cypress-io/github-action

README.md, dist/index.js, index.js, package-lock.json, package.json
That starts local server or whatever is necessary to run in the background for tests to run. Example
```yml
name: With server
on: [push]
jobs:
cypress-run:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v1
- name: Cypress run
uses: cypress-io/github-action@v1
with:
start: npm start
```
- closes #8
- fixes #11 (run `npm ci`)
=> feat: add start parameter

README.md, dist/index.js, index.js
=> feat: add build and wait parameters

README.md, dist/index.js, index.js, package.json
=> feat: add install and working-directory parameters

DEVELOPMENT.md, README.md
that describes how to add new features to this action
=> chore: add development file

DEVELOPMENT.md, dist/index.js, index.js
- closes #18 
Tested in https://github.com/bahmutov/cypress-gh-action-example/tree/test-debug-logs
=> fix: use core.debug method instead of console.log

README.md, action.yml, dist/index.js, index.js
* Add `config` and `config-file` inputs
=> feat: config and config-file inputs

.vscode/settings.json, README.md, dist/index.js, index.js
Another option that changes default (60 seconds) timeout to specific value in seconds
```yml
- uses: cypress-io/github-action@v1
with:
start: npm start
wait-on: http://localhost:8080/status
wait-on-timeout: 120
```
- closes #27
=> Add wait on timeout

README.md, dist/index.js, index.js
- clsoses #34 
```
- uses: cypress-io/github-action@v1
with:
record: true
parallel: true
group: 'Actions example'
ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
env:
CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
```
**Tip:** see GitHub Actions [environment variables](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables) and [expression syntax](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions).
=> Custom ci build

.vscode/settings.json, README.md, dist/index.js, index.js, package-lock.json, package.json
Because `wait-on` seems to time out, wrote my own using `got`
- closes #41 
- closes #42
=> fix: use custom code for wait-on logic

README.md, index.js
=> allow to prefix test command

README.md, dist/index.js, index.js
testing in https://github.com/cypress-io/angular-pizza-creator/pull/36
=> feat: working command prefix

.github/workflows/main.yml, package-lock.json, package.json
sleep better at night knowing the links in Markdown are correct
=> chore: check Markdown links

README.md, dist/index.js, index.js, package-lock.json, package.json
This PR is blocked by this PR on the TR https://github.com/cypress-io/cypress/pull/6394
And PR for the dashboard that is WIP
=> Update customCiBuildId, should use GITHUB_RUN_ID

.github/workflows/example-env.yml, .github/workflows/main.yml, .gitignore, DEVELOPMENT.md, README.md, action.yml, dist/index.js, examples/env/cypress.json, examples/env/cypress/integration/spec.js, examples/env/cypress/integration/without-env-spec.js, examples/env/cypress/plugins/index.js, examples/env/package-lock.json, examples/env/package.json, index.js
- global environment variables should be passed
- additional variables can be passed vis `env: ...` block specific to the action
- closes #85
=> add example with `env` option and without

.github/workflows/example-basic.yml, README.md, examples/basic/cypress.json, examples/basic/cypress/integration/spec.js, examples/basic/package-lock.json, examples/basic/package.json
=> add basic example

.github/workflows/example-start.yml, .prettierrc.json, README.md, dist/index.js, examples/start/cypress.json, examples/start/cypress/integration/spec.js, examples/start/package-lock.json, examples/start/package.json, examples/start/public/index.html, index.js
=> Use working directory when running build and start commands

.github/workflows/example-start-and-yarn-workspaces.yml, README.md
=> add fail-fast note, closes #48

.github/workflows/example-chrome.yml, .github/workflows/example-edge.yml, README.md, action.yml, dist/index.js, examples/chrome/package-lock.json, examples/chrome/package.json, examples/firefox/package-lock.json, examples/firefox/package.json, index.js
- added `cypress info` command
- added Edge example test
- added Edge to README
- closes #105 
- the build command now parses the command string and tries to find the tool better before running the command
=> fix: better build command and Edge browser example

README.md, renovate.json
=> add renovate config file

.github/workflows/example-basic.yml, .vscode/settings.json, README.md, examples/basic/package-lock.json, examples/basic/package.json
just to know which browsers are installed where by default
=> print cypress info from basic example

.github/workflows/example-node-versions.yml, .github/workflows/main.yml, README.md, examples/node-versions/cypress.json, examples/node-versions/cypress/integration/spec.js, examples/node-versions/package-lock.json, examples/node-versions/package.json
- closes #112 
- added example
=> build on Node 10 and Node 12 and test on Node 8, 10 and 12

dist/index.js, index.js, package-lock.json, package.json
=> fix: replace `@octokit/rest` with `@octokit/core`

action.yml
=> fix: add documented command-prefix input

action.yml
Fixes https://github.com/cypress-io/github-action/issues/157
=> fix: add missing configuration options to action specification

.github/workflows/example-recording.yml, README.md, dist/index.js, examples/basic/package-lock.json, examples/basic/package.json, examples/recording/cypress.json, examples/recording/cypress/integration/spec-a.js, examples/recording/cypress/integration/spec-b.js, examples/recording/cypress/integration/spec-c.js, examples/recording/cypress/integration/spec-d.js, examples/recording/package-lock.json, examples/recording/package.json, index.js
- closes #162 
Let's make it into a breaking change, even if everything stays the same, just to make people aware that the change has happened.
=> feat: refactor to use NPM module API to run Cypress

.github/workflows/example-quiet.yml, README.md, action.yml, dist/index.js, examples/quiet/cypress.json, examples/quiet/cypress/integration/spec.js, examples/quiet/cypress/plugins/index.js, examples/quiet/package-lock.json, examples/quiet/package.json, examples/quiet/public/index.html, index.js
add missing `--quiet` parameter to `action.yml` file to avoid `warnings` in console while running in CI as below:
=> feat: add missing parameter `quiet` to action.yml

dist/index.js, index.js
=> fix: Update ciBuildId with jobId

.github/workflows/example-config.yml, README.md, dist/index.js, examples/config/cypress.json, examples/config/cypress/integration/spec.js, examples/config/package-lock.json, examples/config/package.json, examples/config/public/index.html, index.js
closes #207
shows the `config: ...` option in action. If you have a similar example, please look at the logs by setting the GitHub secret
```
ACTIONS_STEP_DEBUG: true
```
=> fix: add config example and fix exit on failed tests

.github/workflows/example-wait-on.yml, README.md, examples/wait-on/README.md, examples/wait-on/cypress.json, examples/wait-on/cypress/integration/spec.js, examples/wait-on/index.js, examples/wait-on/index2.js, examples/wait-on/index3.js, examples/wait-on/package-lock.json, examples/wait-on/package.json
And fix the timeout
- closes #231 
I can see the hanging job (wait-on example, wait3 job)
=> Add several wait-on examples

.github/workflows/example-wait-on.yml, README.md, dist/index.js, examples/wait-on/index3.js, index.js, package-lock.json, package.json, src/ping.js
reworked `ping` method to pass `wait-on` examples
=> fix: bump got dependency to 11.8.0

dist/index.js, examples/wait-on/package-lock.json, examples/wait-on/package.json, index.js
- closes #219 
Prevents Cypress binary folder snowballing and accumulating multiple Cypress versions
Read https://glebbahmutov.com/blog/do-not-let-cypress-cache-snowball/
=> fix: prevent Cypress binary snowball

.github/workflows/example-webpack.yml, README.md, examples/webpack/README.md, examples/webpack/cypress.json, examples/webpack/cypress/integration/spec.js, examples/webpack/index.html, examples/webpack/package-lock.json, examples/webpack/package.json, examples/webpack/src/index.js, examples/webpack/webpack.config.js
Example starts the webpack-dev-server and waits for URL to respond
=> Add webpack dev server example

.github/workflows/example-wait-on.yml, README.md, dist/index.js, index.js
```yml
- uses: cypress-io/github-action@v2
with:
start: npm start
wait-on: 'npx wait-on --timeout 5000 http://localhost:3000'
```
=> feat: allow using custom wait-on command

.github/workflows/example-firefox.yml, examples/firefox/package-lock.json, examples/firefox/package.json
=> bump Cypress to v5.6.0 in Firefox example

.github/workflows/example-install-only.yml, README.md, examples/install-only/README.md, examples/install-only/cypress.json, examples/install-only/cypress/integration/spec.js, examples/install-only/package-lock.json, examples/install-only/package.json
=> add example for install Cypress only case

.github/workflows/example-basic.yml, dist/index.js, examples/basic/package-lock.json, examples/basic/package.json, index.js
=> fix: skip cypress verify and info if skipping binary

dist/index.js, index.js
=> feat: always provide ci-build-id so actions can be re-run (#340)

.github/workflows/example-debug.yml, README.md, dist/index.js, index.js, package-lock.json, package.json, src/ping.js
=> feat: switch to debug module for verbose logs

README.md
I believe the version of the action should be consistent with all of the rest of the example. Implemented in in this way actually by myself and everything works perfectly.
=> [Docs] Update action's version on 'Custom test command'

.github/workflows/example-basic.yml, .github/workflows/example-chrome.yml, .github/workflows/example-config.yml, .github/workflows/example-custom-ci-build-id.yml, .github/workflows/example-custom-command.yml, .github/workflows/example-debug.yml, .github/workflows/example-edge.yml, .github/workflows/example-env.yml, .github/workflows/example-firefox.yml, .github/workflows/example-install-command.yml, .github/workflows/example-install-only.yml, .github/workflows/example-node-versions.yml, .github/workflows/example-quiet.yml, .github/workflows/example-recording.yml, .github/workflows/example-start-and-yarn-workspaces.yml, .github/workflows/example-start.yml, .github/workflows/example-wait-on.yml, .github/workflows/example-webpack.yml, .github/workflows/main.yml, examples/start/cypress.json, examples/start/package-lock.json, examples/start/package.json
Per:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull-request-events-for-forked-repositories-1
https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks
=> chore: Add pull_request to GHA triggers to run workflows against public PR's when approved

.github/workflows/example-basic-pnpm.yml, .github/workflows/example-basic.yml, .github/workflows/example-chrome.yml, .github/workflows/example-component-test.yml, .github/workflows/example-config.yml, .github/workflows/example-cron.yml, .github/workflows/example-custom-ci-build-id.yml, .github/workflows/example-custom-command.yml, .github/workflows/example-debug.yml, .github/workflows/example-edge.yml, .github/workflows/example-env.yml, .github/workflows/example-install-command.yml, .github/workflows/example-install-only.yml, .github/workflows/example-quiet.yml, .github/workflows/example-recording.yml, .github/workflows/example-start-and-yarn-workspaces.yml, .github/workflows/example-start.yml, .github/workflows/example-wait-on.yml, .github/workflows/example-webpack.yml, DEVELOPMENT.md, README.md, package-lock.json, package.json
Fixes:
- https://github.com/cypress-io/github-action/pull/528, https://github.com/cypress-io/github-action/issues/336
- https://github.com/cypress-io/github-action/pull/516
- https://github.com/cypress-io/github-action/pull/515
=> update action dependencies

dist/index.js, package-lock.json, package.json
Combined GH dependency & dev deps bumps, dist rebuild
=> fix(deps): combined renovate bot bumps

DEVELOPMENT.md
This PR resolves https://github.com/cypress-io/github-action/issues/742.
It delivers an updated [DEVELOPMENT.md](https://github.com/cypress-io/github-action/blob/master/DEVELOPMENT.md) document which takes account of changes in automated processing of action builds and checking through the [Husky pre-commit hook](https://github.com/cypress-io/github-action/blob/master/.husky/pre-commit) and through [github/workflows/check-dist.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/check-dist.yml).
It makes it clearer about the necessary technical steps that Contributors to the repository should take.
=> docs: update submission instructions in DEVELOPMENT.md

.github/workflows/example-recording.yml, .github/workflows/example-start-and-yarn-workspaces.yml, README.md, action.yml, dist/index.js, examples/recording/package.json, examples/v9/recording/package.json, index.js
=> fix: update dashboard refs to cloud

dist/index.js, package-lock.json
This PR resolves vulnerabilities by updating
[package-lock.json](https://github.com/cypress-io/github-action/blob/master/package-lock.json)
using `npm audit fix`.
**BEFORE**
6 vulnerabilities (5 moderate, 1 high)
**AFTER**
found 0 vulnerabilities
=> fix(deps): npm audit fix vulnerabilities

CHANGELOG.md, README.md
Correct remaining references to v5.
- https://github.com/cypress-io/cypress-documentation/pull/5458
- #1009 
- #1014
=> docs: add changelog for 6.3.0 and 6.4.0

examples/webpack/package-lock.json, examples/webpack/package.json
Installing dependencies in [examples/webpack](https://github.com/cypress-io/github-action/tree/master/examples/webpack) reports vulnerabilities:
> 2 vulnerabilities (1 moderate, 1 high)
Update to latest dependencies in [examples/webpack](https://github.com/cypress-io/github-action/tree/master/examples/webpack) and run `npm audit fix`.
Execute
```shell
cd examples/webpack
npm ci
npm start
```
then execute `npm test` in separate terminal window.
Confirm that no vulnerabilities are reported and that Cypress test passes.
=> chore(deps): update example webpack
