README.md, dist/index.js, index.js
If `yarn.lock` is found, then yarn will be used to install NPM dependencies
See https://github.com/bahmutov/yarn-cypress-cache/commit/264ea485d1256ad2ea297499cc22bed70290f082/checks?check_suite_id=307916678 for example
=> feat: support yarn

README.md, dist/index.js, index.js, package-lock.json, package.json
- closes #3 
- closes #4 
By enforcing custom NPM and Cypress caching folders across different platforms. Example build https://github.com/bahmutov/yarn-cypress-cache/commit/99d1ef534b434f2c96eea0a6859c3bb1ff78a3aa/checks?check_suite_id=308154793
```yml
jobs:
build:
strategy:
matrix:
os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
runs-on: ${{ matrix.os }}
steps:
- uses: actions/checkout@v1
- name: Cypress run
uses: cypress-io/github-action@0077a8c
```
=> feat: support Mac and Windows

README.md, dist/index.js, index.js
- closes #23 
```yml
name: End-to-end tests
on: [push]
jobs:
cypress-run:
runs-on: ubuntu-latest
strategy:
matrix:
node: [10, 12]
name: E2E on Node v${{ matrix.node }}
steps:
- name: Setup Node
uses: actions/setup-node@v1
with:
node-version: ${{ matrix.node }}
- name: Checkout
uses: actions/checkout@v1
- name: Cypress run
uses: cypress-io/github-action@v1
with:
record: true
group: Tests on Node v${{ matrix.node }}
cache-key: node-v${{ matrix.node }}-on-${{ runner.os }}-hash-${{ hashFiles('yarn.lock') }}
env:
CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
```
=> feat: add cache-key parameter

README.md, action.yml, dist/index.js, index.js
* adds `env` input (closes [cypress-io/actions #25](https://github.com/cypress-io/github-action/issues/25))
=> feat: add env input - #25

.github/workflows/main.yml, README.md, dist/index.js, index.js, package-lock.json, package.json
Installing dependencies should take into account "working-directory" parameter
- closes #46 
If your project structure is
```text
root/
e2e/
(code for installing and running Cypress tests)
package.json
package-lock.json
cypress.json
cypress
(code for running the "app" with "npm start")
package.json
yarn.lock
```
Then this works
```yml
name: E2E
on: push
jobs:
test:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@master
- name: Install root dependencies
uses: bahmutov/npm-install@v1
- name: Start server in the background
run: npm start &
- name: Install Cypress and run tests
uses: cypress-io/github-action@4e415ee
with:
working-directory: e2e
```
See https://github.com/bahmutov/cypress-gh-action-subfolders
=> feat: allow installing using "working-directory" folder parameter

index.js
This only moves the pinging to debug, otherwise leaves the timeout and the initialisation of `wait-on` as console outputs.
Also, instead of adding a flag to `wait-on` I figured it made more sense to use the default debug variable.
Fixes #45
=> fix: move ping logs to debug mode

README.md
github have changed the latest ubuntu version to 18.04 which Cypress doesn't seem to yet support, this changes the readme to pin 16.04 until supported
resolves #65
=> docs: pin runs-on ubuntu version to 16.04 in readme

.github/workflows/example-basic.yml, examples/basic/cypress/integration/spec.js
- confirming screen resolution problem problem reported in #88
Storing screenshots as artifacts, see https://github.com/cypress-io/github-action/actions/runs/42034757
Noticed: screenshot in Electron is 1280x720
The same screenshot in Chrome 80 is 1050x888
=> Screenshot resolution test

.github/workflows/example-basic.yml, .github/workflows/example-chrome.yml, .gitignore, README.md, examples/chrome/cypress.json, examples/chrome/cypress/integration/spec.js, examples/chrome/cypress/plugins/index.js, examples/chrome/package-lock.json, examples/chrome/package.json
and storing them as artifacts and printing image dimensions for #88
=> Taking screenshots in Electron and Chrome

.github/workflows/example-chrome.yml, examples/chrome/cypress/integration/spec.js, examples/chrome/cypress/plugins/index.js
- closes #88 
Hmm, for a while I thought the user would need to spin their own Xvfb server with custom parameters like this to get higher resolution screen
```
xvfb-run --server-args="-screen 0 1920x1080x24" cypress run --browser chrome --headless
```
But when I tried the simplest solution it worked: run Cypress as before and just pass the flag in the plugin to tell Chrome to use the larger resolution
```js
module.exports = on => {
on('before:browser:launch', (browser, launchOptions) => {
if (browser.name === 'chrome') {
// https://www.ghacks.net/2013/10/06/list-useful-google-chrome-command-line-switches/
launchOptions.args.push('--window-size=1920,1080')
return launchOptions
}
})
}
```
The produced images are 1920x1020 (or similar without the top bar) for the runner, see …
=> use Chrome window size 1920,1080

action.yml, dist/index.js
Fixes warnings about invalid inputs by adding input settings to `action.yml` - the warnings that appear are described in #141 and look like so:
=> fix: add missing inputs to action.yml to prevent warnings - #141

action.yml
Add missing spec input to action.yml to prevent warnings in console log as on screenshot below:
=> fix: add missing spec input to action.yml

README.md, action.yml, dist/index.js, index.js
* Adds input for `project` cli option [documented here](https://docs.cypress.io/guides/guides/command-line.html#cypress-run-project-lt-project-path-gt) to allow for running tests within a project folder
=> feat: add project input

.github/workflows/example-recording.yml, README.md, action.yml, dist/index.js, index.js
- closes #150 
setting output via https://github.com/actions/toolkit/tree/master/packages/core#inputsoutputs
Typical use case
```yml
- name: Cypress tests
uses: cypress-io/github-action@v2
id: cypress
continue-on-error: true
with:
record: true
env:
CYPRESS_RECORD_KEY: ${{ secrets.RECORDING_KEY }}
- name: Print Dashboard URL
run: |
echo Cypress finished with: ${{ steps.cypress.outcome }}
echo See results at ${{ steps.cypress.outputs.dashboardUrl }}
```
=> feat: export dashboard url from the action

dist/index.js, index.js
- closes #212
Catches cache restore errors and just prints a warning, rather than failing the job. Tested in https://github.com/bahmutov/eleventy-example/pull/10
=> fix: ignore restore cache error

dist/index.js, index.js
prints the list of binaries in the global cache after the install
=> fix: list Cypress cached versions after install

dist/index.js, index.js
in situations when the job specified `working-directory` parameter, `actions/exec` would fail to run `yarn` or `npm` if the working directory was not absolute.
- closes #211
=> fix: resolve working-directory if specified

.github/workflows/example-wait-on.yml, README.md, dist/index.js, examples/wait-on/index.js, examples/wait-on/index2.js, examples/wait-on/index3.js, examples/wait-on/package-lock.json, examples/wait-on/package.json, index.js
When you need to start webserver and API for example. Separate commands with comma
```yml
- name: Cypress tests
uses: cypress-io/github-action@v2
with:
start: npm run api, npm run web
wait-on: 'http://localhost:3050' 
```
- for #128
For now wait for the longest starting process
=> feat: start several services in parallel

.github/workflows/example-wait-on.yml, README.md, dist/index.js, index.js
- closes #152 
- closes #128
Separate urls with a comma
```yml
with:
working-directory: examples/wait-on
start: npm start -- --port 3050, npm run start2 -- --port 3060, node ./index3 --port 3070
wait-on: 'http://localhost:3050, http://localhost:3060, http://localhost:3070'
```
=> feat: wait on multiple urls

.github/workflows/example-wait-on.yml, dist/index.js, examples/wait-on/README.md, examples/wait-on/index4.js, examples/wait-on/package.json, src/ping-cli.js, src/ping.js
closes #235 
Adding a test where the server takes 5 seconds to respond to every request, shows our `ping` logic timing out. Reworked ping to quickly retry on `ECONNREFUSED` but use long timeout (30 seconds) for other errors.
=> fix: use longer ping timeout for wait-on pings

.github/workflows/example-firefox.yml
Seems the Docker container is just making everything flaky, and Ubuntu GH Action environments have Firefox 82 pre-installed
=> Run Firefox example without using Docker containers

.github/workflows/example-basic.yml
closes https://github.com/cypress-io/github-action/issues/251
the .github/workflows/example-basic.yml tests Cypress on Ubuntu 16, 18, and 20. Shows that no additional OS dependencies are necessary, GH virtual environments already have everything we need
=> chore: confirm Cypress v6 runs on ubuntu 16

index.js
When using `install: false`, the Cypress binary needs to be installed manually. If this is done a separate job, the caching gets complicated if the binary is in the home directory. Setting the env var `CYPRESS_CACHE_FOLDER: ${{ github.workspace }}/node_modules/.cache/Cypress` makes this trivial, but is currently not supported by this action as the cache folder path is hard-coded. This change adds support for overriding the path with the environment var.
=> fix: respect the CYPRESS_CACHE_FOLDER environment variable

.github/workflows/example-config.yml, README.md, dist/index.js, examples/config/cypress/integration/spec-a.js, examples/config/cypress/integration/spec-b.js, index.js
- closes #289
Allow multiline spec parameter, like
```yml
spec: |
cypress/integration/spec-a.js
cypress/**/*-b.js
```
Added examples to the config workflow
=> feat: handle specs on separate lines

.github/workflows/example-start.yml, README.md, dist/index.js, examples/start/package-lock.json, examples/start/package.json, index.js
- closes #309 by adding more debug logs 
- closes #311
- added example that starts multiple services
- allows putting start commands one per line
```
start: |
npm start
npm run start2
```
=> feat: allow placing start commands on separate lines

index.js
closes #363 
I know that there are known workarounds for this, mentioned both in the [README](https://github.com/cypress-io/github-action#parallel) and some [issue comments](https://github.com/cypress-io/github-action/issues/177).
Since this is relevant not only for parallel runs I think that adding this at all times would improve the DX and provide this improvement out of the box for all users. The expected result is that a GitHub action should be able to re-run the workflow and create a new test run in the Cypress dashboard.
=> feat: always provide ci-build-id so actions can be re-run

.github/workflows/example-recording.yml, dist/index.js, index.js
closes #365 
added a workflow with recording with just group name
=> fix: send ci-build-id only in parallel or group mode

.github/workflows/example-custom-ci-build-id.yml, README.md, dist/index.js
Based on the idea described in https://medium.com/attest-r-and-d/adding-a-unique-github-build-identifier-7aa2e83cadca
- first job generates a unique id and sets it as an output
- test jobs use that unique id as ci-build-id
- the user can then re-run the workflow without problems, it is recorded as a new Dashboard run
=> Add example with a custom build

index.js
Only quotes arguments on Windows when they contain [argument delimiters](https://ss64.com/nt/syntax-esc.html).
resolves #459
=> quote Windows arguments based on delimeters

README.md
Update README doc file upgrading the upload-artifact Github actions to v2 as it is in the example workflows.
=> chore: update upload-artifact version in readme doc

.github/workflows/main.yml
=> Use latest version of @semantic-release/git to re-enable semantic releases

README.md
The readme references a "Cypress 10" section that doesn't exist anymore since all the examples have been updated.
=> docs: remove outdated README reference

.github/workflows/example-chrome.yml, README.md, action.yml, dist/index.js, index.js
- Addresses issue [#403](https://github.com/cypress-io/github-action/issues/403);
- Because `cypress run` executes tests in `headless` mode by default we need to bring back the flag which toggles `headed` vs `headless` execution in CI;
=> fix: make headed execution available again

dist/index.js, index.js
The workflow summary is currently not available on GitHub Enterprise.
When trying to use the API it will result in the following error:
```
Error: Unable to find environment variable for $GITHUB_STEP_SUMMARY. Check if your runtime environment supports job summaries.
at Summary.<anonymous> (/runner/_work/_actions/philipparndt/cy-github-action/disable-summary-on-ghe/dist/index.js:1810:23)
Error: Unable to find environment variable for $GITHUB_STEP_SUMMARY. Check if your runtime environment supports job summaries.
at Generator.next (<anonymous>)
at /runner/_work/_actions/philipparndt/cy-github-action/disable-summary-on-ghe/dist/index.js:1783:71
at new Promise (<anonymous>)
at __webpack_modules__.1327.__awaiter (/runner/_work/_actions/philipparndt/cy-github-action/disable-summary-on-ghe/dist/i …
```
=> Fix: Disable summary when it is not available

.github/workflows/example-basic-pnpm.yml, dist/index.js, examples/v10/basic-pnpm/cypress.config.js, examples/v10/basic-pnpm/cypress/e2e/spec.cy.js, examples/v10/basic-pnpm/package.json, examples/v10/basic-pnpm/pnpm-lock.yaml, examples/v9/basic-pnpm/cypress.json, examples/v9/basic-pnpm/cypress/integration/spec.js, examples/v9/basic-pnpm/package.json, examples/v9/basic-pnpm/pnpm-lock.yaml, index.js
=> feat: add support for pnpm (install and cache deps)

README.md
I intentionally did not change references to `dashboardUrl` (I don't think `cloudUrl` exists yet).
=> Update Dashboard references to Cloud

.github/workflows/example-node-versions.yml, .github/workflows/main.yml, package-lock.json, package.json
BREAKING CHANGE:
Add node v18 support & remove deprecated v12.
- add node v18, remove deprecated v12 in `example-node-versions.yml` test matrix
- add node v18, remove v12 in `main.yml`
- bump `ncc` pkg to fix `ERR_OSSL_EVP_UNSUPPORTED` errors intruduced in node > node v16 (https://github.com/vercel/ncc/pull/868)
- bump `@types/node` to latest
- bump `actions/setup-node`, `actions/checkout` to v3 to prevent  < v16 deprecation warnings
- rename tests for clarity
=> feat: upgrade to use Node v18, remove v12

.github/workflows/example-firefox.yml, .github/workflows/example-install-only.yml, examples/v10/react-scripts/package-lock.json, examples/v9/react-scripts/package-lock.json
Targeting a few failing tests that have been part of the previous GHA releases with some fixes.
There are related open issues [#1](https://github.com/cypress-io/cypress/issues/22086), [#2](https://github.com/cypress-io/cypress/issues/18919), [#3](https://github.com/cypress-io/github-action/issues/104) with FF that still cause flake in one test that will need a separate effort.
=> fix: update failed tests

README.md
This PR resolves issue https://github.com/cypress-io/github-action/issues/663 "Broken links in README"
It corrects bad links in the [README.md](https://github.com/cypress-io/github-action/blob/master/README.md) document which caused [400 (Bad Request)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400) and [404 (Not Found)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404) errors.
In addition it replaces links in [README.md](https://github.com/cypress-io/github-action/blob/master/README.md) which were previously pointing to documents on https://help.github.com/. Links now use https://docs.github.com/ instead.
The use of the new links takes account of the help restructuring by bundling some links together for a better user experience and to better isolate from …
=> Correct broken links in README.md

md-linkcheck.json, package-lock.json, package.json
This PR resolves issue https://github.com/cypress-io/github-action/issues/664 "markdown-link-check produces wrong results and exit status"
1. To resolve the issue that link checking on the domain [github.com](https://github.com/) results in 403 Forbidden errors, the new markdown-link-check configuration file `md-linkcheck.json` is added and it is referred to by the script `check:markdown`. After adding this config file, checks on links to github.com no longer produce a 403 error.
2. To resolve the issue that the action [main.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/main.yml) is successful, even when the markdown link check fails, the check:markdown script is converted to use `xargs` instead of `exec` as suggested in …
=> Make check:markdown successful for github domain checks

.github/workflows/example-start.yml, examples/v10/start/package-lock.json, examples/v10/start/package.json, examples/v9/start/package-lock.json, examples/v9/start/package.json
This PR resolves issue https://github.com/cypress-io/github-action/issues/657 "CI: Sporadic failures in example-start running multiple servers".
It modifies the action [.github/workflows/example-start.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-start.yml):
1. by disabling [update-check](https://www.npmjs.com/package/update-check) through environment variable `NO_UPDATE_CHECK` = 1 and
2. by updating [serve](https://www.npmjs.com/package/serve) to the latest version (14.1.2). [serve Version 14](https://github.com/vercel/serve#usage) requires a minimum of Node.js 14. This is compatible with [GHA v5](https://github.com/cypress-io/github-action/releases/tag/v5.0.0) which removes Node.js 12 support. (The Node.js 14 version is in [maintenance …
=> Resolve sporadic failures in example-start running multiple servers

.github/workflows/example-firefox.yml
This PR resolves the issue https://github.com/cypress-io/github-action/issues/659 "CI: Sporadic failures in example-firefox".
The Firefox test under Cypress v9 in [.github/workflows/example-firefox.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-firefox.yml) is disabled, since it is unreliable and the issue has been shown to be reproducible on a local machine independently of github-action.
This allows the Cypress v10 test to then run reliably.
=> Skip Firefox test using Cypress v9 to resolve flaky tests

.github/workflows/example-basic-pnpm.yml
This PR resolves the deprecation warnings produced by running [.github/workflows/example-basic-pnpm.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic-pnpm.ym). It solves one item of issue https://github.com/cypress-io/github-action/issues/648 "Deprecated Ubuntu 18.04 used in example workflows".
The previous deprecation warnings, for instance in run [3643305664](https://github.com/cypress-io/github-action/actions/runs/3643305664), were:
"Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2"
and
"The ubuntu-18.04 environment is deprecated, consider …
=> Resolve deprecation warnings for example-basic-pnpm

.github/workflows/example-basic.yml
This PR resolves the deprecation warnings produced by running [.github/workflows/example-basic.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic.yml). It solves one item of issue https://github.com/cypress-io/github-action/issues/648 "Deprecated Ubuntu 18.04 used in example workflows".
The previous deprecation warnings, for instance in run [3643305670](https://github.com/cypress-io/github-action/actions/runs/3643305670), were:
"Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2"
and
"The ubuntu-18.04 environment is deprecated, consider switching to …
=> Resolve deprecation warnings for example-basic

.github/workflows/example-basic-pnpm.yml, .github/workflows/example-basic.yml, .github/workflows/example-component-test.yml, .github/workflows/example-recording.yml, README.md
Hi there 👋 As always, thanks for your continued efforts in the end to end / integration test automation space!
Here's a quick PR to upgrade to [the new `5.0.0` version](https://github.com/cypress-io/github-action/releases/tag/v5.0.0)
=> Upgrade version in examples

.github/workflows/example-custom-ci-build-id.yml
This PR resolves issue https://github.com/cypress-io/github-action/issues/674 "CI: example-custom-ci-build-id uses deprecated set-output method" by converting the use of `set-output` to the current recommendations for [setting an output parameter](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter) from the [GitHub documentation: Workflow commands for GitHub Actions](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions).
`run: echo "::set-output name=value::sha-$GITHUB_SHA-time-$(date +"%s")"`
is replaced by
`run: echo "value=sha-$GITHUB_SHA-time-$(date +"%s")" >> $GITHUB_OUTPUT`
In addition some comment text has been updated, including changing references from Cypress Dashboard to Cypress …
=> Replace deprecated set-output in example-custom-ci-build-id by environment files

.github/workflows/example-chrome.yml
This PR resolves issue https://github.com/cypress-io/github-action/issues/669 "CI: Workflow chrome shows Annotations warnings".
It updates the example workflow [.github/workflows/example-chrome.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-chrome.yml) by
1. correcting the paths for artifact uploads. Adds `v9` for v9 tests. 
2. ensuring that the artifact names are unique. Appends `-v10` to v10 tests.
3. converting the incorrect parameter `headless: true` to `headed: false`
Edit: In addition, as requested, the v9 test, and artifacts produced by it, have `-v9` added to their labels.
View the action logs for https://github.com/cypress-io/github-action/actions/workflows/example-chrome.yml and check that there are no longer any Annotations warnings.
The …
=> Clear Annotations warnings from example-chrome workflow

examples/v10/start-and-yarn-workspaces/workspace-1/package.json, examples/v10/start-and-yarn-workspaces/workspace-2/package.json, examples/v10/start-and-yarn-workspaces/yarn.lock, examples/v9/start-and-yarn-workspaces/workspace-1/package.json, examples/v9/start-and-yarn-workspaces/workspace-2/package.json, examples/v9/start-and-yarn-workspaces/yarn.lock
Fixed changed default port for serve
This PR adds to the existing draft PR https://github.com/cypress-io/github-action/pull/673 which fails in run [3709862504](https://github.com/cypress-io/github-action/actions/runs/3709862504) due to mismatch of ports:
```text
$ serve public
INFO  Accepting connections at http://localhost:3000
http://localhost:5000 timed out on retry 91 of 3, elapsed 90268ms, limit 90000ms
Error: connect ECONNREFUSED 127.0.0.1:5000
```
The `serve` port is changed to explicitly specify `5000`.
=> fix upgrade to serve 14.1.2 in start-and-yarn-workspaces

README.md
This PR resolves a new issue that `npm run check:markdown` fails on GitHub when checking the link https://renovateapp.com/ in the [README](https://github.com/cypress-io/github-action/blob/master/README.md) file. The error is HTTP 403 forbidden.
When run locally there is no failure and https://renovateapp.com/ redirects to https://renovatebot.com/ and then to https://www.mend.io/free-developer-tools/renovate/.
I have replaced the link
https://renovateapp.com/
by
https://github.com/renovatebot
and this passes the `npm run check:markdown` check on GitHub.
CloudFront is blocking access to https://www.mend.io/free-developer-tools/renovate/ from GitHub by responding with 403 forbidden. A `cy.visit('https://www.mend.io/free-developer-tools/renovate/)` run on GitHub also fails.
`curl -v …
=> Resolve markdown-link-check forbidden with renovate app link

README.md
This PR corrects the reference to the Ubuntu versions used by the [example-basic.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic.yml) workflow described in README section [Basic](https://github.com/cypress-io/github-action/blob/master/README.md#basic).
The currently used versions are:
- `runs-on: ubuntu-20.04`
- `runs-on: ubuntu-22.04`
=> Correct ubuntu versions for basic example

README.md
This PR resolves issue https://github.com/cypress-io/github-action/issues/691 "README lists unsupported Node.js versions 10 and 12".
Instances in [README.md](https://github.com/cypress-io/github-action/blob/master/README.md) with examples using `node: [10, 12]` are updated to use the current set of supported Node.js versions `node: [14, 16, 18]` instead.
=> Update supported Node.js versions in README

scripts/npm-install-v10-examples.sh
This PR resolves issue https://github.com/cypress-io/github-action/issues/699 "npm-install-v10-examples script targets yarn example-install-command".
It removes the incorrect instruction
```bash
cd ../install-command && npm install cypress@latest
```
from [npm-install-v10-examples.sh](https://github.com/cypress-io/github-action/blob/master/scripts/npm-install-v10-examples.sh).
Since [examples/v10/install-command](https://github.com/cypress-io/github-action/tree/master/examples/v10/install-command) is based on `yarn` it must only be updated using `yarn` rather than `npm`.
Execute [npm-install-v10-examples.sh](https://github.com/cypress-io/github-action/blob/master/scripts/npm-install-v10-examples.sh) locally and ensure that there is no change to the files in the directory …
=> Remove scripted npm update for yarn-based install-command

.github/workflows/example-firefox.yml, examples/v10/firefox/cypress.config.js, examples/v9/firefox/cypress.json
This PR resolves the issue https://github.com/cypress-io/github-action/issues/661 "CI: Artifact and video warnings in example-firefox".
1. It corrects [.github/workflows/example-firefox.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-firefox.yml) by selecting the right directory to upload the screenshots captured by the Cypress v9 test and makes the name unique under which the artifacts are stored on GitHub.
2. It disables videos to prevent a video warning message appearing which is a known problem under Firefox (see https://github.com/cypress-io/cypress/issues/18415).
3. ~~`.gitignore` files are created for both v9 and v10 Firefox tests in case the tests are used locally (rather than in the workflow).~~ Edit: removed.
Find a successful run of the …
=> Correct Firefox example artifacts and video

.github/workflows/example-basic-pnpm.yml, .github/workflows/example-basic.yml, .github/workflows/example-chrome.yml, .github/workflows/example-config.yml, .github/workflows/example-cron.yml, .github/workflows/example-custom-ci-build-id.yml, .github/workflows/example-custom-command.yml, .github/workflows/example-debug.yml, .github/workflows/example-env.yml, .github/workflows/example-firefox.yml, .github/workflows/example-install-command.yml, .github/workflows/example-install-only.yml, .github/workflows/example-node-versions.yml, .github/workflows/example-quiet.yml, .github/workflows/example-recording.yml, .github/workflows/example-start-and-yarn-workspaces.yml, .github/workflows/example-start.yml, .github/workflows/example-wait-on.yml, .github/workflows/example-webpack.yml, .github/workflows/main.yml, DEVELOPMENT.md, README.md
This PR implements the suggestion from https://github.com/cypress-io/github-action/issues/696 "Update to Ubuntu 22.04 as standard".
It converts [workflows](https://github.com/cypress-io/github-action/tree/master/.github/workflows) which previously only ran on [ubuntu-20.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md) or only on `ubuntu-latest` to instead run only on [ubuntu-22.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md). (Any workflows which run on both [ubuntu-20.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md) and [ubuntu-22.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md) may still retain an example of …
=> Update to generally run on ubuntu-22.04 in workflows

README.md
This corrects the example https://github.com/cypress-io/github-action/blob/master/README.md#start-multiple-servers
`runs-on: ubuntu-18.04`
now reads
`runs-on: ubuntu-22.04`
It was overlooked, as the only example still specifying `ubuntu-18.04` and it should have been handled by PR https://github.com/cypress-io/github-action/pull/720. ([ubuntu-18.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu1804-Readme.md) is deprecated.)
=> Correct README for "Start multiple servers" to use ubuntu-22.04

README.md
This PR resolves issue https://github.com/cypress-io/github-action/issues/709 "Linked archived 'More examples' in README using @v1 fail"
The archived and failing example repositories as follows are removed from the README section [More examples](https://github.com/cypress-io/github-action#more-examples):
| Failing examples using GHA @v1                                                                           |
| -------------------------------------------------------------------------------------------------------- |
| [cypress-io/cypress-and-jest-typescript-example](https://github.com/cypress-io/cypress-and-jest-typescript-example) |
| [cypress-io/cypress-gh-action-vue-example](https://github.com/cypress-io/cypress-gh-action-vue-example)             |
| …
=> Remove non-working archived example links

README.md
This PR resolves issue https://github.com/cypress-io/github-action/issues/688 "Missing working-directory description for v10 and later".
It changes the working-directory example to use `app-test` instead of `e2e` (to avoid confusion with the default `cypress` sub-folder `e2e`) and it adds examples for v10.
The examples now link to directories in this repository instead of to https://github.com/bahmutov/cypress-gh-action-monorepo, in order to provide for v9-type and v10-type End-to-End examples and v10-type Component test examples.
Also viewable for review on https://github.com/MikeMcC399/github-action/blob/docs/working-directory/README.md#working-directory.
=> Update description of working-directory parameter for v10 and later

README.md
This PR resolves issue https://github.com/cypress-io/github-action/issues/713 "Microsoft Edge browser available on Linux".
The statement:
"**Note:** Microsoft has not released Edge for Linux yet, thus you need to run these tests on Windows or Mac runners with Edge preinstalled."
in the README file section [Edge](https://github.com/cypress-io/github-action/blob/master/README.md#edge) is no longer correct. The paragraph is removed.
*Edge for Linux became generally available in November 2021 and the current GitHub runners [ubuntu-20.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#browsers-and-drivers) and [ubuntu-22.04](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#browsers-and-drivers) contain Edge …
=> Remove outdated comment on Edge availability on Linux

README.md
This correct the typo in Specs section.
Previously it was like that:
`You can pass multiple multiple specs and wild card patterns using multi-line parameter, see [example-config.yml](https://file+.vscode-resource.vscode-cdn.net/Users/uzairkhan/Repos/github-action/.github/workflows/example-config.yml):`
Now it will show like that:
`You can pass multiple specs and wild card patterns using multi-line parameter, see [example-config.yml](https://file+.vscode-resource.vscode-cdn.net/Users/uzairkhan/Repos/github-action/.github/workflows/example-config.yml):`
=> Update README.md for Specs section 

README.md
This PR resolves issue https://github.com/cypress-io/github-action/issues/733 "Command prefix example angular-pizza-creator outdated by" removing the reference to the archived repository https://github.com/cypress-io/angular-pizza-creator:
"See live example [angular-pizza-creator](https://github.com/cypress-io/angular-pizza-creator)."
from the [README: Command prefix](https://github.com/cypress-io/github-action#command-prefix) section.
The example is archived, read-only, with no further development expected and it relies on Node.js 12 which has reached end-of-life. It will finally fail in Summer 2023 as GitHub plans to remove support for Node.js 12.
=> Remove outdated angular-pizza-creator from README

README.md, package.json
This PR resolves issue https://github.com/cypress-io/github-action/issues/744 "Package description lacks 'component test'"
It adds the text "component tests" to the descriptions in
- [README.md](https://github.com/cypress-io/github-action/blob/master/README.md) and
- [package.json](https://github.com/cypress-io/github-action/blob/master/package.json)
=> Add "component tests" to action description

.github/workflows/example-chrome.yml
This PR resolves issue https://github.com/cypress-io/github-action/issues/734 "Chrome example contains failing jobs (ffprobe and mplayer)"
It removes the test steps `ffprobe` and `mplayer` from [.github/workflows/example-chrome.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-chrome.yml).
The utilities are not loaded, the tests are therefore failing. Since these tests are not necessary, they are removed.
View a workflow run in https://github.com/cypress-io/github-action/actions/workflows/example-chrome.yml, select:
- tests-v9 or
- tests
Ensure that there is no occurrence of:
- "Run ffprobe cypress/videos/*.mp4 || true" or
- "Run mplayer -really-quiet -ao null -vo null -identify -frames 0 cypress/videos/*.mp4 || true"
=> Remove ffprobe and mplayer from chrome test

.github/workflows/example-basic-pnpm.yml, .github/workflows/example-basic.yml, .github/workflows/example-chrome.yml, .github/workflows/example-component-test.yml, .github/workflows/example-config.yml, .github/workflows/example-cron.yml, .github/workflows/example-custom-ci-build-id.yml, .github/workflows/example-custom-command.yml, .github/workflows/example-debug.yml, .github/workflows/example-edge.yml, .github/workflows/example-env.yml, .github/workflows/example-firefox.yml, .github/workflows/example-install-command.yml, .github/workflows/example-install-only.yml, .github/workflows/example-node-versions.yml, .github/workflows/example-quiet.yml, .github/workflows/example-recording.yml, .github/workflows/example-start-and-yarn-workspaces.yml, .github/workflows/example-start.yml, .github/workflows/example-wait-on.yml, .github/workflows/example-webpack.yml
This PR implements the suggestion from issue https://github.com/cypress-io/github-action/issues/678 "Add workflow_dispatch to examples".
It adds `workflow_dispatch` to each of the workflow examples in [.github/workflows](https://github.com/cypress-io/github-action/tree/master/.github/workflows).
This enables any of the example workflows to be run manually, which is very helpful to test an individual workflow, especially after changes have been made.
=> Allow all example workflows to be triggered manually

README.md
This PR resolves the documentation issue https://github.com/cypress-io/github-action/issues/680 "Example uses Docker image with end-of-life Node.js 12".
In the documentation examples
- [Docker image](https://github.com/cypress-io/github-action#docker-image) 
- [Firefox](https://github.com/cypress-io/github-action#firefox)
the Cypress Docker image
- [cypress/browsers:node18.12.0-chrome106-ff106](https://github.com/cypress-io/cypress-docker-images/tree/master/browsers/node18.12.0-chrome106-ff106) is substituted for the 
- [cypress/browsers:node12.13.0-chrome78-ff70](https://github.com/cypress-io/cypress-docker-images/tree/master/browsers/node12.13.0-chrome78-ff70) Docker image,
since Node.js 12 already passed End-of-Life last year on 2022-04-30 according to the [End-of-Life …
=> Update Docker examples in README to Node.js 18

README.md
This PR corrects the example instructions in [README: "Debugging waiting for URL to respond"](https://github.com/cypress-io/github-action/blob/master/README.md#debugging-waiting-for-url-to-respond).
The correct example use of `ping` from the CLI is:
```bash
$ node src/ping-cli.js https://example.cypress.io
```
Attempting to call `src/ping.js` is incorrect, does nothing and produces no output.
Follow the example instructions and execute
```bash
node src/ping-cli.js https://example.cypress.io
```
from a `bash` terminal window.
Check the response:
```text
pinging url https://example.cypress.io for 30 seconds
```
=> Correct README typo for ping debug example

.github/workflows/check-markdown.yml, .github/workflows/main.yml
This PR resolves issue https://github.com/cypress-io/github-action/issues/717 "Bad external links may block release". It is a rework of PR https://github.com/cypress-io/github-action/pull/762.
In [.github/workflows/main.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/main.yml) `npm run check:markdown` is removed from the `build-and-test` job and placed it inside a new independent workflow [.github/workflows/check-markdown.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/check-markdown.yml).
This means that a release can optionally be carried out independently of a markdown link error. This may be necessary and desired if a link failure is caused by a temporary issue on an external website. If on the other hand there is a hard …
=> Remove release dependency on markdown link check (Rev2)

examples/config/package-lock.json, examples/config/package.json, examples/start-and-yarn-workspaces/workspace-1/package.json, examples/start-and-yarn-workspaces/workspace-2/package.json, examples/start-and-yarn-workspaces/yarn.lock, examples/start/package-lock.json, examples/start/package.json, examples/v9/config/package-lock.json, examples/v9/config/package.json, examples/v9/start-and-yarn-workspaces/workspace-1/package.json, examples/v9/start-and-yarn-workspaces/workspace-2/package.json, examples/v9/start-and-yarn-workspaces/yarn.lock, examples/v9/start/package-lock.json, examples/v9/start/package.json
This PR mitigates a critical vulnerability reported by dependabot and `yarn audit` for:
- [examples/start-and-yarn-workspaces/yarn.lock](https://github.com/cypress-io/github-action/blob/master/examples/start-and-yarn-workspaces/yarn.lock)
- [examples/v9/start-and-yarn-workspaces/yarn.lock](https://github.com/cypress-io/github-action/blob/master/examples/v9/start-and-yarn-workspaces/yarn.lock)
It concerns [minimist](https://www.npmjs.com/package/minimist) < 1.2.6 derived from [serve](https://www.npmjs.com/package/serve).
In this PR [serve](https://www.npmjs.com/package/serve) is updated to the current version 14.2.0 in all examples which use this npm package.
For consistency `serve` is also moved from "dependencies" to "devDependencies" in `package.json` files.
The following examples are …
=> Update serve to 14.2.0

package-lock.json, package.json
This PR removes the unused npm package [stop-build](https://www.npmjs.com/package/stop-build) which invokes two critical vulnerabilities in `npm audit` through `minimist@0.0.10` and `lodash@3.10.1`. The package was last updated 6 years ago.
=> Remove stop-build

.github/workflows/example-component-test.yml
This PR implements the suggestions from issue https://github.com/cypress-io/github-action/issues/770 "Harmonize Component test workflow" regarding the workflow [.github/workflows/example-component-test.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-component-test.yml).
1. It changes the name to `example-component-test` so that it appears sorted in the left-hand side of [GH Action view](https://github.com/cypress-io/github-action/actions) together with the E2E tests.
2. It changes the trigger to be identical to E2E example triggers. This avoids the workflow running on `push` to branches other than `master`.
3. It changes the runner to the explicit Ubuntu version `ubuntu-22.04`. This makes it clearer exactly which version is being used and it aligns …
=> Harmonize Component test workflow to E2E example workflows

.github/workflows/check-dist.yml
This PR addresses issue https://github.com/cypress-io/github-action/issues/706 "Add build & diff "/dist" folder workflow".
It adds a new workflow [.github/workflows/check-dist.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/check-dist.yml) which checks for consistency between source files and the generated contents of the [master/dist](https://github.com/cypress-io/github-action/tree/master/dist) directory.
If the source files and [master/dist](https://github.com/cypress-io/github-action/tree/master/dist) are consistent then the workflow succeeds.
If the source files and [master/dist](https://github.com/cypress-io/github-action/tree/master/dist) are **not** consistent then the workflow fails.
Test on Ubuntu 22.04.
Make a change to …
=> Add check for dist/ directory consistent with source files

.github/workflows/example-debug.yml
This PR renames the job in [.github/workflows/example-debug.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-debug.yml) from `nightly` to `debug-logs`, which provides a more accurate description of the purpose of the job.
([.github/workflows/example-cron.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-cron.yml) which does indeed run every night at 04:00 UTC uses the job name `nightly`. This is a fitting job name for this workflow, but not for the debug one.)
=> Change example-debug job name from nightly to debug-logs

.github/workflows/main.yml
This PR partially addresses issue https://github.com/cypress-io/github-action/issues/715 "Issues with cycjimmy/semantic-release-action in main workflow (Rev 2)" where [.github/workflows/main.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/main.yml) may run in a fork, attempting to carry out a release, which then fails with an error message due to lack of write permissions to the parent repository.
The PR restricts the `release` job of [.github/workflows/main.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/main.yml) so that it only runs on the repository [cypress-io/github-action](https://github.com/cypress-io/github-action) and not on a fork of this repository.
In a fork, ensure that workflows are enabled (Settings > Actions > …
=> Prevent release attempt from fork

examples/basic-pnpm/package.json, examples/v9/basic-pnpm/package.json
This PR corrects a minor inconsistency in:
- [examples/basic-pnpm/package.json](https://github.com/cypress-io/github-action/blob/master/examples/basic-pnpm/package.json) and
- [examples/v9/basic-pnpm/package.json](https://github.com/cypress-io/github-action/blob/master/examples/v9/basic-pnpm/package.json)
It adds `pnpm` to the package name `example-basic` and to the package description to distinguish it from the other `example-basic` based on `npm`.
=> Correct example-basic for pnpm package.json to add pnpm to name

dist/index.js, index.js
This PR resolves a log formatting issue when the [start:](https://github.com/cypress-io/github-action/blob/master/README.md#start-server) (server) parameter is used.
If a step:
```yml
- name: Cypress run
uses: cypress-io/github-action@v5
with:
start: npm start
```
is defined in a GitHub workflow, the log would show:
```text
start server "npm start command "npm start"
```
with the text of the start command incorrectly rendered twice.
The fix is credited to @fbiville who originally submitted PR https://github.com/cypress-io/github-action/pull/481 in Jan, 2022.
With this PR the log output for the above example shows as:
```text
start server command "npm start"
```
View the logs of https://github.com/cypress-io/github-action/actions/workflows/example-webpack.yml
Select the `wait` job then …
=> Correct log format for start: parameter

.github/workflows/example-wait-on.yml
This PR resolves issue https://github.com/cypress-io/github-action/issues/802 "example-wait-on fails on GitHub waiting for localhost".
Due to the migration of [GitHub runners](https://github.com/actions/runner-images) to use Node.js 18, name resolution is behaving differently when accessing `localhost`. This affects webservers used for testing which only listen on IPv4 or IPv6, but not on both network stacks.
In [example-wait-on](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-wait-on.yml) it changes the network name / address
- to wait for [react-scripts][react] server using the IPv4 address `127.0.0.1`
and 
- changes the startup of [vite server][vite] to `npx vite --host` (see Vite Server Options …
=> wait-on example changes for react-scripts and vite server under Node.js 18

.github/workflows/example-node-versions.yml
This PR implements the suggestion from https://github.com/cypress-io/github-action/issues/807 "Add Node.js 19 to tested versions" to modify [.github/workflows/example-node-versions.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-node-versions.yml) so that it additionally tests with Node.js 19. It also sets `fail-fast` to false so that each Node.js version test is carried out even if the test of another Node.js version should fail.
According to the [Node.js Release Schedule](https://github.com/nodejs/release#release-schedule) Node.js 19.x is the Current version. It was released on Oct 18, 2022, enters maintenance on Apr 1, 2023 and goes into end-of-life status on Jun 1, 2023.
This is to be followed by the next Node.js LTS version 20.x, planned for …
=> Add test for Node.js 19

README.md
This PR updates the browser examples in the [Browser section](https://github.com/cypress-io/github-action/blob/master/README.md#browser) of the README file.
The examples are harmonized in terms of layout, job-naming, etc.
- Electron is mentioned as the default browser
- The Firefox example is no longer shown as running in a container, since this is not necessary. (Resolves issue https://github.com/cypress-io/github-action/issues/735.)
=> docs: harmonize browser examples in README

README.md
This PR updates the README example [Robust custom build id](https://github.com/cypress-io/github-action#robust-custom-build-id) which contains code
`run: echo "::set-output name=value::sha-$GITHUB_SHA-time-$(date +"%s")"`
that GitHub has deprecated. [GitHub Actions: Deprecating save-state and set-output commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) states "We are monitoring telemetry for the usage of these commands and plan to fully disable them on 31st May 2023".
I already changed the workflow [example-custom-ci-build-id](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-custom-ci-build-id.yml) through PR https://github.com/cypress-io/github-action/pull/675 in December 2022 and at the …
=> docs: remove deprecated set-output from example

README.md
This PR adds a (legacy) note to links which reference external examples in the [README](https://github.com/cypress-io/github-action/blob/master/README.md) file and which only demonstrate a [Legacy Configuration](https://docs.cypress.io/guides/references/legacy-configuration) as used by Cypress 9 and below.
| README Section                                                                                 | Example                                                                                        | Cypress version   |
| ---------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------- | ----------------- |
| …
=> docs: add legacy notation to external examples using only Cypress 9 and below

.github/workflows/add-issue-to-triage-board.yml, .github/workflows/triage_closed_issue_comment.yml
This PR disables the following workflows from running in a fork if they are triggered there:
- [add-issue-to-triage-board.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/add-issue-to-triage-board.yml)
- [triage_closed_issue_comment.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/triage_closed_issue_comment.yml)
The workflows are not intended for use in a fork. The activities there are not of interest for the triage board and if the workflows are triggered they fail due to lack of access to necessary secrets.
The following conditional is added so that the corresponding workflow is skipped if it is triggered in a fork:
```yml
if: github.repository == 'cypress-io/github-action'
```
See [Example: Only run job for specific …
=> ci: skip triage workflows in fork

package-lock.json, package.json
This PR removes the unused dependency [execa](https://www.npmjs.com/package/execa) from [package.json](https://github.com/cypress-io/github-action/blob/master/package.json).
Renovate's PR https://github.com/cypress-io/github-action/pull/790 "fix(deps): update dependency execa to v7" then becomes obsolete.
Since [execa](https://www.npmjs.com/package/execa) is unused, removing it has no impact on the action itself. `npm run build` produces the same output as previously.
=> deps: remove unused execa

.github/workflows/example-basic.yml, README.md
This PR implements the suggestion from issue https://github.com/cypress-io/github-action/issues/784 "Component tests README section incomplete" reflecting the GA status of component testing since [Cypress 11.0.0](https://docs.cypress.io/guides/references/changelog#11-0-0). The changes are applied to the examples in the [README.md](https://github.com/cypress-io/github-action/blob/master/README.md).
1. A new example for Component Testing, separate from E2E, is added as "[Component](#component-testing) testing"
2. The Basic example is renamed "[End-to-End](#end-to-end-testing) testing" to differentiate it from Component Testing
3. The original combined E2E and Component test is relabeled as "Combine [Component and E2E](#component-and-e2e-testing) testing"
4. A paragraph is added explaining …
=> docs: improve component testing documentation

docs/MAINTENANCE.md, scripts/check-package-manager-npm.sh, scripts/check-package-managers-other.sh, scripts/update-cypress-latest-npm.sh, scripts/update-cypress-latest-other.sh, scripts/update-cypress-latest.sh
This PR improves the error handling for the update scripts called by
```bash
npm run update:cypress
```
It was previously possible for them to fail silently, particularly if `pnpm` or `yarn` were not installed.  This situation can occur if `nvm` is used to manage `Node.js` versions, since global installations of `pnpm` and `yarn` are tied to a specific `Node.js` version and not carried over, for instance if `Node.js` is updated to the latest LTS version.
The scripts now check that the following commands are available:
- npm
- pnpm
- yarn
and advise installation if they are missing.
On Ubuntu and Windows 11 Pro.
1. With no `npm` available (for instance by uninstalling `nvm`). `npm -v` should produce "command not found", execute
```bash
./scripts/update-cypress-latest.sh
```
and confirm …
=> build: improve update script error handling

examples/react-scripts/package-lock.json, examples/v9/react-scripts/package-lock.json, examples/v9/webpack/package-lock.json, examples/v9/webpack/package.json, examples/webpack/package-lock.json, examples/webpack/package.json
This PR updates webpack to 5.76.1 prompted by a dependabot warning.
The following examples have webpack updated directly:
- [examples/webpack](https://github.com/cypress-io/github-action/tree/master/examples/webpack) and
- [examples/v9/webpack](https://github.com/cypress-io/github-action/tree/master/examples/v9/webpack)
The following examples are fixed using `npm audit -fix`, since webpack is installed as a dependency of `react-scripts@5.0.1` for which there is not yet any newer version available:
- [examples/react-scripts](https://github.com/cypress-io/github-action/tree/master/examples/react-scripts) and
- [examples/v9/react-scripts](https://github.com/cypress-io/github-action/tree/master/examples/v9/react-scripts)
=> chore(deps): update webpack example version

.github/workflows/example-wait-on.yml, README.md, examples/react-scripts/package-lock.json, examples/react-scripts/package.json, examples/v9/react-scripts/package-lock.json, examples/v9/react-scripts/package.json
This PR installs the npm package [wait-on](https://www.npmjs.com/package/wait-on) into
- [examples/react-scripts/package.json](https://github.com/cypress-io/github-action/blob/master/examples/react-scripts/package.json) and
- [examples/v9/react-scripts/package.json](https://github.com/cypress-io/github-action/blob/master/examples/v9/react-scripts/package.json)
so that the corresponding `package-lock.json` files are locked to a fixed version of [wait-on](https://www.npmjs.com/package/wait-on) .
Without this step, the workflow [.github/workflows/example-wait-on.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-wait-on.yml) causes the latest version of `wait-on` to be installed. See logs from https://github.com/cypress-io/github-action/actions/workflows/ex …
=> test: lock version of wait-on for react-scripts

dist/index.js, package-lock.json, package.json
This PR replaces failing Renovate PRs:
- https://github.com/cypress-io/github-action/pull/841
- https://github.com/cypress-io/github-action/pull/842
[MEND Renovate](https://github.com/apps/renovate) is unable to handle updating these dependencies successfully, since they cause changes to the action which then needs recompiling. Renovate does not have the capacity to recompile.
- Installation of [supports-color@9.3.1](https://github.com/chalk/supports-color/releases/tag/v9.3.1) and action recompile
- Update to [markdown-link-check@3.11.0](https://github.com/tcort/markdown-link-check/blob/HEAD/CHANGELOG.md#Version-3110)
- Update to [@actions/io@1.1.3](https://github.com/actions/toolkit/blob/HEAD/packages/io/RELEASES.md#%E2%80%8B113) and action recompile
The update of …
=> fix(deps): update dependencies @actions/io and markdown-link-check

README.md
This PR adds documentation to the [README](https://github.com/cypress-io/github-action/blob/master/README.md) file to describe using the package manager [pnpm](https://pnpm.io/) referring also to the existing example materials:
- [example-basic-pnpm.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic-pnpm.yml)
- [examples/v9/basic-pnpm](https://github.com/cypress-io/github-action/tree/master/examples/v9/basic-pnpm)
This documentation step was omitted when support for `pnpm` was added through PR https://github.com/cypress-io/github-action/pull/586 in [v4.2.0](https://github.com/cypress-io/github-action/releases/tag/v4.2.0).
- A new example section …
=> docs: add pnpm example

README.md
This PR removes the second section [Docker image](https://github.com/cypress-io/github-action/blob/master/README.md#docker-image-1) for the following reasons:
- It does not explain how to use the GitHub action. On the contrary it explains how **not** to use it.
- It is confusing, because there is another section higher up in the [README](https://github.com/cypress-io/github-action/blob/master/README.md) file with exactly the same header [Docker image](https://github.com/cypress-io/github-action/blob/master/README.md#docker-image) which **does** explain how to use the GH Action with a Docker container.
- With the addition of documentation for `pnpm` in PR https://github.com/cypress-io/github-action/pull/844 it would need to be explained for completeness how this could also be a solution …
=> docs: remove second "Docker image" non-example section

README.md
This PR reworks the [README: Outputs](https://github.com/cypress-io/github-action/blob/master/README.md#outputs) section to state that the `dashboardUrl` is only set if the run was recorded using the action parameter `record: true`. It warns that this is not the case if a [Custom test command](#custom-test-command) with the `command` parameter is used, since this overrides the `record` parameter.
The custom command operates independently. See
https://github.com/cypress-io/github-action/blob/96268482322bc63c76561c602a84be842c527dbc/index.js#L665-L668
The regular call, which which would use the `record` parameter, is not invoked in this case
https://github.com/cypress-io/github-action/blob/96268482322bc63c76561c602a84be842c527dbc/index.js#L501-L505
- This partially resolves issue …
=> docs: update dashboardurl section - not set if custom command used

.husky/pre-commit, package-lock.json, package.json
This PR resolves https://github.com/cypress-io/github-action/issues/743 "Inactive git pre-commit Husky hook" by reactivating the [husky](https://www.npmjs.com/package/husky) hook.
It should also resolve an issue with Renovate. If dependencies which are used in the action are bumped by Renovate and they need to be compiled, Renovate does not know about this step and a PR it produces may be incomplete and fail the CI test [.github/workflows/check-dist.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/check-dist.yml).
- [husky](https://www.npmjs.com/package/husky) is updated to the latest version [husky v8.0.3](https://github.com/typicode/husky/releases/tag/v8.0.3).
- The inactive hook `"pre-commit": "npm run format && npm run build && git add index.js dist"` is …
=> ci: update to husky 8.0.3 and reactivate hook

scripts/update-cypress-latest-other.sh
This PR updates [scripts/update-cypress-latest-other.sh](https://github.com/cypress-io/github-action/blob/master/scripts/update-cypress-latest-other.sh) so that [examples/yarn-modern](https://github.com/cypress-io/github-action/tree/master/examples/yarn-modern) uses the latest version of `yarn` from the package manager Yarn Modern after running `npm run update:cypress`.
GitHub only includes Yarn Classic in its standard runners, so there is otherwise no mechanism to update the version of Yarn Modern.
Yarn Modern is updated only for [examples/yarn-modern](https://github.com/cypress-io/github-action/tree/master/examples/yarn-modern).
[examples/v9/yarn-modern](https://github.com/cypress-io/github-action/tree/master/examples/v9/yarn-modern) for legacy Cypress is untouched by this change. …
=> build: automate update of examples/yarn-modern to yarn latest

dist/index.js, index.js
This PR catches the error condition of a missing package manager lock file and displays a user-friendly error message.
The action requires a lock file from `npm`, `pnpm` or `yarn` in order to install dependencies and store the cache.
---
BEFORE
The action fails showing an error message similar to the following:
```text
@cypress/github-action trying to restore cached NPM modules
node:internal/fs/utils:345
throw err;
^
Error: ENOENT: no such file or directory, open '/home/runner/work/github-action/github-action/examples/yarn-classic/package-lock.json'
```
This error message only mentions `package-lock.json` (npm). It does not mention lock file names from `pnpm` or `yarn`, which are also supported.
---
AFTER
An error message is shown in the action logs summary and action logs details similar …
=> feat: user-friendly error if lock file missing

.github/workflows/example-basic-pnpm.yml, README.md
This PR remediates a breaking change caused by the release of [pnpm 8.0.0](https://github.com/pnpm/pnpm/releases/tag/v8.0.0) on March 28, 2023.
`pnpm install --frozen-lockfile` does not accept `pnpm-lock.yaml` with `lockfileVersion: 5.4` generated by [pnpm v7.30.5](https://github.com/pnpm/pnpm/releases/tag/v7.30.5).
[pnpm 8.0.0](https://github.com/pnpm/pnpm/releases/tag/v8.0.0) is a breaking change. Apart from the compatibility issue with `lockfileVersion: 5.4` it also removes support for Node.js 14.
[.github/workflows/example-basic-pnpm.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic-pnpm.yml) uses [pnpm/action-setup](https://github.com/pnpm/action-setup)@v2  `with: version: latest`
Bind …
=> fix(deps): use pnpm 7 not pnpm 8 (new latest)

README.md
This PR re-works the [README section: Explicit version](https://github.com/cypress-io/github-action/blob/master/README.md#explicit-version).
The text is simplified, corrected and the heading is renamed using the more neutral "Action version" instead of "Explicit version".
- `v5` is clarified as being the latest version
- Selecting `cypress-io/github-action@v5` is using a branch name, not a tag name. (There is no tag `v5`.)
- In addition to referring to GitHub's [tags](https://github.com/cypress-io/github-action/tags) list, the [releases](https://github.com/cypress-io/github-action/releases) list and [Changelog](https://github.com/cypress-io/github-action/blob/master/README.md#changelog) are also linked
=> docs: improve "explicit version" section in readme

README.md
This PR updates the [README: Specs](https://github.com/cypress-io/github-action/blob/master/README.md#specs) example to use non-legacy default directory and filenames for test specs, i.e. `cypress/e2e/*.cy.js` instead of `cypress/integration/*.js`.
=> docs: update specs example with non-legacy directory/filename

CONTRIBUTING.md, README.md
This PR renames the file [DEVELOPMENT.md](https://github.com/cypress-io/github-action/blob/master/DEVELOPMENT.md) to use the standard filename `CONTRIBUTING.md`.
This was requested by @emilyrohrbough in https://github.com/cypress-io/github-action/pull/853#discussion_r1157814238.
It also updates the [README.md](https://github.com/cypress-io/github-action/blob/master/README.md) file accordingly.
According to GitHub Docs [Setting guidelines for repository contributors](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) the `CONTRIBUTING.md` file can be in the repository's root, `docs` or `.github` directory. Given that the original [DEVELOPMENT.md](https://github.com/cypress-io/github-action/blob/master/DEVE …
=> docs: move DEVELOPMENT.md to CONTRIBUTING.md

README.md
This PR updates the [README: parallel](https://github.com/cypress-io/github-action/blob/master/README.md#parallel) example section.
It adds a paragraph to recommend using a Docker container when testing against a non-Electron browser.
This relates to issues:
- https://github.com/cypress-io/cypress/issues/25040
- https://github.com/cypress-io/github-action/issues/602
- https://github.com/cypress-io/github-action/issues/865
=> docs: recommend container for parallel browser testing

.github/workflows/example-recording.yml
This PR adds a 2-container matrix to the `parallel-v9` and `parallel` jobs of [.github/workflows/example-recording.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-recording.yml).
```yml
strategy:
fail-fast: false
matrix:
containers: [1, 2]
```
To gain benefit from the `record` & `parallel` parameters there must be more than one container running, otherwise no load-balancing can take place.
```yml
with:
record: true
parallel: true
```
This PR therefore improves the example workflow by making it better mirror practical usage of the `record` & `parallel` parameters.
=> test: add matrix to parallel recording

README.md
This PR capitalizes the table of contents (ToC) in https://github.com/cypress-io/github-action/blob/master/README.md consistently.
The position of the entries in the ToC and body are reordered to match each other. Recording topics are grouped together. This concerns:
- [Specify auto cancel after failures](https://github.com/cypress-io/github-action/blob/master/README.md#specify-auto-cancel-after-failures)
- [Quiet output](https://github.com/cypress-io/github-action/blob/master/README.md#quiet-flag)
=> docs: fix Table of Contents ordering and capitalization

README.md
This PR modifies the [README](https://github.com/cypress-io/github-action/blob/master/README.md) file. It ...
- moves the prerequisite information about installing Cypress up and out of the section about End-to-End Testing, since it is a general prerequisite and not specific to the End-to-End Testing example.
- removes "NPM" from the reference to [NPM module API](https://docs.cypress.io/guides/guides/module-api) to match the Cypress documentation heading "Module API" in https://docs.cypress.io/guides/guides/module-api
- links references to `cypress npm module` to its entry in the npm registry https://www.npmjs.com/package/cypress
- links the reference `package.json` to the npm documentation [Creating a package.json file](https://docs.npmjs.com/creating-a-package-json-file)
Note: the name …
=> docs: harmonize references to Cypress npm module

.github/workflows/example-install-only.yml, .github/workflows/example-quiet.yml, .github/workflows/example-wait-on.yml, CONTRIBUTING.md, README.md
This PR modifies the:
- [README](https://github.com/cypress-io/github-action/blob/master/README.md) file
- [CONTRIBUTING](https://github.com/cypress-io/github-action/blob/master/CONTRIBUTING.md) file
- `*.yml` workflows in the [.github/workflows](https://github.com/cypress-io/github-action/tree/master/.github/workflows) directory
causing:
- references to `NPM` to be changed to lowercase `npm` in conformance with its documentation under [About npm](https://docs.npmjs.com/about-npm).
=> misc: use lower case for references to npm package manager

examples/custom-command/package-lock.json, examples/custom-command/package.json
This PR updates [lodash](https://www.npmjs.com/package/lodash) to [v4.17.21](https://github.com/lodash/lodash/wiki/Changelog#v41721) in [examples/custom-command](https://github.com/cypress-io/github-action/tree/master/examples/custom-command).
The current configuration reports a vulnerability. To reproduce:
```text
$ cd examples/config
$ npm ci
added 173 packages, and audited 174 packages in 7s
35 packages are looking for funding
run `npm fund` for details
1 high severity vulnerability
To address all issues, run:
npm audit fix --force
```
After applying the changes from this PR:
Execute:
```bash
npm ci
```
and confirm that 0 vulnerabilities are reported. Then execute
```bash
npm run custom-test
```
and confirm that the Cypress test completes successfully.
Confirm that …
=> chore(deps): update examples/custom-command dependencies

examples/config/package-lock.json, examples/config/package.json
This PR updates [start-server-and-test](https://www.npmjs.com/package/start-server-and-test) to [v2.0.0](https://github.com/bahmutov/start-server-and-test/releases/tag/v2.0.0) in [examples/config](https://github.com/cypress-io/github-action/tree/master/examples/config).
The current configuration reports deprecations and vulnerabilities. To reproduce:
```text
$ cd examples/config
$ npm ci
npm WARN deprecated @hapi/pinpoint@2.0.0: Moved to 'npm install @sideway/pinpoint'
npm WARN deprecated @hapi/formula@2.0.0: Moved to 'npm install @sideway/formula'
npm WARN deprecated debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. …
```
=> chore(deps): update examples/config dependencies

README.md
Some entries are missing in the table-of-contents. This PR adds them in.
=> docs: add missing entries to table-of-contents

.github/workflows/example-node-versions.yml, README.md
Node.js `14` moved into end-of-life status on April 30, 2023 and is therefore no longer officially supported. The versions which are currently supported by Node.js according to their [Release schedule](https://github.com/nodejs/release#release-schedule) are now `16`, `18`, `19` and  `20`.
This PR takes account of this Node.js status change and it removes Node.js `14` ...
- from the list of versions which [.github/workflows/example-node-versions.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-node-versions.yml) tests
- from the list [Node.js Support](https://github.com/cypress-io/github-action/blob/master/README.md#nodejs-support) of supported versions for the action
All examples in the [README](https://github.com/cypress-io/github-action/blob/master/R …
=> fix(deps): update node.js versions in examples

.github/workflows/example-basic-pnpm.yml
This PR updates the version of pnpm used in [.github/workflows/example-basic-pnpm.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic-pnpm.yml) from `7` to `8` (latest version) for the Cypress v10 and higher jobs only. Legacy Cypress v9 jobs remain using the older pnpm `7`.
[pnpm 8.0.0](https://github.com/pnpm/pnpm/releases/tag/v8.0.0) removed support for Node.js `14` and adopted [Lockfile v6](https://github.com/pnpm/pnpm/pull/5810).
The prerequisites for using [pnpm 8.0.0](https://github.com/pnpm/pnpm/releases/tag/v8.0.0) are already fulfilled:
- Node.js `14.x` itself moved to [End-of-Life](https://github.com/nodejs/release#release-schedule) on April 30, 2023
- The [examples/basic-pnpm/pnpm-lock.yaml](https://github.com/cypress-io/github-action/blo …
=> test(deps): update pnpm to 8

README.md
This PR adds [pnpm](https://pnpm.io/) and [Yarn](https://classic.yarnpkg.com/) to the introduction in the [README](https://github.com/cypress-io/github-action/blob/master/README.md) file.
It respects the product naming (lower case / mixed case) as defined by the products themselves:
- [npm](https://docs.npmjs.com/)
- [pnpm](https://pnpm.io/)
- [Yarn](https://classic.yarnpkg.com/)
The PR replaces the previous https://github.com/cypress-io/github-action/pull/880 which I closed after realizing that there were some other documentation prerequisites necessary for consistency which have now been dealt with by:
- #881
- #885
=> docs: add pnpm and Yarn to intro

.github/workflows/main.yml
This PR follows on from https://github.com/cypress-io/github-action/issues/722#issuecomment-1533640162 which proposes to remove `extra_plugins` from the workflow. These plugins were inactive since the configuration was incomplete.
The following changes are made to [.github/workflows/main.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/main.yml) using the GitHub JavaScript [action-for-semantic-release](https://github.com/marketplace/actions/action-for-semantic-release) called by `cycjimmy/semantic-release-action@v3`:
1. Remove the `extra_plugins:` parameter containing
```yaml
extra_plugins: |
@semantic-release/git
@semantic-release/changelog
```
2. Change the `branch` parameter to `branches`. The `branch` parameter is only officially supported for …
=> ci: remove unused release plugins

dist/index.js, index.js
This PR modifies the action source file [index.js](https://github.com/cypress-io/github-action/blob/master/index.js) for consistency with
- the `npm` documentation [About npm](https://docs.npmjs.com/about-npm) which uses lower case `npm` and with
- the Cypress documentation [Module API](https://docs.cypress.io/guides/guides/module-api) which does not include `NPM` in its name
- Text and comments now refer to `npm` consistently in lower case.
- `NPM` is removed from the reference to the Cypress [Module API](https://docs.cypress.io/guides/guides/module-api)
=> fix: harmonize npm name usage in logs

README.md
This PR harmonizes references to workflows in the [README.md](https://github.com/cypress-io/github-action/blob/master/README.md) document so they consistently appear **without** a path and **with** a file extension `.yml`. This is the way that most of the references have been written.
For example the reference to [.github/workflows/example-custom-command.yml](.github/workflows/example-custom-command.yml) is changed to display as [example-custom-command.yml](.github/workflows/example-custom-command.yml).
If an example workflow can be linked to by a status badge, then the redundant text link is removed. The use of badges is also explained.
=> docs: harmonize workflow readme references

README.md
This PR closes #360 and modifies the [README > Start server](https://github.com/cypress-io/github-action#start-server) section.
When a server is started in a job, it continues running until the job completes. The shutdown of a server is not linked to the end of testing as such. The current text was misleading in this respect.
An example can be seen by viewing [actions/workflows/example-start.yml](https://github.com/cypress-io/github-action/actions/workflows/example-start.yml?query=branch%3Amaster), for example job [8915428534](https://github.com/cypress-io/github-action/actions/runs/4981323712/jobs/8915428534)
=> docs: clarify server shutdown

.github/workflows/example-recording.yml, README.md, action.yml, dist/index.js, index.js
Closes #909.
This PR adds a GitHub step output ~~`cloudRunUrl`~~ `resultsUrl` for recording, providing a name which is not tied to the branding name of Cypress Dashboard or Cypress Cloud. This is a replacement for `dashboardUrl`.
The GitHub step output `dashboardUrl`, stemming from the previous Cypress Dashboard branding, continues to function and is documented as deprecated.
Documentation and examples are updated accordingly.
[examples/v9](https://github.com/cypress-io/github-action/tree/master/examples/v9) are left using `dashboardUrl`
=> feat: replace dashboardUrl by resultsUrl

examples/v9/start-and-yarn-workspaces/yarn.lock
This PR resolves a critical vulnerability in [examples/v9/start-and-yarn-workspaces](https://github.com/cypress-io/github-action/tree/master/examples/v9/start-and-yarn-workspaces) using `minimist` reported by Dependabot.
`yarn.lock` is deleted and regenerated.
=> chore(deps): refresh dependencies in examples/v9/start-and-yarn-workspaces

README.md
Updating the examples to more clearly not always expect video artifacts since videos will not be captured by default in version 13.0.
THIS PR CAN BE MERGED ANYTIME. It's not dependent on 13.0 changes being made ahead of time.
=> Update GitHub Action in anticipation of video default changes

README.md
This PR updates the [README > Changelog](https://github.com/cypress-io/github-action/blob/master/README.md#changelog) to reflect the updated text in [GitHub's blog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
They originally planned to disable `save-state` and `set-output` commands by May 31, 2023.
Now they write:
> Our telemetry shows significant usage of these commands. Given the number of impacted customers we are postponing the removal.
with no new plan date published.
=> docs: github postpones set-output removal

.github/workflows/example-node-versions.yml, README.md
Node.js `19` moved into end-of-life status on June 1, 2023 and is therefore no longer officially supported. The versions which are currently supported by Node.js according to their [Release schedule](https://github.com/nodejs/release#release-schedule) are now `16`, `18`, and  `20`.
This PR takes account of this Node.js status change. It removes Node.js `19` ...
- from the list of versions which [.github/workflows/example-node-versions.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-node-versions.yml) tests
- from the examples in the [README](https://github.com/cypress-io/github-action/blob/master/README.md) file
The list [Node.js Support](https://github.com/cypress-io/github-action/blob/master/README.md#nodejs-support) of supported versions for the …
=> fix(deps): remove node.js 19

.github/workflows/example-chrome.yml, examples/browser/cypress.config.js
This PR makes changes affecting Chrome and Edge browser testing for Cypress 12.x based tests: It ...
- disables video generation in [examples/browser](https://github.com/cypress-io/github-action/tree/master/examples/browser)
- disables video artifact upload in [.github/workflows/example-chrome.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-chrome.yml) for v10+ examples.
*([examples/v9](https://github.com/cypress-io/github-action/tree/master/examples/v9) are not changed)*
Harmonization, simplification and preparation for future Cypress release:
1. Groundwork to be able to consolidate and harmonize browser testing:
- Cypress cannot generate videos with Firefox (see open issue https://github.com/cypress-io/cypress/issues/18415). PR aligns with …
=> test: disable video collection and artifact upload for v12 examples

README.md
This PR documents the addition of `resultsUrl` and the deprecation of `dashboardUrl` from PR https://github.com/cypress-io/github-action/pull/916 in release [v5.8.0](https://github.com/cypress-io/github-action/releases/tag/v5.8.0) of the action into the [README > Changelog](https://github.com/cypress-io/github-action/blob/master/README.md#changelog) section.
=> docs: add resultsurl to changelog

README.md
This PR removes the link to the outdated [cypress-io/cypress-workshop-ci](https://github.com/cypress-io/cypress-workshop-ci) from [github-action > README > More information](https://github.com/cypress-io/github-action/blob/master/README.md#more-information). The materials used by the workflow are outdated and archived. 
See also 
- https://github.com/cypress-io/cypress-documentation/pull/5291 from @AtofStryker
- https://github.com/cypress-io/cypress-workshop-ci/issues/9
=> docs: remove outdated workshop-ci reference

examples/wait-on/package-lock.json, examples/wait-on/package.json
This PR resolves a deprecation warning in [examples/wait-on](https://github.com/cypress-io/github-action/tree/master/examples/wait-on) by updating [debug](https://www.npmjs.com/package/debug) to `debug@4.3.4`.
Executing `npm ci` produces the following warning:
> npm WARN deprecated debug@4.2.0: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
The npm module [debug](https://www.npmjs.com/package/debug) is updated to `debug@latest` (`4.3.4`).
=> chore(deps): update debug in examples/wait-on

dist/index.js, index.js
This PR resolves an issue calling commands `cypress cache list` and `cypress cache verify` if the project is using [Yarn Plug'n'Play](https://yarnpkg.com/features/pnp) (introduced through PR https://github.com/cypress-io/github-action/pull/599 from @PilotConway). In this case the commands were not finding the installed version of Cypress.
The following commands, which are called internally by the action, are replaced if the action is working from a `yarn.lock` file. This is the case for [Yarn Classic](https://classic.yarnpkg.com/) and [Yarn Modern](https://yarnpkg.com/) projects. Although the issue only affects [Yarn Modern](https://yarnpkg.com/) using [Yarn Plug'n'Play](https://yarnpkg.com/features/pnp) configuration, the change is activated for **all** types of Yarn projects.
The …
=> fix: use yarn instead of npx with yarn.lock

dist/index.js, index.js
This PR reverts https://github.com/cypress-io/github-action/pull/914 which caused a breaking change due to replacing `npx cypress cache list` by `yarn cypress cache list` for Yarn projects.
If the working-directory contains a script definition with the name `cypress` then yarn uses this script definition instead of executing `cypress` from `node_modules`. In the case of issue https://github.com/cypress-io/github-action/issues/941 this caused the workflow to hang indefinitely.
PR https://github.com/cypress-io/github-action/pull/914 was intended to resolve an issue with Yarn Modern Plug'n'Play, however the PR is applied to all types of Yarn projects (Classic & Modern).
The changes defined in https://github.com/cypress-io/github-action/pull/914 should be rescheduled for a future date when …
=> revert: "fix: use yarn instead of npx with yarn.lock (#914)"

.github/workflows/example-node-versions.yml
This PR removes the following comment from [.github/workflows/example-node-versions.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-node-versions.yml):
"# Hmm, should we rebuild the "dist" before using the action?"
It's unclear whether this was supposed to be an exercise for the reader or a to-do task for the author of the comment!
In fact it is not necessary to rebuild the [`dist/`](https://github.com/cypress-io/github-action/tree/master/dist) folder because:
1. the workflow [.github/workflows/check-dist.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/check-dist.yml) independently rebuilds and checks the consistency of the [`dist/`](https://github.com/cypress-io/github-action/tree/master/dist) folder
2. in practice the …
=> test: remove comment about rebuilding dist in node test

README.md
This PR adds an explanation to the [README > Node.js Support](https://github.com/cypress-io/github-action/blob/master/README.md#nodejs-support) section regarding which version of Node.js is used by `github-action`.
- The [Cypress Module API](https://docs.cypress.io/guides/guides/module-api) call uses the version of Node.js defined in [action.yml](https://github.com/cypress-io/github-action/blob/38817732586351d080f5ea0a828482f78c4cd370/action.yml#L99-L101). For `github-action@v5` this is currently Node.js `16.16.0`. GitHub currently only offers the `node16` environment for the [runs.using](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions) option of GitHub JavaScript Actions.
- Other `github-action` options which execute …
=> docs: explain node.js usage

examples/install-command/package.json, examples/install-command/yarn.lock, examples/install-only/package-lock.json, examples/install-only/package.json, examples/v9/install-command/package.json, examples/v9/install-command/yarn.lock, examples/v9/install-only/package-lock.json, examples/v9/install-only/package.json, examples/v9/wait-on/package-lock.json, examples/v9/wait-on/package.json
This PR updates the remaining examples to use `debug@4.3.4` (the latest version, published on Mar 17, 2022) instead of the deprecated `debug@4.2.0`.
See [debug](https://www.npmjs.com/package/debug).
It follows on from https://github.com/cypress-io/github-action/pull/939.
`debug@4.2.0` which was published on May 29, 2020 is deprecated.
```text
$ npm view debug@4.2.0 deprecated
Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
=> chore(deps): update debug to 4.3.4

README.md
This PR corrects the name of the example `yarn-modern` job in the [README > Yarn Modern](https://github.com/cypress-io/github-action/blob/master/README.md#yarn-modern) section.
This README section displays an `example-yarn-modern` workflow with the confusingly misnamed job name `yarn-classic`.
The job name is changed to `yarn-modern` so that it aligns with the actual [example-yarn-modern.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-yarn-modern.yml) workflow example containing the two jobs:
- `yarn-modern-v9`
- `yarn-modern`
=> docs: correct yarn-modern job name in readme

README.md
This PR provides clarification about the Yarn Modern `nodeLinker` configuration option of Yarn Modern through [`.yarnrc.yml`](https://yarnpkg.com/configuration/yarnrc#nodeLinker).
| `nodeLinker` value | Comments                                                                |
| ------------------ | ----------------------------------------------------------------------- |
| undefined          | defaults to `pnp`. Default for new Yarn Modern projects.                |
| `pnp`              | Yarn Modern Plug'n'Play                                                 |
| `node-modules`     | `npm` compatible mode. Projects upgraded from Yarn Classic use this.    |
| `pnpm`             | Cannot be used with `github-action`. Does not work with `npx` commands. |
=> docs: add nodelinker information to yarn modern readme section

README.md
This PR links the README section
[Record test results on Cypress Cloud](https://github.com/cypress-io/github-action/blob/master/README.md#record-test-results-on-cypress-cloud)
to the [Cypress Cloud documentation](https://on.cypress.io/guides/cloud)
https://on.cypress.io/guides/cloud/introduction
and to the [Cypress Cloud](https://on.cypress.io/cloud)
https://on.cypress.io/cloud
=> docs: link recording example to cypress cloud

README.md
This PR adds an introduction to the [README](https://github.com/cypress-io/github-action/blob/master/README.md) document to explain about the default use of `github-action`.
There have been several user issues lately in various places where the basic functionality of the action was not properly understood. Up until now there was no concise place in the action documentation which explained it.
=> docs: add intro to readme for default use

README.md
This PR cautions about the use of the `start` parameter to run tests. There have been several instances lately where users have made this mistake.
=> docs: caution use of start to run tests

CHANGELOG.md, README.md
This PR moves the [README > Changelog](https://github.com/cypress-io/github-action/blob/master/README.md#changelog) section contents to a separate new file `CHANGELOG.md` in the root of the repository.
This is in preparation to add more details to the Changelog, which would make it overly long to be displayed directly in the [README](https://github.com/cypress-io/github-action/blob/master/README.md) file itself. Once this PR is reviewed and merged, I will submit a follow-on PR to expand the details in the new `CHANGELOG.md`.
I also plan to submit a separate PR with new information about GitHub compatibility.
=> docs: create separate changelog

CHANGELOG.md
This PR adds 5.x features which were not yet listed in the [CHANGELOG.md](https://github.com/cypress-io/github-action/blob/master/CHANGELOG.md) document:
- 5.7.0 - Add basic Yarn Modern Plug'n'Play support
- 5.6.0 - Improve check for lockfile presence
- 5.5.0 - Examples add Yarn Modern
- 5.4.0 - Examples add Yarn Classic
- 5.3.0 - Add parameter `publish-summary` (default `true`)
- 5.1.0 - Add parameter `auto-cancel-after-failures`
=> docs: add missing 5.x features to changelog

examples/component-tests/README.md, examples/component-tests/cypress.config.js, examples/component-tests/index.html, examples/component-tests/package-lock.json, examples/component-tests/package.json, examples/component-tests/src/App.css, examples/component-tests/src/App.jsx, examples/component-tests/src/components/Stepper.cy.jsx, examples/component-tests/src/components/Stepper.jsx, examples/component-tests/src/index.css, examples/component-tests/src/main.jsx
- The link in [examples/component-tests/README.md](https://github.com/cypress-io/github-action/blob/master/examples/component-tests/README.md) to [component-testing/react/quickstart](https://docs.cypress.io/guides/component-testing/react/quickstart) is broken, due to changes on the documentation website. (It's also not covered by an `on.cypress.io` redirect.)
---
The [examples/component-tests](https://github.com/cypress-io/github-action/tree/master/examples/component-tests) is refactored to use latest versions and to conform to the updated [Component Testing > Getting Started](https://docs.cypress.io/guides/component-testing/getting-started) document.
```bash
cd examples/component-tests
npm ci
npx cypress run --component
```
Run [.github/workflows/example-component-test.yml](https://github …
=> test: update component-tests example

package-lock.json, package.json
This PR updates [prettier](https://www.npmjs.com/package/prettier) from `2.8.4` to [prettier@3.0.1](https://github.com/prettier/prettier/releases/tag/3.0.1).
This is in preparation for the expected support of Node.js `20` for JavaScript actions. Making updates separate as far as possible reduces the risk of causing unexpected breaking changes.
Execute
```bash
npm ci
npm run format
npm run build
```
and check there are no `git` changes to be committed.
=> chore(deps): update prettier to 3.0.1

README.md
This PR improves the [README > Docker image](https://github.com/cypress-io/github-action#docker-image) example:
1. It builds on the suggestions made in the open PRs #938 and #963 to add `options: --user 1001` to the Docker example. For GitHub-hosted runners `--user 1001` is mandatory when testing against Mozilla Firefox and optional for other browsers.
2. The container is changed to the generic `cypress/browsers:latest` image tag to provide a timeless and easily readable example. A link to the Docker Hub [cypress/browsers:latest](https://hub.docker.com/r/cypress/browsers/tags) is provided so that readers can search for specific versions such as [cypress/browsers:node-20.5.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1](https://hub.docker.com/layers/cypress/browsers/node-20.5.0-c …
=> docs: rework docker example

examples/yarn-modern-pnp/package.json, examples/yarn-modern-pnp/yarn.lock
This PR corrects the package name in [examples/yarn-modern-pnp/package.json](https://github.com/cypress-io/github-action/blob/master/examples/yarn-modern-pnp/package.json) which was a misleading duplicate of the package name also used in [examples/yarn-modern/package.json](https://github.com/cypress-io/github-action/blob/master/examples/yarn-modern/package.json).
=> chore: correct package name for yarn-modern-pnp example

README.md
This repository contains links to example repos using [Legacy configurations](https://docs.cypress.io/guides/references/legacy-configuration) of Cypress concerning version 9 and below. The release of the first version of Cypress to conform to current configurations was [Cypress 10.0.0](https://docs.cypress.io/guides/references/changelog#10-0-0) released on June 1, 2022, more than one year ago.
Based on user issues in the Cypress repository there is a clear trend that new development is not relying on legacy Cypress 9 versions and below.
Continuing to link to example repositories, which have been left unmaintained and have not been updated in the last year, is not helpful for users looking for up-to-date running examples which demonstrate Cypress GitHub Action using a minimum Cypress …
=> docs: remove links to legacy external example repos

examples/config/package-lock.json, examples/config/package.json, examples/start-and-yarn-workspaces/workspace-1/package.json, examples/start-and-yarn-workspaces/workspace-2/package.json, examples/start-and-yarn-workspaces/yarn.lock, examples/start/package-lock.json, examples/start/package.json
This PR updates the npm module [serve](https://www.npmjs.com/package/serve) to [serve@14.2.1](https://github.com/vercel/serve/releases/tag/14.2.1) which is the latest version.
[serve](https://www.npmjs.com/package/serve) is used in several examples as a webserver.
It reminds in logs if it is not the latest version, for example in job [16178553414](https://github.com/cypress-io/github-action/actions/runs/5964083289/job/16178553414):
>> example-config@1.0.0 start
>> serve public --listen 3333
>
> UPDATE  The latest version of `serve` is 14.2.1
> INFO  Accepting connections at http://localhost:3333
> HTTP  8/24/2023 1:04:00 PM ::1 GET /
> HTTP  8/24/2023 1:04:00 PM ::1 Returned 200 in 1027 ms
=> chore(deps): update serve to 14.2.1

README.md
Descriptions and examples using [Legacy configurations](https://docs.cypress.io/guides/references/legacy-configuration) of Cypress concerning version 9 and below are now archived in the [v5](https://github.com/cypress-io/github-action/tree/v5) branch.
This PR removes descriptions of directory layouts for [Legacy configurations](https://docs.cypress.io/guides/references/legacy-configuration) from the [README > Working directory](https://github.com/cypress-io/github-action/blob/master/README.md#working-directory) section.
The section is rewritten and simplified to refer to more complete descriptions of different possible folder layouts in the Cypress documentation located under [Folder structure](https://on.cypress.io/guides/core-concepts/writing-and-organizing-tests#Folder-Structure).
=> docs: rewrite readme working directory description

.github/workflows/example-component-test.yml
This PR changes the workflow [.github/workflows/example-component-test.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-component-test.yml) to run the action from the `HEAD` of the branch it is started in instead of explicitly from the [v5](https://github.com/cypress-io/github-action/tree/v5) branch as is currently the case:
https://github.com/cypress-io/github-action/blob/d5d4c90348e3b92abdcbbad1a3659597b18945bb/.github/workflows/example-component-test.yml#L15-L16
This aligns the workflow with all the other example workflows in [.github/workflows](https://github.com/cypress-io/github-action/blob/master/.github/workflows/) which use the construct:
```yml
- name: Cypress tests
uses: ./
```
=> test: run component test example from current branch

.github/workflows/example-basic-pnpm.yml, .github/workflows/example-basic.yml, .github/workflows/example-component-test.yml, .github/workflows/example-recording.yml, CONTRIBUTING.md, README.md
This PR changes the recommended version of this action from `v5` to `v6`.
It is submitted as a feature so that the updated README is published to https://www.npmjs.com/package/@cypress/github-action.
---
When merging please also follow the instructions in [CONTRIBUTING > GitHub Marketplace publication](https://github.com/cypress-io/github-action/blob/master/CONTRIBUTING.md#github-marketplace-publication). This is a manual step.
---
- I originally wanted to wait for GitHub [`runs.using` for JavaScript actions](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing-for-javascript-actions) to properly document the use of `node20`, however to avoid confusion with the pending PR https://github.com/cypress-io/github-action/pull/1009 I propose to change …
=> feat: recommend v6 as standard action version

README.md
In the example in the [README > Specify auto cancel after failures](https://github.com/cypress-io/github-action/blob/master/README.md#specify-auto-cancel-after-failures) section, the following lines are removed:
```yml
- name: Setup Node
uses: actions/setup-node@v3
```
- The example does not need any specific version of Node.js in order to be used and to be understandable
- [GitHub Actions Runner Images](https://github.com/actions/runner-images) already include Node.js LTS (currently Node.js `18.17.1`) installed by default
- `actions/setup-node@v3` is called without specifying any version of Node.js. [actions/setup-node](https://github.com/actions/setup-node) advises against this:
> The node-version input is optional. If not supplied, the node version from PATH will be used. However, it …
=> docs: remove setup-node from auto cancel example

.github/workflows/example-node-versions.yml, CHANGELOG.md, CONTRIBUTING.md, README.md
This PR aligns the Cypress JavaScript GitHub Action documentation and examples in this repo with the Cypress documentation [Getting Started > System requirements > Node.js](https://docs.cypress.io/guides/getting-started/installing-cypress#Nodejs) which specifies
- Node.js 18.x
- Node.js 20.x and above
as being supported. Node.js `16` is no longer listed.
There is **no** change to the action itself, which can continue to be used with Node.js `16` although it will be classed as unsupported.
In any case Node.js `16` moves into a general end-of-life status on Sep 11, 2023 - see [Node.js 16 EOL announcement](https://nodejs.org/en/blog/announcements/nodejs16-eol).
This PR removes Node.js `16` ...
- from the list of versions which [.github/workflows/example-node-versions.yml](https://github.com/c …
=> feat(deps): remove node.js 16

README.md
Update all workflow examples in the [README](https://github.com/cypress-io/github-action/blob/master/README.md) documentation to use JavaScript action [actions/checkout](https://github.com/actions/checkout) `v4`.
- The previously used `v3` runs under `node16` with [end-of-life](https://nodejs.org/en/blog/announcements/nodejs16-eol) today, Sep 11, 2023
- `v4` is the latest version, which runs under `node20`, and this is under active support
=> docs: update actions/checkout to v4 in README

.github/workflows/check-dist.yml, .github/workflows/check-markdown.yml, .github/workflows/example-wait-on.yml, .github/workflows/main.yml
This PR replaces the use of the JavaScript action [bahmutov/npm-install](https://github.com/marketplace/actions/npm-or-yarn-install-with-caching) in several [.github/workflows](https://github.com/cypress-io/github-action/tree/master/.github/workflows) by a call to [npm-ci](https://docs.npmjs.com/cli/v10/commands/npm-ci).
The JavaScript action [bahmutov/npm-install](https://github.com/bahmutov/npm-install) relies on `node16`, which reached [end-of-life](https://nodejs.org/en/blog/announcements/nodejs16-eol) on Sep 11, 2023. It is uncertain if there will be a new release to support `node20` and it has been more than a year since any maintainer has responded to issues in this repo.
The alternative [npm-ci](https://docs.npmjs.com/cli/v10/commands/npm-ci) is available for all supported …
=> chore(deps): use npm ci instead of npm-install

README.md
This PR updates the documentation-only example [README > Subfolders](https://github.com/cypress-io/github-action/blob/master/README.md#subfolders).
- Instead of having an unusual mixture of Yarn and npm package managers and their corresponding lock files, the example is changed to only using npm with `package-lock.json` files.
- The use of the JavaScript action [bahmutov/npm-install](https://github.com/marketplace/actions/npm-or-yarn-install-with-caching) is replaced by a call to [npm-ci](https://docs.npmjs.com/cli/v10/commands/npm-ci), since the JavaScript action runs only on the end-of-life Node.js `16` version.
- The [Cypress configuration file](https://docs.cypress.io/guides/references/configuration#Configuration-File) name is updated to the correct name `cypress.config.js` for …
=> docs: rework subfolders example

.github/workflows/example-chrome.yml
This PR rationalizes the [example-chrome.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-chrome.yml) workflow.
- Electron tests run with `npx cypress info` are disabled. Testing against Electron does not belong in a Chrome workflow.
- Instead of running headless tests twice, now one headless and one headed test is run.
=> test: rework example-chrome workflow

README.md
This PR adds a note in [README > Compatibility](https://github.com/cypress-io/github-action/blob/master/README.md#compatibility) that `v4` and `v5` of the `cypress-io/github-action` which use `node16` are now deprecated.
1. Node.js 16 entered [end-of-life](https://nodejs.org/en/blog/announcements/nodejs16-eol) on Sep 11, 2023.
2. [GitHub Actions: Transitioning from Node 16 to Node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) announced on Sep 22, 2023 the beginning of the deprecation process for `node16` actions. (`node12` are already forced to run under `node16`. Early next year they will all be forced on to `node20`.)
=> docs: deprecate versions v4 & v5 using node16

.github/workflows/example-config.yml, README.md, examples/config/cypress.config-alternate.js
- This PR follows on from issue https://github.com/cypress-io/github-action/issues/1046.
The PR provides two improvements:
1. The [README > Config file](https://github.com/cypress-io/github-action#config-file) section is updated to use an example config filename from current Cypress configurations (Cypress `10.x` and later) where the filename by default is either `cypress.config.js` for JavaScript apps or `cypress.config.ts` for TypeScript apps, instead of `cypress.json` for legacy configurations (Cypress `9.x` and earlier).
2. A job is added to the [example-config.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-config.yml) workflow which demonstrates the use of the `config-file` parameter. This parameter was not previously being tested.
Run the …
=> test: demonstrate config-file parameter

.github/workflows/example-docker.yml
For consistency with other examples, the [example-docker.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-docker.yml) workflow is modified to use the action from its branch instead of from the published action. CI will then test after `push` or `pull_request` event triggers correctly using any modifications to the action.
```yaml
- uses: cypress-io/github-action@v6
```
is changed to
```yaml
- uses: ./
```
=> test: example-docker use action from branch

.github/workflows/example-node-versions.yml, README.md
[Node.js 21.0.0](https://nodejs.org/en/blog/release/v21.0.0) was released on Oct 17, 2023.
This PR adds Node.js `21` to the matrix of tested nodes under [.github/workflows/example-node-versions.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-node-versions.yml) and to the [README](https://github.com/cypress-io/github-action/blob/master/README.md).
According to [Node.js release schedule](https://github.com/nodejs/release#release-schedule) plans, Node.js `20.x` changes from "Current" status to "LTS" status on Oct 24, 2023. This does not affect the tests as Node.js `20` is already included in the matrix of tested versions.
=> tests(deps): add node.js 21 (current) to tests

examples/component-tests/package-lock.json, examples/component-tests/package.json, examples/nextjs/package-lock.json, examples/nextjs/package.json, examples/wait-on-vite/package-lock.json, examples/wait-on-vite/package.json
dependabot reports moderate vulnerabilities in examples using [postcss](https://www.npmjs.com/package/postcss) < `8.4.31`
- [examples/nextjs](https://github.com/cypress-io/github-action/tree/master/examples/nextjs)
This PR uses `npm update` to update dependencies for the above examples to resolve the reported vulnerability in [postcss](https://www.npmjs.com/package/postcss) < `8.4.31`.
The dependency [postcss](https://www.npmjs.com/package/postcss) is updated to `8.4.31`, which is currently the latest version.
=> chore(deps): update examples with postcss to 8.4.31

examples/yarn-classic/yarn.lock
[examples/yarn-classic](https://github.com/cypress-io/github-action/tree/master/examples/yarn-classic) through
https://github.com/cypress-io/github-action/blob/97e80e2e3ba77e9991d957bc8763d660971fab69/examples/yarn-classic/yarn.lock#L925-L930
continues to use the deprecated `qs@6.10.5`.
Yarn Classic does not avoid deprecated versions, unlike Yarn Modern.
```text
$ cd examples/yarn-classic
$ yarn list --pattern qs
yarn list v1.22.19
└─ qs@6.10.5
```
`cypress` is removed and reinstalled to allow Yarn to pick up `@cypress/request@3.0.1` which is pegged to the required (non-deprecated) `qs@6.10.4`.
A future version of Cypress could be updated to depend on `@cypress/request@^3.0.1` instead of on `@cypress/request@^3.0.0` to avoid this mismatch in Yarn Classic installations.
=> chore(deps): downgrade to qs@6.10.4 in yarn-classic example

.github/workflows/example-basic-pnpm.yml, README.md
If `cypress-io/github-action` finds a `pnpm-lock.yaml` file, it uses the pnpm command `pnpm install --frozen-lockfile` by default to install dependencies. It does not however cache these dependencies for a future run of the same workflow.
This PR is a workaround to the pnpm example to make up for this missing functionality.
It adds dependency caching of the [pnpm store](https://pnpm.io/cli/store) contents using the command `pnpm store path` to find the location of the store and [actions/cache](https://github.com/actions/cache) to cache the store contents. This is applied to
- the workflow [example-basic-pnpm.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic-pnpm.yml) and to
- the [README > …
=> test: add npm caching to pnpm examples

docs/MAINTENANCE.md
Since last week `npm run check:markdown` has been sporadically failing when checking the link
`[Microsoft Windows](https://www.microsoft.com/windows/)` to https://www.microsoft.com/windows/ in the document
[docs/MAINTENANCE.md](https://github.com/cypress-io/github-action/blob/master/docs/MAINTENANCE.md).
This is the portion of the check log showing the failure:
```text
FILE: docs/MAINTENANCE.md
[✓] ../examples
[✓] https://docs.cypress.io/guides/references/configuration
[✓] https://github.com/cypress-io/github-action
[✓] https://www.npmjs.com/
[✓] https://pnpm.io/
[✓] https://classic.yarnpkg.com/
[✓] https://yarnpkg.com/
[✓] https://github.com/cypress-io/github-action/tree/v5/examples/v9
[✓] https://github.com/cypress-io/github-action/tree/v5/
[✓] …
```
=> ci: remove microsoft windows from markdown-link-check

.github/workflows/check-dist.yml, .github/workflows/example-node-versions.yml, .github/workflows/main.yml, README.md
This PR updates workflows and examples to use [actions/setup-node@v4](https://github.com/actions/setup-node/releases/tag/v4) that runs under `node20` (instead of [actions/setup-node@v3](https://github.com/actions/setup-node/releases/tag/v3) which runs under the deprecated `node16` version).
The specific version of Node.js used in workflows
- [.github/workflows/main.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/main.yml)
- [.github/workflows/check-dist.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/check-dist.yml)
is updated and aligned to `NODE20_VERSION="20.8.1"` in https://github.com/actions/runner/blob/main/src/Misc/externals.sh.
=> chore(deps): update to actions/setup-node@v4

scripts/update-cypress-latest-other.sh
If [scripts/update-cypress-latest-other.sh](https://github.com/cypress-io/github-action/blob/master/scripts/update-cypress-latest-other.sh) is run on a cleanly cloned repository or on one where `git clean` has been run, then it fails to update Cypress in the Yarn `workspace-2` [examples/start-and-yarn-workspaces/workspace-2](https://github.com/cypress-io/github-action/tree/master/examples/start-and-yarn-workspaces/workspace-2). If it is run again, then the update works as expected.
Replace the use of `npm install` in [scripts/update-cypress-latest-other.sh](https://github.com/cypress-io/github-action/blob/master/scripts/update-cypress-latest-other.sh) operating on [examples/start-and-yarn-workspaces](https://github.com/cypress-io/github-action/tree/master/examples/start-and-yarn-workspaces …
=> build: fix version update for yarn workspace

examples/nextjs/package-lock.json, examples/nextjs/package.json
This PR updates the E2E example in [examples/nextjs](https://github.com/cypress-io/github-action/tree/master/examples/nextjs) from Next.js `13` to [Next.js 14](https://nextjs.org/blog/next-14), announced on Oct 26, 2023.
The original setup followed the instructions in [Create a Next.js App](https://nextjs.org/learn/basics/create-nextjs-app) (see PR #867) and the resulting app has remained unchanged between Next.js `13` and `14`.
=> chore(deps): update nextjs example to v14

.github/workflows/example-recording.yml, README.md
- closes #1072
This PR corrects an issue where the [example-recording.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-recording.yml) workflow passes back a success status to GitHub in the `parallel` job whether or not the Cypress tests from the project [examples/recording](https://github.com/cypress-io/github-action/tree/master/examples/recording) pass or fail.
The code example in [README > Outputs](https://github.com/cypress-io/github-action/blob/master/README.md#outputs) is also corrected.
1. Modify [examples/recording/cypress/e2e/spec-a.cy.js](https://github.com/cypress-io/github-action/blob/master/examples/recording/cypress/e2e/spec-a.cy.js) to introduce a deliberate failure condition by adding the following to the test spec:
```js …
```
=> test: fix example-recording failure reporting status

examples/config/package-lock.json, examples/config/package.json
This PR updates [start-server-and-test](https://www.npmjs.com/package/start-server-and-test) to [v2.0.3](https://github.com/bahmutov/start-server-and-test/releases/tag/v2.0.3) in [examples/config](https://github.com/cypress-io/github-action/tree/master/examples/config) to resolve a vulnerability 
[CVE-2023-45857 - Axios Cross-Site Request Forgery Vulnerability](https://github.com/advisories/GHSA-wf5p-g6vw-rhxx).
```bash
cd examples/config
npm audit
```
No vulnerabilities should be reported.
=> chore(deps): update start-server-and-test to `2.0.3`

CHANGELOG.md, README.md
This PR adds release [v6.6.0](https://github.com/cypress-io/github-action/releases/tag/v6.6.0) to the [CHANGELOG.md](https://github.com/cypress-io/github-action/blob/master/CHANGELOG.md).
- [v6.6.0](https://github.com/cypress-io/github-action/releases/tag/v6.6.0) included PR https://github.com/cypress-io/github-action/pull/1056
=> docs: update changelog for release v6.6.0

dist/index.js, index.js, package-lock.json, package.json
This PR updates Prettier to [3.1.1](https://github.com/prettier/prettier/releases/tag/3.1.1), current latest version.
The previous version, Prettier [3.1.0](https://prettier.io/blog/2023/11/13/3.1.0.html), introduced new formatting for nested JavaScript tenaries to increase readability.
The action source has been reformatted according to the new rules. This causes whitespace changes only.
=> chore(deps): update prettier to 3.1.1

.github/workflows/example-chrome.yml, .github/workflows/example-firefox.yml, README.md
This PR updates the usage of [actions/upload-artifact](https://github.com/actions/upload-artifact) from `v3` to [actions/upload-artifact@v4](https://github.com/actions/upload-artifact/releases/tag/v4.0.0) in affected [workflows](https://github.com/cypress-io/github-action/tree/master/.github/workflows):
- [example-chrome.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-chrome.yml)
- [example-firefox.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-firefox.yml)
The `v3` version [actions/upload-artifact@v3.1.3](https://github.com/actions/upload-artifact/tree/v3.1.3) was tied to the deprecated Node.js `16` version which entered [end-of-life](https://nodejs.org/en/blog/announcements/nodejs16-eol/) on Sep 9, 2023. The …
=> test(deps): update github action upload-artifact to v4

examples/config/package-lock.json, examples/webpack/package-lock.json
This PR updates the npm transient dependency [follow-redirects](https://www.npmjs.com/package/follow-redirects) to [follow-redirects@1.15.4](https://github.com/follow-redirects/follow-redirects/releases/tag/v1.15.4) to resolve a security vulnerability [Follow Redirects improperly handles URLs in the url.parse() function](https://github.com/advisories/GHSA-jchw-25xp-jwwc) reported by GitHub Dependabot.
```shell
cd examples/webpack
npm ci
```
and
```shell
cd examples/config
npm ci
```
No vulnerabilities should be reported.
=> chore(deps): update follow-redirects to resolve vulnerability

.github/workflows/example-basic-pnpm.yml, .github/workflows/example-install-only.yml, README.md
This PR updates the use of [actions/cache](https://github.com/actions/cache) in the [README](https://github.com/cypress-io/github-action/blob/master/README.md) file and example workflows:
- [example-basic-pnpm.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic-pnpm.yml)
- [example-install-only.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-install-only.yml)
from `@v3` to `@v4`.
The previously used [actions/cache@v3](https://github.com/actions/cache/releases/tag/v3) tag of this JavaScript Action relied on the deprecated `node16` version.
With the release of [actions/cache@v4.0.0](https://github.com/actions/cache/releases/tag/v4.0.0) compatibility with `node20` is available.
Run modified workflows twice. The …
=> test(deps): update action/cache to v4

.github/workflows/main.yml
This PR updates the use of [cycjimmy/semantic-release-action](https://github.com/cycjimmy/semantic-release-action) in the [release workflow (`main.yml`)](https://github.com/cypress-io/github-action/blob/master/.github/workflows/main.yml) from `@v3` to `@v4`.
The branch [cycjimmy/semantic-release-action@v3](https://github.com/cycjimmy/semantic-release-action/tree/v3) of this JavaScript Action relied on the deprecated `node16` version.
With the release of [cycjimmy/semantic-release-action@v4.0.0](https://github.com/cycjimmy/semantic-release-action/releases/tag/v4.0.0) compatibility with `node20` is available.
To avoid deprecation warnings from GitHub runners, Cypress GitHub Action `cypress-io/github-action` is migrated to use the [cycjimmy/semantic-release-action@v4](https://github.com/cycji …
=> fix(deps): update cycjimmy/semantic-release-action to v4

examples/component-tests/package-lock.json, examples/component-tests/package.json, examples/wait-on-vite/package-lock.json, examples/wait-on-vite/package.json
This PR updates the npm module [vite](https://www.npmjs.com/package/vite) to [vite@4.5.2](https://github.com/vitejs/vite/releases/tag/v4.5.2) to resolve a security vulnerability [Vite dev server option `server.fs.deny` can be bypassed when hosted on case-insensitive filesystem](https://github.com/advisories/GHSA-c24v-8rfc-w8vw) reported by GitHub Dependabot.
```shell
cd examples/component-tests
npm ci
```
and
```shell
cd examples/wait-on-vite
npm ci
```
No vulnerabilities should be reported.
=> chore(deps): update vite to resolve vulnerability (server.fs.deny)

.github/workflows/example-basic-pnpm.yml, README.md
This PR removes the dependency on the JavaScript GitHub Action [pnpm/action-setup](https://github.com/pnpm/action-setup).
[pnpm/action-setup](https://github.com/pnpm/action-setup) was last updated on Jul 26, 2023 to [pnpm/action-setup@v2.4.0](https://github.com/pnpm/action-setup/releases/tag/v2.4.0). This version supports only `node16` version and causes deprecation warnings when run on GitHub:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: pnpm/action-setup@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
- https://github.com/pnpm/action-setup/issues/99 was opened to request an update of the pnpm action to support `node20`. There is no clear indication about if / when …
=> test(deps): install pnpm with npm

.husky/pre-commit, package-lock.json, package.json
- This PR migrates the action to [husky@9.0.6](https://github.com/typicode/husky/releases/tag/v9.0.6), replacing the auto-generated, incomplete PR from renovate https://github.com/cypress-io/github-action/pull/1119.
Although Husky `9` is stated to be backwards compatible to Husky `8` (see [husky@9.0.1](https://github.com/typicode/husky/releases/tag/v9.0.1)) the following additional migration steps are taken:
To avoid a deprecation warning when installing dependencies, the prepare script in [package.json](https://github.com/cypress-io/github-action/blob/master/package.json) is changed from
```json
"prepare": "husky install"
```
to
```json
"prepare": "husky"
```
The following lines are removed from [.husky/pre-commit](https://github.com/cypress-io/github-action/blob/master/.husky/pre-commit) …
=> chore(deps): update husky to 9.0.6

.github/workflows/example-start-and-yarn-workspaces.yml
The comments in [.github/workflows/example-start-and-yarn-workspaces.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-start-and-yarn-workspaces.yml)
https://github.com/cypress-io/github-action/blob/4cedef59b86ca68d5698ff837ccd0933e91ac316/.github/workflows/example-start-and-yarn-workspaces.yml#L34-L43
regarding `fail-fast` are out of place, since the workflow does not record to the Cypress Cloud.
Modify the text to explain about using `fail-fast`. It allows both tests to run independently of any failure of the other test.
=> test: correct example-start-and-yarn-workspaces fail-fast comments

.github/workflows/example-start-and-pnpm-workspaces.yml, README.md, examples/start-and-pnpm-workspaces/package.json, examples/start-and-pnpm-workspaces/packages/workspace-1/cypress.config.js, examples/start-and-pnpm-workspaces/packages/workspace-1/cypress/e2e/spec.cy.js, examples/start-and-pnpm-workspaces/packages/workspace-1/package.json, examples/start-and-pnpm-workspaces/packages/workspace-1/public/index.html, examples/start-and-pnpm-workspaces/packages/workspace-2/cypress.config.js, examples/start-and-pnpm-workspaces/packages/workspace-2/cypress/e2e/spec.cy.js, examples/start-and-pnpm-workspaces/packages/workspace-2/package.json, examples/start-and-pnpm-workspaces/packages/workspace-2/public/index.html, examples/start-and-pnpm-workspaces/pnpm-lock.yaml, examples/start-and-pnpm-workspaces/pnpm-workspace.yaml, scripts/update-cypress-latest-other.sh
The Cypress GitHub JavaScript Action (GHA) provides minimum support for projects using the [pnpm package manager](https://pnpm.io). It runs `pnpm install --frozen-lockfile` if it finds a `pnpm-lock.yaml` lockfile. It however offers no simple out-of-the-box provision for working with [pnpm workspaces](https://pnpm.io/workspaces). There is no logic in GHA to deal with the lack of a lockfile in a pnpm workspace and so GHA is unable to install dependencies directly from the workspace.
- Note also https://github.com/cypress-io/github-action/issues/1044. pnpm dependency caching is not implemented in GHA.
[pnpm](https://pnpm.io/workspaces) has built-in support for monorepositories (AKA multi-package repositories, multi-project repositories, or monolithic repositories).
pnpm repos using …
=> test: add pnpm workspaces example

README.md
- closes #1142
The badge for the newly-added workflow [.github/workflows/example-start-and-pnpm-workspaces.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-start-and-pnpm-workspaces.yml) shows "no status", instead of the expected "passed" status in the [README > pnpm workspaces](https://github.com/cypress-io/github-action/blob/master/README.md#pnpm-workspaces) section.
Most status badges in the [README](https://github.com/cypress-io/github-action/blob/master/README.md) do not conform to the documentation [Adding a workflow status badge](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge) which specifies the format
```text
https://github.com/OWNER/REPOSITORY/actions/workflows/WORKFLOW-FILE/badge.sv …
```
=> docs: fix status badges in readme

examples/config/package-lock.json
Installing dependencies in [examples/config](https://github.com/cypress-io/github-action/tree/master/examples/config) reports vulnerabilities:
> 1 moderate severity vulnerability
Run `npm audit fix` in [examples/config](https://github.com/cypress-io/github-action/tree/master/examples/config).
Execute
```shell
cd examples/config
npm ci
npm start
```
Confirm that no vulnerabilities are reported.
Open web browser and check that "This is a page" shows on http://localhost:3333/ .
=> chore(deps): update example config

README.md
The [example workflow](https://github.com/cypress-io/github-action/blob/master/README.md#component-testing) for Component Testing in the README file uses `name: End-to-end tests`. This is not a fitting name for an example of Component Testing!
Change to `name: Component tests` in the [Component Testing](https://github.com/cypress-io/github-action/blob/master/README.md#component-testing) section of the README file.
=> docs: correct name in readme ct example

examples/webpack/package-lock.json
In [examples/webpack](https://github.com/cypress-io/github-action/tree/master/examples/webpack) `npm audit` reports
```text
express  <4.19.2
Severity: moderate
Express.js Open Redirect in malformed URLs - https://github.com/advisories/GHSA-rv95-896h-c2vc
fix available via `npm audit fix`
node_modules/express
1 moderate severity vulnerability
```
`"express": "^4.17.3"` is a dependency of [webpack-dev-server@5.0.4](https://github.com/webpack/webpack-dev-server/releases/tag/v5.0.4) (current latest)
Refresh dependencies of [webpack-dev-server@5.0.4](https://github.com/webpack/webpack-dev-server/releases/tag/v5.0.4) through uninstall and re-install with npm.
Ubuntu `22.04.4` LTS, Node.js `20.12.0` LTS
Execute:
```shell
cd examples/webpack
npm ci
```
and confirm no vulnerabilities reported.
=> chore(deps): update webpack-dev-server dependencies

.github/workflows/example-basic-pnpm.yml, .github/workflows/example-start-and-pnpm-workspaces.yml, README.md, examples/basic-pnpm/pnpm-lock.yaml, examples/start-and-pnpm-workspaces/pnpm-lock.yaml
This PR updates the version of pnpm used in the workflows:
- [.github/workflows/example-start-and-pnpm-workspaces.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-start-and-pnpm-workspaces.yml)
and in the
- [README > pnpm](https://github.com/cypress-io/github-action/blob/master/README.md#pnpm) section
from pnpm `8` to pnpm `9` (latest version).
[pnpm@9.0.0](https://github.com/pnpm/pnpm/releases/tag/v9.0.0) was released on Apr 16, 2024.
Additionally the `pnpm-lock.yaml` lockfiles for
- …
=> test(deps): update examples to pnpm 9

.github/workflows/example-node-versions.yml, README.md
[Node.js 22.0.0](https://nodejs.org/en/blog/release/v22.0.0) was released on Apr 24, 2024.
This PR adds Node.js `22` to the matrix of tested nodes under [.github/workflows/example-node-versions.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-node-versions.yml) and to the [README](https://github.com/cypress-io/github-action/blob/master/README.md) examples.
According to [Node.js release schedule](https://github.com/nodejs/release#release-schedule) plans, Node.js `22.x` changes from "Current" status to "LTS" status on Oct 29, 2024.
=> tests(deps): add node.js 22 (current) to tests

.github/workflows/example-basic-pnpm.yml, .github/workflows/example-start-and-pnpm-workspaces.yml, README.md
- related to issue https://github.com/cypress-io/github-action/issues/1179
pnpm [basic](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic-pnpm.yml) and [workspaces](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-start-and-pnpm-workspaces.yml) workflows
- [example-basic-pnpm.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic-pnpm.yml)
- [example-start-and-pnpm-workspaces.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-start-and-pnpm-workspaces.yml)
include the use of the GitHub provided [actions/cache](https://github.com/actions/cache) action to cache dependencies installed by pnpm, with the input `restore-keys` set to a loose match in …
=> test: remove pnpm store cache loose match restore-keys

examples/nextjs/package-lock.json, examples/nextjs/package.json
`npm audit` reports a vulnerability with `next@14.0.1` in [examples/nextjs](https://github.com/cypress-io/github-action/tree/master/examples/nextjs)
Update to [next@14.2.3](https://github.com/vercel/next.js/releases/tag/v14.2.3) which is current `latest`.
```shell
cd examples/nextjs
npm ci
npm audit
```
=> test(deps): update next to 14.2.3

examples/wait-on-vite/package-lock.json, examples/wait-on-vite/package.json
- supports closure of enhancement issue #1081
[examples/wait-on-vite](https://github.com/cypress-io/github-action/tree/master/examples/wait-on-vite) is updated to [vite@5.2.11](https://github.com/vitejs/vite/releases/tag/v5.2.11).
```shell
cd examples/wait-on-vite
npm ci
npm run dev
```
In a separate terminal window, execute:
```shell
npm test
```
=> test(deps): update examples/wait-on-vite to v5

.github/workflows/example-basic-pnpm.yml, .github/workflows/example-start-and-pnpm-workspaces.yml, README.md
- closes https://github.com/cypress-io/github-action/issues/1179
Workflows such as [.github/workflows/example-basic-pnpm.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic-pnpm.yml), which attempt to cache the contents of the pnpm store, fail sporadically, especially after there has been a change in the version of Cypress and where pnpm workflow jobs are running in parallel.
If the cache of the pnpm store cache is loaded with the `cypress` module, through steps outside of the Cypress GitHub action, and the Cypress binary has not been successfully cached by the action, then Cypress fails with a verification error.
There is no mechanism available to coordinate these two different caching mechanisms. (See also …
=> test: remove pnpm store caching

.github/workflows/example-node-versions.yml, README.md
According to [Node.js release schedule](https://github.com/nodejs/release#release-schedule) plans, Node.js `21.x` reached End-of-life status on June 1, 2024.
This PR removes Node.js `21`
- from the matrix of tested nodes under [.github/workflows/example-node-versions.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-node-versions.yml) and
- from the [README](https://github.com/cypress-io/github-action/blob/master/README.md).
Supported versions are now `18.x`, `20.x` and `22.x`.
There is no change to the action itself.
- `cypress-io/github-action@v6` continues to use `node20`
See [README > Usage](https://github.com/cypress-io/github-action#usage) for a more detailed explanation.
- Node.js [Release …
=> feat(deps): remove node.js 21

CHANGELOG.md
- follows on from https://github.com/cypress-io/github-action/pull/1189
Update the [CHANGELOG](https://github.com/cypress-io/github-action/blob/master/CHANGELOG.md)
| Version | Changes                                                    |
| ------- | ---------------------------------------------------------- |
| v6.7.0  | Examples remove Node.js 21. End of support for Node.js 21. |
=> docs: add changelog 6.7.0 entry

dist/index.js, examples/webpack/package-lock.json, package-lock.json
[Uncontrolled resource consumption in braces](https://github.com/advisories/GHSA-grv7-fg5c-xmjg) in [CVE-2024-4068](https://nvd.nist.gov/vuln/detail/CVE-2024-4068) reports a vulnerability for [braces](https://www.npmjs.com/package/braces) < `3.0.3`
Update to [braces@3.0.3](https://www.npmjs.com/package/braces/v/3.0.3)
1. Rebuild `cypress-io/github-action`
2. Update [examples/webpack](https://github.com/cypress-io/github-action/tree/master/examples/webpack)
=> fix(deps): update to braces 3.0.3

README.md
- PR https://github.com/cypress-io/github-action/pull/1188 removed pnpm caching from [pnpm](https://github.com/cypress-io/github-action/blob/master/README.md#pnpm), however [pnpm workspaces](https://github.com/cypress-io/github-action/blob/master/README.md#pnpm-workspaces) still has a reference to pnpm caching.
Remove the outdated reference in [pnpm workspaces](https://github.com/cypress-io/github-action/blob/master/README.md#pnpm-workspaces) to pnpm caching.
=> docs: remove outdated readme pnpm text

README.md
- related to https://github.com/cypress-io/cypress-docker-images/issues/1119
If `cypress-io/github-action` is used to run a Cypress Docker image [cypress/included](https://github.com/cypress-io/cypress-docker-images/tree/master/included) as a container with `--user 1001` (as recommended), then GitHub actions may report a caching error:
> Failed to restore: "/usr/bin/tar" failed with error: The process '/usr/bin/tar' failed with exit code 2
[cypress/included](https://github.com/cypress-io/cypress-docker-images/tree/master/included) Docker images include the Cypress binary installed in `/root/.cache/Cypress` with owner `root` (see environment variable `CYPRESS_CACHE_FOLDER` of Docker image).
By default `cypress-io/github-action` attempts to cache and restore the Cypress binary. Any such …
=> docs: recommend CYPRESS_INSTALL_BINARY=0 for cypress/included Docker image

.github/workflows/example-docker.yml
[.github/workflows/example-docker.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-docker.yml) uses
- [cypress/browsers:node-20.5.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1](https://hub.docker.com/layers/cypress/browsers/node-20.5.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1/images/sha256-fdfca094938a3f97f82e57f209d494968b4f46e36c74efd2adca91a69aedc8ef) published on Sep 1, 2023.
This is outdated.
update the [cypress/browsers Docker image](https://hub.docker.com/r/cypress/browsers) in [.github/workflows/example-docker.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-docker.yml) to
- [cypress/browsers:node-20.14.0-chrome-126.0.6478.114-1-ff-127.0.1-edge-126.0.2592.61-1] …
=> test(deps): update example-docker image version to node-20.14.0

.github/workflows/main.yml
The [.github/workflows/main.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/main.yml) workflow is intended to run with the same Node.js version as defined in https://github.com/actions/runner/blob/main/src/Misc/externals.sh in order to provide a representative CI test.
The workflow currently uses Node.js `20.8.1`
https://github.com/cypress-io/github-action/blob/76647aab959ed8c5508c2a310420a36bb9bf3157/.github/workflows/main.yml#L21
whereas the GitHub runner has been updated to use `NODE20_VERSION="20.13.1"` in the meantime
https://github.com/actions/runner/blob/2a7f327d93fb79326c974f4858ce62c3b81c580a/src/Misc/externals.sh#L11
Update Node.js in [.github/workflows/main.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/main.yml) …
=> ci(deps): update main workflow node.js to 20.13.1

dist/index.js, examples/install-command/package.json, examples/install-command/yarn.lock, examples/install-only/package-lock.json, examples/install-only/package.json, examples/wait-on/package-lock.json, examples/wait-on/package.json, package-lock.json, package.json
- supersedes failed PR https://github.com/cypress-io/github-action/pull/1223
- Renovate PR https://github.com/cypress-io/github-action/pull/525 attempts to update [debug](https://github.com/debug-js/debug) from `4.3.4` to [4.3.6](https://github.com/debug-js/debug/releases/tag/4.3.6) in the root [package.json](https://github.com/cypress-io/github-action/blob/master/package.json). This fails because Renovate does not re-build the action, leading to a mismatch.
- Renovate does not update [debug](https://github.com/debug-js/debug) in the [examples](https://github.com/cypress-io/github-action/tree/master/examples) directories
Using Node.js `20.15.1`.
Update all instances of [debug](https://github.com/debug-js/debug) in the repo from `4.3.4` to …
=> fix(deps): update debug to 4.3.6

package.json
[package.json](https://github.com/cypress-io/github-action/blob/master/package.json) specifies an invalid protocol for the `repository.url` key.
https://github.com/cypress-io/github-action/blob/257570a2f3389e224be9630256c77777dcbb99ae/package.json#L20-L23
Valid protocols, as listed in the [Git URLs as Dependencies](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#git-urls-as-dependencies) npm documentation section, are defined as follows:
> `<protocol>` is one of `git`, `git+ssh`, `git+http`, `git+https`, or `git+file`.
Using Node.js `20.16.0` LTS, execute the following in root of repo:
```shell
npm pkg fix
```
Since this repo is not published as an npm package, no new version needs to be created.
=> chore: correct package.json repository.url protocol to git+https

.github/workflows/example-basic-pnpm.yml
Several jobs in the workflow [.github/workflows/example-basic-pnpm.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic-pnpm.yml) are repeated with the only difference being the operating system:
- `ubuntu-20.04`
- `ubuntu-22.04`
- `windows-latest`
- `macos-latest`
The final job `basic-pnpm-without-binary-install` is proof that issue https://github.com/cypress-io/github-action/issues/327 from 2021 was resolved. This job is redundant, since it was copied from [.github/workflows/example-basic.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic.yml) and it does not correspond to an actual full use-case, since no tests are run.
The jobs use `npx` which is not a native `pnpm` command.
1. Convert the workflow into …
=> test: convert pnpm workflow to os matrix

.github/workflows/example-basic-pnpm.yml, README.md
- resolves issue https://github.com/cypress-io/github-action/issues/1227 for non-workspace configuration
- PR https://github.com/cypress-io/github-action/pull/1188 removed pnpm caching due to reliability issues.
- The enhancement request https://github.com/cypress-io/github-action/issues/1044 remains open and at this time there is no native pnpm caching implemented in `cypress-io/github-action`.
- Lack of pnpm caching can cause a performance impact on workflows, negatively affecting the usability of `cypress-io/github-action`.
[pnpm Continuous Integration > GitHub Actions](https://pnpm.io/continuous-integration#github-actions) documentation recommends installing [pnpm](https://pnpm.io/) with [pnpm/action-setup](https://github.com/pnpm/action-setup) and caching pnpm with GitHub's …
=> test: implement example pnpm workflow caching

examples/component-tests/package-lock.json, examples/component-tests/package.json
- Closes #1081
The prerequisite for Cypress support of Component testing using vite v5 is [cypress@13.10.0](https://docs.cypress.io/guides/references/changelog#13-10-0), released May 21, 2024, or above.
[examples/component-tests](https://github.com/cypress-io/github-action/tree/master/examples/component-tests) is updated to
- [vite@5.3.3](https://github.com/vitejs/vite/releases/tag/v5.3.3)
- [@vitejs/plugin-react@4.3.1](https://github.com/vitejs/vite-plugin-react/releases/tag/v4.3.1)
```shell
cd examples/component-tests
npm ci
npm test
```
- Vite [Migration from v4](https://vitejs.dev/guide/migration.html)
- Issue https://github.com/cypress-io/cypress/issues/29557 also affects this example
=> test(deps): update examples/component-tests to vite v5

examples/config/package-lock.json
Dependabot reports alert [Server-Side Request Forgery in axios](https://github.com/advisories/GHSA-8hc4-vh64-cxmj) for [examples/config/package-lock.json](https://github.com/cypress-io/github-action/blob/master/examples/config/package-lock.json).
[axios](https://www.npmjs.com/package/axios) is a transient dependency of
https://github.com/cypress-io/github-action/blob/a08087f53f35fbade998de761fa13e4d83479306/examples/config/package.json#L17
Resolve the vulnerability with `npm audit fix` which updates `axios` to `1.7.4`.
- See https://github.com/jeffbski/wait-on/issues/159
=> chore(deps): update axios to 1.7.4

dist/index.js, examples/webpack/package-lock.json, package-lock.json
`npm audit` reports
```text
micromatch  <4.0.8
Severity: moderate
Regular Expression Denial of Service (ReDoS) in micromatch - https://github.com/advisories/GHSA-952p-6rrq-rcjv
```
Execute
```shell
npm audit fix
```
- in root of [repo](https://github.com/cypress-io/github-action)
- in [examples/webpack](https://github.com/cypress-io/github-action/tree/master/examples/webpack)
Due to `micromatch` also being used in the action code (not just in an `examples` directory) an update results in a patch release of the action.
```text
└─┬ find-yarn-workspace-root@2.0.0
└── micromatch@4.0.8
```
=> fix(deps): update micromatch to 4.0.8

examples/webpack/package-lock.json, examples/webpack/package.json
`npm audit` and Dependabot report a moderate severity vulnerability in [examples/webpack](https://github.com/cypress-io/github-action/tree/master/examples/webpack) using [webpack@5.91.0](https://github.com/webpack/webpack/releases/tag/v5.91.0)
```text
webpack  <5.94.0
Severity: moderate
Webpack's AutoPublicPathRuntimeModule has a DOM Clobbering Gadget that leads to XSS - https://github.com/advisories/GHSA-4vvj-4cpr-p986
```
Update [examples/webpack](https://github.com/cypress-io/github-action/tree/master/examples/webpack) to [webpack@5.94.0](https://github.com/webpack/webpack/releases/tag/v5.94.0)
=> chore(deps): update webpack to 5.94.0

README.md
The npm [debug](https://www.npmjs.com/package/debug) module's source repo moved:
- from https://github.com/visionmedia/debug
- to https://github.com/debug-js/debug
See release notes [debug@4.3.3](https://github.com/debug-js/debug/releases/tag/4.3.3).
Replace the link above in the [README > Debugging](https://github.com/cypress-io/github-action/blob/master/README.md#debugging) section according to the repository migration.
=> docs: update link to debug-js/debug repo

dist/index.js, package-lock.json, package.json
- supersedes PR https://github.com/cypress-io/github-action/pull/1250
- npm module [debug](https://www.npmjs.com/package/debug) has released a new version [debug@4.3.7](https://github.com/debug-js/debug/releases/tag/4.3.7).
- Renovate attempted to update in PR https://github.com/cypress-io/github-action/pull/1250 however this fails in CI because the action needs to be re-built.
- Update to [debug@4.3.7](https://github.com/debug-js/debug/releases/tag/4.3.7) and re-build the action.
There is no functional change to `debug`, only a reformat of one line of code in the [ms](https://www.npmjs.com/package/ms) npm module which was published 4 years ago and has only now been merged into a new `debug` release.
=> fix(deps): update debug to 4.3.7

examples/config/package-lock.json, examples/config/package.json, examples/start-and-pnpm-workspaces/package.json, examples/start-and-pnpm-workspaces/pnpm-lock.yaml, examples/start-and-yarn-workspaces/package.json, examples/start-and-yarn-workspaces/yarn.lock, examples/start/package-lock.json, examples/start/package.json
- Closes https://github.com/cypress-io/github-action/issues/1254
The following example directories report high severity vulnerabilities due to their transient dependency usage of `path-to-regexp@2.2.1`:
Check with `npm audit`:
-  [examples/config](https://github.com/cypress-io/github-action/tree/master/examples/config)
-  [examples/start](https://github.com/cypress-io/github-action/tree/master/examples/start)
Check with `pnpm audit`:
- [examples/start-and-pnpm-workspaces/packages](https://github.com/cypress-io/github-action/tree/master/examples/start-and-pnpm-workspaces/packages)
`yarn audit` shows no issue, however Dependabot reports the vulnerability:
- [examples/start-and-yarn-workspaces/packages](https://github.com/cypress-io/github-action/tree/master/examples/start-and-yarn-workspaces …
=> chore(deps): update path-to-regexp to 3.3.0

README.md
[README > Debugging > Logs from the test runner](https://github.com/cypress-io/github-action/blob/master/README.md#logs-from-the-test-runner) explains only how to use `DEBUG: 'cypress:*'` without any information about selectively collecting Cypress debug logs.
Add a reference to https://on.cypress.io/troubleshooting#Log-sources
=> docs: add cypress debug log sources reference

examples/config/package-lock.json, examples/config/package.json, examples/start-and-pnpm-workspaces/packages/workspace-1/package.json, examples/start-and-pnpm-workspaces/packages/workspace-2/package.json, examples/start-and-pnpm-workspaces/pnpm-lock.yaml, examples/start-and-yarn-workspaces/workspace-1/package.json, examples/start-and-yarn-workspaces/workspace-2/package.json, examples/start-and-yarn-workspaces/yarn.lock, examples/start/package-lock.json, examples/start/package.json
The following example directories are using [serve@14.2.1](https://github.com/vercel/serve/releases/tag/14.2.1):
- [examples/config](https://github.com/cypress-io/github-action/tree/master/examples/config)
- [examples/start](https://github.com/cypress-io/github-action/tree/master/examples/start)
- [examples/start-and-pnpm-workspaces/packages/workspace-1](https://github.com/cypress-io/github-action/tree/master/examples/start-and-pnpm-workspaces/packages/workspace-1)
- [examples/start-and-pnpm-workspaces/packages/workspace-2](https://github.com/cypress-io/github-action/tree/master/examples/start-and-pnpm-workspaces/packages/workspace-2)
- [examples/start-and-yarn-workspaces/packages/workspace-1](https://github.com/cypress-io/github-action/tree/master/examples/start-and-yarn-workspaces/packag …
=> chore(deps): update serve to 14.2.3

examples/webpack/package-lock.json
`npm audit` reports
> 5 vulnerabilities (2 moderate, 3 high)
in [examples/webpack](https://github.com/cypress-io/github-action/tree/master/examples/webpack)
```text
$ npm audit
body-parser  <1.20.3
Severity: high
body-parser vulnerable to denial of service when url encoding is enabled - https://github.com/advisories/GHSA-qwcr-r2fm-qrc7
fix available via `npm audit fix`
node_modules/body-parser
express  <=4.19.2 || 5.0.0-alpha.1 - 5.0.0-beta.3
Depends on vulnerable versions of body-parser
Depends on vulnerable versions of path-to-regexp
Depends on vulnerable versions of send
Depends on vulnerable versions of serve-static
node_modules/express
path-to-regexp  <0.1.10
Severity: high
path-to-regexp outputs backtracking regular expressions - https://github.com/advisories/GHSA-9wv6-86v2-598j
fix …
```
=> chore(deps): update examples/webpack

.github/workflows/example-debug.yml
The workflow [.github/workflows/example-debug.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-debug.yml) only demonstrates using the environment variable setting 
`DEBUG: '@cypress/github-action'`
It does not demonstrate 
`DEBUG: 'cypress:*'` 
to show debug logs of Cypress.
Add a job to [.github/workflows/example-debug.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-debug.yml) to demonstrate `DEBUG: 'cypress:*'`.
=> test: add cypress debug to example-debug workflow

examples/component-tests/package-lock.json, examples/component-tests/package.json, examples/wait-on-vite/package-lock.json, examples/wait-on-vite/package.json
`npm audit` reports a moderate severity vulnerability in [examples/component-tests](https://github.com/cypress-io/github-action/tree/master/examples/component-tests)
```text
vite  5.3.0 - 5.3.5
Severity: moderate
Vite DOM Clobbering gadget found in vite bundled scripts that leads to XSS - https://github.com/advisories/GHSA-64vr-g452-qvp3
Vite's `server.fs.deny` is bypassed when using `?import&raw` - https://github.com/advisories/GHSA-9cwx-2883-4wfx
```
and similarly in [examples/wait-on-vite](https://github.com/cypress-io/github-action/tree/master/examples/wait-on-vite)
```text
vite  5.0.0 - 5.2.13
Severity: moderate
Vite DOM Clobbering gadget found in vite bundled scripts that leads to XSS - https://github.com/advisories/GHSA-64vr-g452-qvp3
Vite's `server.fs.deny` is bypassed when using …
```
=> chore(deps): update vite to 5.4.6

examples/nextjs/package-lock.json, examples/nextjs/package.json
`npm audit` reports a high severity vulnerability in [examples/nextjs](https://github.com/cypress-io/github-action/tree/master/examples/nextjs)
```text
next  14.0.0 - 14.2.9
Severity: high
Next.js Cache Poisoning - https://github.com/advisories/GHSA-gp8f-8m3g-qvj9
```
Update to [next@14.2.12](https://github.com/vercel/next.js/releases/tag/v14.2.12) in [examples/nextjs](https://github.com/cypress-io/github-action/tree/master/examples/nextjs).
=> chore(deps): update next to 14.2.12

.github/workflows/example-basic.yml, .github/workflows/example-debug.yml
The workflow [.github/workflows/example-debug.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-debug.yml) does not demonstrate debugging installation of the Cypress binary.
Add a job to [.github/workflows/example-debug.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-debug.yml) to demonstrate separation of Cypress npm module and Cypress binary installations using `DEBUG: 'cypress:cli*'`.
Remove the related job `basic-without-binary-install` from [.github/workflows/example-basic.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic.yml) since it is now effectively moved to [.github/workflows/example-debug.yml](https://github.com/cypress-io/github-action/blob/master/.github/work …
=> test: add binary install debug to example-debug workflow

examples/component-tests/package-lock.json, examples/wait-on-vite/package-lock.json
`npm audit` reports a high severity vulnerability in
- [examples/component-tests](https://github.com/cypress-io/github-action/tree/master/examples/component-tests) and
```text
rollup  4.0.0 - 4.22.3
Severity: high
DOM Clobbering Gadget found in rollup bundled scripts that leads to XSS - https://github.com/advisories/GHSA-gcx4-mw62-g8wm
```
Update transient dependency to [rollup@4.22.4](https://github.com/rollup/rollup/releases/tag/v4.22.4) in
using `npm audit fix`.
=> chore(deps): update rollup to 4.22.4

.github/workflows/example-basic.yml
The workflow [.github/workflows/example-basic.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic.yml) is refactored as follows:
- The workflow is converted to use a matrix of operating systems for clarity
- `ubuntu-24.04` is added
- `latest` operating systems are pinned to concrete versions for stability:
- `windows-latest` changed to [windows-2022](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md) (Windows Server 2022)
- `macos-latest` changed to [macos-14](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md) (macOS 14 Arm64)
=> ci: rework example-basic

README.md
The [README > Debugging waiting for URL to respond](https://github.com/cypress-io/github-action/blob/master/README.md#debugging-waiting-for-url-to-respond) contains an example:
```
$ node src/ping-cli.js https://example.cypress.io
pinging url https://example.cypress.io for 30 seconds
::debug::pinging https://example.cypress.io has finished ok
```
where the last line of the example is incorrect.
Without debugging enabled, the output under Node.js `v20.18.0` LTS appears as:
```text
$ node src/ping-cli.js https://example.cypress.io
pinging url https://example.cypress.io for 30 seconds
```
With debugging enabled, the output is as follows:
```text
$ DEBUG='@cypress/github-action' node src/ping-cli.js https://example.cypress.io
pinging url https://example.cypress.io for 30 seconds …
```
=> docs: correct and extend ping debug instructions

examples/config/package-lock.json, examples/config/package.json, examples/start-and-pnpm-workspaces/package.json, examples/start-and-pnpm-workspaces/packages/workspace-1/package.json, examples/start-and-pnpm-workspaces/packages/workspace-2/package.json, examples/start-and-pnpm-workspaces/pnpm-lock.yaml, examples/start-and-yarn-workspaces/package.json, examples/start-and-yarn-workspaces/workspace-1/package.json, examples/start-and-yarn-workspaces/workspace-2/package.json, examples/start-and-yarn-workspaces/yarn.lock, examples/start/package-lock.json, examples/start/package.json
The following example directories are using [serve@14.2.3](https://github.com/vercel/serve/releases/tag/14.2.3):
- [examples/config](https://github.com/cypress-io/github-action/tree/master/examples/config)
- [examples/start](https://github.com/cypress-io/github-action/tree/master/examples/start)
- [examples/start-and-pnpm-workspaces/packages/workspace-1](https://github.com/cypress-io/github-action/tree/master/examples/start-and-pnpm-workspaces/packages/workspace-1)
- [examples/start-and-pnpm-workspaces/packages/workspace-2](https://github.com/cypress-io/github-action/tree/master/examples/start-and-pnpm-workspaces/packages/workspace-2)
- [examples/start-and-yarn-workspaces/packages/workspace-1](https://github.com/cypress-io/github-action/tree/master/examples/start-and-yarn-workspaces/packag …
=> chore(deps): update serve to 14.2.4

.github/workflows/example-node-versions.yml, README.md
[Node.js 23.0.0](https://nodejs.org/en/blog/release/v23.0.0) was released on Oct 16, 2024.
This PR adds Node.js `23` to the matrix of tested nodes under [.github/workflows/example-node-versions.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-node-versions.yml), to the [README](https://github.com/cypress-io/github-action/blob/master/README.md) examples and to the [README > Node.js > Support](https://github.com/cypress-io/github-action/blob/master/README.md#support) section.
=> tests(deps): add node.js 23 (current) to tests

README.md
- closes https://github.com/cypress-io/github-action/issues/1285
Due to restructuring on https://docs.cypress.io running
```shell
npm run check:markdown
```
results in a report of 2 broken links in the [README](https://github.com/cypress-io/github-action/blob/master/README.md#specify-auto-cancel-after-failures) document:
[✖] https://docs.cypress.io/guides/cloud/smart-orchestration#Auto-Cancellation → Status: 404
[✖] https://on.cypress.io/guides/cloud/smart-orchestration/ → Status: 404
Update Smart Orchestration links according to current structure on https://docs.cypress.io.
Execute the following and confirm that no link issues are reported.
```shell
npm run check:markdown
```
=> docs: fix cypress cloud smart-orchestration links

dist/index.js, package-lock.json, package.json
Supersedes Renovate's failed:
- https://github.com/cypress-io/github-action/pull/1274
- https://github.com/cypress-io/github-action/pull/1292
Executing `npm ci` locally produces the warning:
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
Update
- from `@actions/core@1.10.0` to `@actions/core@1.11.1` - see [@actions/core Releases](https://github.com/actions/toolkit/blob/main/packages/core/RELEASES.md)
- from `@actions/cache@3.2.1` to `@actions/cache@3.3.0` - see [@actions/cache Releases](https://github.com/actions/toolkit/blob/main/packages/cache/RELEASES.md)
Execute the following and confirm no `uuid` deprecation …
=> fix(deps): update @actions/toolkit

.github/workflows/example-docker.yml
With the release of [Node.js v22.11.0](https://nodejs.org/en/blog/release/v22.11.0) (codename 'Jod') the Node.js Long Term Support (LTS) version moved from `v20` to `v22`.
The example workflow
- [.github/workflows/example-docker.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-docker.yml)
currently demonstrates using the Cypress Docker image:
`cypress/browsers:node-20.14.0-chrome-126.0.6478.114-1-ff-127.0.1-edge-126.0.2592.61-1`
This image includes Node.js `20.14.0` which is now in the [Node.js category Maintenance LTS](https://github.com/nodejs/release#release-schedule).
Update Docker example workflow to use a Cypress Docker image built with the Active LTS version Node.js `v22.11.0`:
`cypress/browsers:node-22.11.0-chrome-130.0.6723.69-1-ff-132.0-edge- …
=> tests(deps): update docker example node.js to 22.11.0

.github/workflows/example-basic-pnpm.yml, README.md
With the release of [Node.js v22.11.0](https://nodejs.org/en/blog/release/v22.11.0) (codename 'Jod') the Node.js Long Term Support (LTS) version moved from `v20` to `v22`.
Update workflow usage to
```yml
node-version: 22
```
in
- [README > pnpm](https://github.com/cypress-io/github-action/blob/master/README.md#pnpm)
=> tests(deps): update pnpm example node.js to 22

README.md
The [README > More Information](https://github.com/cypress-io/github-action/blob/master/README.md#more-information) section is made up of three links:
1. blog post [Drastically Simplify Testing on CI with Cypress GitHub Action](https://www.cypress.io/blog/drastically-simplify-your-testing-with-cypress-github-action) from Nov 2019
2. blog post [Test the Preview Vercel Deploys](https://glebbahmutov.com/blog/develop-preview-test/) from Aug 2020
3. link to GitHub Actions documentation [Creating actions](https://docs.github.com/en/actions/creating-actions) which now redirects to a renamed section [Sharing automations](https://docs.github.com/en/actions/sharing-automations).
The two blog posts are based on now-unsupported legacy versions.
The remaining link to a section of the GitHub Actions …
=> docs: remove section "More Information"

README.md
The [README > Manual trigger](https://github.com/cypress-io/github-action/blob/master/README.md#manual-trigger) section contains a link to a YouTube Video https://www.youtube.com/watch?v=4TeSOj2Iy_Q posted on Feb 6, 2021.
The video explains how to use `workflow_dispatch` on a legacy configuration of Cypress.
Replace the link to the outdated YouTube Video https://www.youtube.com/watch?v=4TeSOj2Iy_Q with a link to the GitHub Actions documentation [Manually running a workflow](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/manually-running-a-workflow).
Add the information that all examples are pre-configured to run on the `workflow_dispatch` event.
=> docs: update "Manual trigger" section

README.md
Links in the [README > Usage](https://github.com/cypress-io/github-action/blob/master/README.md#usage) section, which refer to bookmarks in the same document, are using absolute URLs instead of relative ones.
This can cause the wrong information to be displayed when the README is accessed in a branch which is not the default `master` branch.
An example is https://github.com/cypress-io/github-action#custom-install-command
Convert absolute URLs to relative ones in the [README.md](https://github.com/cypress-io/github-action/blob/master/README.md) document, for links which refer to bookmarks in the README document itself.
For example, reduce
`https://github.com/cypress-io/github-action#custom-install-command`
to
`#custom-install-command`
```shell
npm ci
npx markdown-link-check README.md
```
=> docs: make README bookmark internal links relative

README.md
- relates to issue https://github.com/cypress-io/github-action/issues/1308
The README section [Custom install command](https://github.com/cypress-io/github-action/blob/master/README.md#custom-install-command) shows only the example `install-command: yarn --frozen-lockfile --silent` as a slightly modified Yarn Classic v1 install command.
It does not specify that the action expects to find a lock file.
Link to the [Notes > Installation](https://github.com/cypress-io/github-action/blob/master/README.md#installation) section which explains the relationship between lock files and the default installation command that the action uses.
Add the information that if no lock file is provided, then the workflow must ensure that dependencies are installed prior to using the action, and that the action …
=> docs: add install-command lock file prerequisite

README.md
Some links to https://on.cypress.io/, used in the [README](https://github.com/cypress-io/github-action/blob/master/README.md) document, no longer bring up the intended content.
The site https://docs.cypress.io/ was restructured in October 2024 and the use of https://on.cypress.io/ links has not redirected all links to approprate replacement content.
In the [README](https://github.com/cypress-io/github-action/blob/master/README.md) document, replace links to https://on.cypress.io/ that are not showing required content, using either other https://on.cypress.io/ links or instead https://docs.cypress.io/ with appropriate pages and bookmarks.
```shell
npm ci
npx markdown-link-check README.md
```
=> docs: fix readme links for cypress documentation restructuring

examples/basic-pnpm/pnpm-lock.yaml, examples/basic/package-lock.json, examples/browser/package-lock.json, examples/component-tests/package-lock.json, examples/config/package-lock.json, examples/custom-command/package-lock.json, examples/env/package-lock.json, examples/install-command/yarn.lock, examples/install-only/package-lock.json, examples/nextjs/package-lock.json, examples/node-versions/package-lock.json, examples/quiet/package-lock.json, examples/recording/package-lock.json, examples/start-and-pnpm-workspaces/pnpm-lock.yaml, examples/start-and-yarn-workspaces/yarn.lock, examples/start/package-lock.json, examples/wait-on-vite/package-lock.json, examples/wait-on/package-lock.json, examples/webpack/package-lock.json, examples/yarn-classic/yarn.lock, examples/yarn-modern-pnp/yarn.lock, examples/yarn-modern/yarn.lock
Dependabot reports a high severity vulnerability [CVE-2024-21538](https://github.com/advisories/GHSA-3xgq-45jj-v275) in [cross-spawn](https://www.npmjs.com/package/cross-spawn) `>= 7.0.0, < 7.0.5`, patched in [cross-spawn@7.0.5](https://github.com/moxystudio/node-cross-spawn/tree/v7.0.5).
[cross-spawn](https://www.npmjs.com/package/cross-spawn) is a transient dependency of [cypress](https://www.npmjs.com/package/cypress)
```text
$ npm ls cross-spawn
example-basic@1.0.0
└─┬ cypress@13.16.0
└─┬ execa@4.1.0
└── cross-spawn@7.0.3
```
where [exaca@4.1.0](https://github.com/sindresorhus/execa/releases/tag/v4.1.0) requires `cross-spawn@^7.0.0`
Update all usage of `cross-spawn` to [cross-spawn@7.0.6](https://github.com/moxystudio/node-cross-spawn/tree/v7.0.6) (current `latest`).
=> tests(deps): update cross-spawn to 7.0.6

examples/wait-on-vite/package-lock.json, examples/wait-on-vite/package.json
The E2E [examples/wait-on-vite](https://github.com/cypress-io/github-action/tree/master/examples/wait-on-vite) currently uses [vite@5.4.6](https://github.com/vitejs/vite/releases/tag/v5.4.6), released Sep 16, 2024.
The latest version is [vite@6.0.0](https://github.com/vitejs/vite/releases/tag/v6.0.0) released Nov 26, 2024
Update [examples/wait-on-vite](https://github.com/cypress-io/github-action/tree/master/examples/wait-on-vite) to use the latest version [vite@6.0.0](https://github.com/vitejs/vite/releases/tag/v6.0.0).
```shell
cd examples/wait-on-vite
npm ci
npm run dev
```
In a separate terminal window, execute:
```shell
npm test
```
=> test(deps): update wait-on-vite to vite v6

.github/workflows/example-basic.yml
[Ubuntu 20 image is closing down](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#ubuntu-20-image-is-closing-down) in GitHub Actions.
The [blog post of Dec 5, 2024](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#ubuntu-20-image-is-closing-down) announces:
> We are beginning the process of closing down the Ubuntu 20 hosted runner image, following our N-1 [OS support policy](https://github.com/actions/runner-images?tab=readme-ov-file#software-and-image-support). This image will be fully retired by April 1, 2025. We recommend updating workflows to use ubuntu-22.04, or ubuntu-24.04.
The workflow [.github/workflows/example-basic.yml](https://github.com/cypress-io/github-a …
=> ci: remove retiring ubuntu-20.04 from testing

dist/index.js, package-lock.json, package.json
- supersedes PR https://github.com/cypress-io/github-action/pull/1326
- npm module [debug](https://www.npmjs.com/package/debug) has released a new version [debug@4.4.0](https://github.com/debug-js/debug/releases/tag/4.4.0).
- Renovate attempted to update in PR https://github.com/cypress-io/github-action/pull/1326 however this fails in CI because the action needs to be re-built - see https://github.com/cypress-io/github-action/issues/1252.
- Update to [debug@4.4.0](https://github.com/debug-js/debug/releases/tag/4.4.0) and re-build the action.
=> fix(deps): update debug to 4.4.0

examples/component-tests/package-lock.json, examples/nextjs/package-lock.json, examples/nextjs/package.json, examples/wait-on-vite/package-lock.json, examples/webpack/package-lock.json, examples/webpack/package.json
Dependabot and `npm audit` are reporting vulnerabilities in examples.
| `examples`                                  | Vulnerability  | Package          | Need      |
| ------------------------------------------- | -------------- | ---------------- | --------- |
| `nextjs`                                    | CVE-2024-51479 | `next`           | `14.2.15` |
| `wait-on-vite`, `nextjs`, `component-tests` | CVE-2024-55565 | `nanoid`         | `3.3.8`   |
| `webpack`                                   | CVE-2024-52798 | `path-to-regexp` | `0.1.12`  |
Update to:
- [nanoid@3.3.8](https://github.com/ai/nanoid/releases/tag/3.3.8)
- [next@14.2.20](https://github.com/vercel/next.js/releases/tag/v14.2.20)
- [webpack-dev-server@5.2.0](https://github.com/webpack/webpack-dev-server/releases/tag/v5.2.0)
in …
=> test(deps): mitigate vulnerabilities in examples

.github/workflows/example-basic-pnpm.yml, .github/workflows/example-start-and-pnpm-workspaces.yml, README.md, examples/basic-pnpm/package.json, examples/start-and-pnpm-workspaces/package.json
This PR updates the version of pnpm used in the workflows:
- [.github/workflows/example-start-and-pnpm-workspaces.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-start-and-pnpm-workspaces.yml)
and in the
- [README > pnpm](https://github.com/cypress-io/github-action/blob/master/README.md#pnpm) section
from pnpm `9` to pnpm `10`.
[pnpm@10.0.0](https://github.com/pnpm/pnpm/releases/tag/v10.0.0) was released on Jan 7, 2025.
Additionally, the `package.json` files for
- …
=> test(deps): update examples to pnpm 10

dist/index.js, package-lock.json, package.json
- supersedes PR https://github.com/cypress-io/github-action/pull/1328
- GitHub has released a new version of the npm module [@actions/cache](https://www.npmjs.com/package/@actions/cache) with the deprecation notice:
> The new service will gradually roll out as of February 1st, 2025. The legacy service will also be sunset on the same date. Changes in this release are fully backward compatible.
>
> All previous versions of this package will be deprecated. We recommend upgrading to version 4.0.0 as soon as possible before February 1st, 2025.
The new version is [@actions/cache@4.0.0](https://github.com/actions/toolkit/releases/tag/%40actions%2Fcache%404.0.0)
See also [@actions/cache Package Deprecation Notice. Upgrade to the latest 4.0.0 or higher before February 1st …
=> fix(deps): update @actions/cache to 4.0.0

examples/component-tests/package-lock.json, examples/component-tests/package.json
The [examples/component-tests](https://github.com/cypress-io/github-action/tree/master/examples/component-tests) currently uses [vite@5.4.6](https://github.com/vitejs/vite/releases/tag/v5.4.6), released Sep 16, 2024. This is not the latest version.
Update [examples/component-tests](https://github.com/cypress-io/github-action/tree/master/examples/component-tests) to `vite@latest` which is currently [vite@6.0.8](https://github.com/vitejs/vite/releases/tag/v6.0.8), released Jan 20, 2025, including updating other dependencies in the project.
```shell
git clone https://github.com/cypress-io/github-action
cd github-action
git clean -xfd # if repeating
cd examples/component-tests
npm test
```
The test should pass.
Disregard any warning:
> The CJS build of Vite's Node API is deprecated. See …
=> test(deps): update examples/component-tests to vite 6.0.8

dist/index.js, package-lock.json
Dependabot reports the vulnerability [CVE-2025-22150](https://github.com/advisories/GHSA-c76h-2ccp-4975) with Moderate severity in the transient dependency [undici@5.28.4](https://github.com/nodejs/undici/releases/tag/v5.28.4).
```text
$ npm ls undici
@cypress/github-action
└─┬ @actions/cache@4.0.0
└─┬ @actions/http-client@2.2.3
└── undici@5.28.4
```
Update to [undici@5.28.5](https://github.com/nodejs/undici/releases/tag/v5.28.5) by removing [undici@5.28.4](https://github.com/nodejs/undici/releases/tag/v5.28.4) from `package-lock.json`, deleting `node_modules` and running `npm install`.
This resolves the moderate severity vulnerability [CVE-2025-22150](https://github.com/advisories/GHSA-c76h-2ccp-4975).
- The vulnerability has also been reported in …
=> fix(deps): update undici to 5.28.5

examples/component-tests/package-lock.json, examples/component-tests/package.json, examples/wait-on-vite/package-lock.json, examples/wait-on-vite/package.json
Dependabot reports the vulnerability [CVE-2025-24010](https://github.com/advisories/GHSA-vg6x-rcgg-rjx6) with Moderate severity:
- in [vite@6.0.8](https://github.com/vitejs/vite/releases/tag/v6.0.8) used in [examples/component-tests](https://github.com/cypress-io/github-action/tree/master/examples/component-tests)
- in [vite@6.0.0](https://github.com/vitejs/vite/releases/tag/v6.0.0) used in [examples/wait-on-vite](https://github.com/cypress-io/github-action/tree/master/examples/wait-on-vite)
Update `vite` to [vite@6.0.11](https://github.com/vitejs/vite/releases/tag/v6.0.11) in the above examples.
=> test(deps): update vite to 6.0.11 in examples

README.md, examples/basic-pnpm/.npmrc, examples/start-and-pnpm-workspaces/.npmrc
- closes https://github.com/cypress-io/github-action/issues/1363
Caching the pnpm store with default settings leads pnpm to skip running the Cypress postinstall script if the Cypress npm module is already cached. This may lead to failures if the Cypress cache is lost or purged.
Workflows should never depend on the presence of particular caches. They should always be resilient to missing caches.
Add [side-effects-cache=false](https://pnpm.io/npmrc#side-effects-cache) using an `.npmrc` file to the:
- [README > pnpm](https://github.com/cypress-io/github-action/blob/master/README.md#pnpm) section
- [examples/basic-pnpm](https://github.com/cypress-io/github-action/tree/master/examples/basic-pnpm) project
- [examples/start-and-pnpm-workspaces](https://github.com/cypress-io/github-action/tree/mas …
=> test: set side-effects-cache=false for pnpm

dist/index.js, package-lock.json, package.json
Dependabot reports:
- [CVE-2025-25289](https://github.com/advisories/GHSA-xx4v-prfh-6cgc) for [@octokit/request-errror](https://www.npmjs.com/package/@octokit/request-error) versions >= `1.0.0`, < `5.1.1` needing patched version `5.1.1` and versions >= `6.0.0`, < `6.1.7` needing patched version `6.1.7`
- [CVE-2025-25290](https://github.com/advisories/GHSA-rmvr-2pp2-xj38) for [@octokit/request](https://www.npmjs.com/package/@octokit/request) versions >= `1.0.0`, < `9.2.1` needing patched version `9.2.1`
These are the current dependency hierarchies:
```text
$ npm ls @octokit/request-error
@cypress/github-action@0.0.0-development
└─┬ @octokit/core@4.2.0
├── @octokit/request-error@3.0.2
└─┬ @octokit/request@6.2.2
└── @octokit/request-error@3.0.2 deduped
$ npm ls @octokit/request …
```
=> fix(deps): update @octokit/core to 6.1.4

dist/index.js, src/ping.js
Offline linting shows that the following code line is unused
https://github.com/cypress-io/github-action/blob/8c73325c9895fe38d7846f65923bd6e6cd487137/src/ping.js#L1
Remove `const core = require('@actions/core')` from [src/ping.js](https://github.com/cypress-io/github-action/blob/master/src/ping.js).
=> refactor: remove unused @actions/core from ping.js

eslint.config.mjs, examples/basic-pnpm/cypress.config.js, examples/basic/cypress.config.js, examples/browser/cypress.config.js, examples/config/cypress.config-alternate.js, examples/config/cypress.config.js, examples/custom-command/cypress.config.js, examples/install-command/cypress.config.js, examples/install-only/cypress.config.js, examples/node-versions/cypress.config.js, examples/quiet/cypress.config.js, examples/recording/cypress.config.js, examples/recording/cypress/e2e/spec-a.cy.js, examples/recording/cypress/e2e/spec-b.cy.js, examples/recording/cypress/e2e/spec-c.cy.js, examples/recording/cypress/e2e/spec-d.cy.js, examples/start-and-pnpm-workspaces/packages/workspace-1/cypress.config.js, examples/start-and-pnpm-workspaces/packages/workspace-2/cypress.config.js, examples/start-and-yarn-workspaces/workspace-1/cypress.config.js, examples/start-and-yarn-workspaces/workspace-2/cypress.config.js, examples/start/cypress.config.js, examples/wait-on-vite/cypress.config.js, examples/wait-on/cypress.config.js, examples/webpack/cypress.config.js, examples/yarn-classic/cypress.config.js, examples/yarn-modern-pnp/cypress.config.js, examples/yarn-modern/cypress.config.js, package-lock.json, package.json
- The core ESLint JavaScript linting, added through PR https://github.com/cypress-io/github-action/pull/1370, excludes [examples](https://github.com/cypress-io/github-action/tree/master/examples).
- Remove the linting exclusion from [examples](https://github.com/cypress-io/github-action/tree/master/examples) and limit this to the third-party generated [examples/nextjs/src/app/](https://github.com/cypress-io/github-action/tree/master/examples/nextjs/src/app) directory.
- Add linting using [eslint-plugin-cypress](https://www.npmjs.com/package/eslint-plugin-cypress) using the recommended rules.
- Disable the lint rule [cypress/no-unnecessary-waiting](https://github.com/cypress-io/eslint-plugin-cypress/blob/HEAD/docs/rules/no-unnecessary-waiting.md) applied to …
=> chore: extend linting to cypress examples

.husky/pre-commit, action.yml, package.json
- The core file [action.yml](https://github.com/cypress-io/github-action/blob/master/action.yml) has an inconsistent use of quotes.
- It is not included in the automatic formatting of core action files.
Add [action.yml](https://github.com/cypress-io/github-action/blob/master/action.yml) to
- Script `format`
- [.husky/pre-commit](https://github.com/cypress-io/github-action/blob/master/.husky/pre-commit)
One use of double quotes in [action.yml](https://github.com/cypress-io/github-action/blob/master/action.yml) is automatically corrected to standard single quote usage.
https://github.com/cypress-io/github-action/blob/013dd060a557fd6d28b933ed1c3c53f9f3f1c069/action.yml#L93-L96
https://github.com/cypress-io/github-action/blob/013dd060a557fd6d28b933ed1c3c53f9f3f1c069/.prettierrc.json#L6
Ubuntu …
=> build: automatically format action.yml

README.md
- closes #1377
Added [command-prefix](https://github.com/cypress-io/github-action/blob/master/README.md#command-prefix) to the restrictions for using `resultsUrl` in the [README > Outputs](https://github.com/cypress-io/github-action/blob/master/README.md#outputs) section.
In this case Cypress is not run using the [Cypress Module API](https://docs.cypress.io/app/references/module-api) and therefore `resultsUrl` is not available.
https://github.com/cypress-io/github-action/blob/master/README.md#outputs
=> docs: add resultsurl restriction for command-prefix

.github/workflows/main.yml
- Add `npm run lint` (which executes `npx eslint`) to [.github/workflows/main.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/main.yml)
- Remove `npm run test` which runs the unneeded default script `"test": "echo \"There are no tests :(\""`
=> ci: enable eslint linting

dist/index.js, package-lock.json, package.json
- When jobs are run in parallel, GitHub Actions caching may output annotation warnings in situations which should be considered normal.
- This issue is now mitigated by [@actions/cache@4.0.2](https://github.com/actions/toolkit/blob/main/packages/cache/RELEASES.md#402)
- Update from [@actions/cache@4.0.1](https://github.com/actions/toolkit/blob/main/packages/cache/RELEASES.md#401) to [@actions/cache@4.0.2](https://github.com/actions/toolkit/blob/main/packages/cache/RELEASES.md#402) and re-build the action.
=> fix(deps): update @actions/cache to 4.0.2

examples/browser/cypress.config.js, examples/component-tests/cypress.config.js
[Migrating to Cypress 13.0](https://docs.cypress.io/app/references/migration-guide#Migrating-to-Cypress-130) lists the change that [`video` is set to `false` by default](https://docs.cypress.io/app/references/migration-guide#video-is-set-to-false-by-default).
Two config files in the [examples](https://github.com/cypress-io/github-action/tree/master/examples) directories continue to set:
```js
video: false
```
although this is now a redundant setting.
Remove `video: false` settings from config files in the [examples](https://github.com/cypress-io/github-action/tree/master/examples) directories.
=> test: remove default video: false configuration item

.prettierignore, eslint.config.mjs, examples/browser/cypress.config.js, examples/browser/cypress/e2e/spec.cy.js, examples/component-tests/cypress.config.js, examples/config/cypress.config-alternate.js, examples/config/cypress/e2e/spec-a.cy.js, examples/config/cypress/e2e/spec-b.cy.js, examples/custom-command/index.js, examples/env/cypress.config.js, examples/env/cypress/e2e/spec.cy.js, examples/env/cypress/e2e/without-env.cy.js, examples/nextjs/cypress.config.js, examples/quiet/cypress.config.js, examples/quiet/cypress/e2e/spec.cy.js, examples/wait-on/index.js, examples/wait-on/index2.js, examples/wait-on/index3.js, examples/wait-on/index4.js, examples/webpack/webpack.config.js, package-lock.json, package.json
- [ESLint](https://eslint.org/docs/) is already used to lint JavaScript files (see [eslint.config.mjs](https://github.com/cypress-io/github-action/blob/master/eslint.config.mjs) for configuration).
- JavaScript source files that are part of the core action are already formatted using [Prettier](https://prettier.io/).
- JavaScript source files in the [examples](https://github.com/cypress-io/github-action/tree/master/examples) directory are not yet linted for formatting.
- ESLint offers a consolidated plugin [@stylistic/eslint-plugin](https://eslint.style/) for Stylistic Formatting.
- Add linting using [@stylistic/eslint-plugin](https://eslint.style/) using its [recommended rules](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/packages/eslint-plugin/rules.md) for the …
=> test: extend cypress examples linting to javascript styles

dist/index.js, index.js
When running the action against a non-public GH instance, the api request to determine build-id from Github would fail. 
> Bad Credentials
I believe this is due to the incorrect (public) GH instance being contacted.
The fix uses: 
- the `baseUrl` constuctor option of Octokit: https://github.com/octokit/octokit.js/blob/main/README.md#constructor-options
- the available `GITHUB_API_URL` environment variable: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables#default-environment-variables
=> fix: Use correct baseUrl when running in non-public Github instances

.github/workflows/example-basic-pnpm.yml, .github/workflows/example-basic.yml, .github/workflows/example-chrome.yml, .github/workflows/example-config.yml, .github/workflows/example-custom-ci-build-id.yml, .github/workflows/example-custom-command.yml, .github/workflows/example-env.yml, .github/workflows/example-firefox.yml, .github/workflows/example-install-command.yml, .github/workflows/example-install-only.yml, .github/workflows/example-node-versions.yml, .github/workflows/example-quiet.yml, .github/workflows/example-recording.yml, .github/workflows/example-start-and-pnpm-workspaces.yml, .github/workflows/example-start-and-yarn-workspaces.yml, .github/workflows/example-start.yml, .github/workflows/example-wait-on.yml, .github/workflows/example-webpack.yml, .github/workflows/example-yarn-classic.yml, .github/workflows/example-yarn-modern-pnp.yml, .github/workflows/example-yarn-modern.yml, .prettierignore
- There are no linting or formatting checks carried out on `*.yml` workflow files which are included in the [.github/workflows](https://github.com/cypress-io/github-action/tree/master/.github/workflows) directory.
- [Prettier](https://prettier.io/docs/) supports [YAML](https://yaml.org/) formatting and is available for use in the repo.
To ensure consistent `YAML` workflow source formatting as part of an overall effort to increase linting coverage in the repo:
-Add [.prettierignore](https://github.com/cypress-io/github-action/blob/master/.prettierignore) exceptions for:
- generated `pnpm-lock.yaml` files
- Use Prettier to re-format all `*.yml` workflows in the [.github/workflows](https://github.com/cypress-io/github-action/tree/master/.github/workflows) directory:
```shell
npx prettier …
```
=> test: prettier format example yml workflows

.prettierignore, examples/start-and-pnpm-workspaces/package.json
- There are no linting or formatting checks carried out on `*.json` files which are included in the [.github/workflows](https://github.com/cypress-io/github-action/tree/master/.github/workflows) directory.
- [Prettier](https://prettier.io/docs/) supports [JSON](https://www.json.org/json-en.html) formatting and is available for use in the repo.
To ensure consistent `JSON` source formatting as part of an overall effort to increase linting coverage in the repo:
- Add [.prettierignore](https://github.com/cypress-io/github-action/blob/master/.prettierignore) exceptions for:
- generated `package-lock.json` files
- [renovate.json](https://github.com/cypress-io/github-action/blob/master/renovate.json)
- Use Prettier to check all non-generated `*.json` files in the …
=> test: prettier format example json files

.prettierignore, eslint.config.mjs
For styling consistency with the rest of the repo, [eslint.config.mjs](https://github.com/cypress-io/github-action/blob/master/eslint.config.mjs) should not be linted by Prettier.
- Add [eslint.config.mjs](https://github.com/cypress-io/github-action/blob/master/eslint.config.mjs) to [.prettierignore](https://github.com/cypress-io/github-action/blob/master/.prettierignore)
- Add [eslint.config.mjs](https://github.com/cypress-io/github-action/blob/master/eslint.config.mjs) with [@stylistic/eslint-plugin](https://www.npmjs.com/package/@stylistic/eslint-plugin) to itself
- Use `npx eslint eslint.config.mjs --fix` to fix trailing commas
Execute the following and confirm that no errors are reported or changes suggested:
```shell
git clean -xfd
npm ci
npx eslint
npx prettier eslint.config.mjs …
```
=> ci: self-lint eslint config style

dist/index.js, index.js
Linked to: https://github.com/cypress-io/github-action/pull/1371
Specifically see: https://github.com/cypress-io/github-action/pull/1371#issuecomment-2710086713
In a similar change to the one linked about the Github `baseUrl` parameter is passed into the `Octokit` constructor. This allows for the correct CI Build link to be generated within the Cypress UI.
=> fix: pass baseUrl into Octokit constructor

eslint.config.mjs
Each of the following examples includes a `build` script definition which, if run, generates additional files, including JavaScript `*.js` files:
- [examples/nextjs](https://github.com/cypress-io/github-action/tree/master/examples/nextjs)
ESLint does not respect the `.gitignore` files in the monorepo.
[Including .gitignore Files](https://eslint.org/docs/latest/use/configure/ignore#including-gitignore-files) describes how to use a compatibility utility to work around this restriction, however it is less complicated to use ESLint's global ignore instead, and it requires no …
=> ci: exclude builds from eslint checks

.prettierignore, examples/component-tests/src/components/Stepper.jsx
- React `*.jsx` files are not currently linted. With the exception of the two `Stepper*.jsx` files in [examples/component-tests/src/components](https://github.com/cypress-io/github-action/tree/master/examples/component-tests/src/components) however, all other `*.jsx` source files are scaffolded by `npm create vite` and should not be linted since the content is externally provided.
- The ESLint npm modules [eslint-plugin-react](https://www.npmjs.com/package/eslint-plugin-react) and [@stylistic/eslint-plugin](https://www.npmjs.com/package/@stylistic/eslint-plugin) both fail when attempting to lint [examples/component-tests/src/components](https://github.com/cypress-io/github-action/tree/master/examples/component-tests/src/components). This appears to be a gap in their functionality.
- …
=> test: add jsx linting

.prettierignore
Prettier should not be applied to content created by builds or sourced externally.
Each of the following examples includes a `build` script definition which, if run, generates additional files:
- [examples/nextjs](https://github.com/cypress-io/github-action/tree/master/examples/nextjs)
The [dist](https://github.com/cypress-io/github-action/tree/master/dist) directory also contains only generated files.
Generated by `ncc` through `npm run build`
- [dist](https://github.com/cypress-io/github-action/tree/master/dist)
Scaffolded by Cypress:
- …
=> ci: exclude prettier checks on generated content

.github/workflows/main.yml, CONTRIBUTING.md, package.json
- Previous PRs have made incremental changes to the scope of [Prettier](https://prettier.io/docs/) formatting and checks
- Running `npx prettier . --check` now returns success
- Scripts to run Prettier across the whole repo and in CI are missing
- The use of Prettier is not documented
- Add script
- `format:all` to fix all required formatting with Prettier
- `format:all:check` to check all required formatting with Prettier
- Add instructions to [CONTRIBUTING](https://github.com/cypress-io/github-action/blob/master/CONTRIBUTING.md)
- Add `format:all:check` to [.github/workflows/main.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/main.yml)
On Ubuntu `24.04.2` LTS, Node.js `22.14.0` LTS
```shell
npm ci
npm run format:all:check
```
and confirm the response is: …
=> ci: add overall prettier check to ci

README.md
The table [README > More examples](https://github.com/cypress-io/github-action/blob/master/README.md#more-examples) is excluded from Prettier formatting.
- Remove Prettier exclusion for the [README > More examples](https://github.com/cypress-io/github-action/blob/master/README.md#more-examples)
- Run `npx prettier --write README.md`
=> docs: re-align external repo example table

README.md
Add an explanatory Caching section to the [README](https://github.com/cypress-io/github-action/blob/master/README.md) document, providing a more differentiated description of what is covered by built-in caching and what options are available for pnpm and Yarn Modern.
=> docs: add README caching section

examples/nextjs/package-lock.json, examples/nextjs/package.json
Dependabot reports a critical vulnerability [CVE-2025-29927](https://github.com/advisories/GHSA-f82v-jwr5-mffw) in [examples/nextjs](https://github.com/cypress-io/github-action/tree/master/examples/nextjs) affecting [next](https://www.npmjs.com/package/next) `>= 15.0, < 15.2.3`
In [examples/nextjs](https://github.com/cypress-io/github-action/tree/master/examples/nextjs) update:
| Module                                                   | from                | to                                                                                     |
| -------------------------------------------------------- | ------------------- | -------------------------------------------------------------------------------------- |
| [next](https://www.npmjs.com/package/next)               | `next@15.1.5` …
=> test(deps): update next to 15.2.3

CONTRIBUTING.md
- related to https://github.com/cypress-io/github-action/pull/1143
The example badge in the [CONTRIBUTING > Adding a new example](https://github.com/cypress-io/github-action/blob/master/CONTRIBUTING.md#adding-a-new-example) section shows "no status" instead of the expected "passed" status.
Update the syntax of the `example-chrome` badge in the [CONTRIBUTING > Adding a new example](https://github.com/cypress-io/github-action/blob/master/CONTRIBUTING.md#adding-a-new-example) section to use the current format as already corrected in the [README > Chrome](https://github.com/cypress-io/github-action/blob/master/README.md#chrome) section.
=> docs: fix example status badge in contributing

CONTRIBUTING.md, package.json
- If CI linting finds an ESLinting error in the [.github/workflows/main.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/main.yml) there is no script available to simply correct automatically fixable linting errors.
- There is no mention of ESLinting preparation in the [CONTRIBUTING](https://github.com/cypress-io/github-action/blob/master/CONTRIBUTING.md) document.
- Add a script `lint:fix` to [package.json](https://github.com/cypress-io/github-action/blob/master/package.json) equivalent to running the following (see [eslint options](https://eslint.org/docs/latest/use/command-line-interface#options)):
```shell
npx eslint --fix
```
- Add `lint:fix` to the [CONTRIBUTING > Providing fixes or features](https://github.com/cypress-io/github-action/blob/master/CONTRI …
=> chore: add script lint:fix

dist/index.js, index.js
- follows on from https://github.com/cypress-io/github-action/issues/1408
If Cypress fails to run using the Module API, for instance due to an issue with the Cypress config file, which was the case with issue https://github.com/cypress-io/github-action/issues/1408, no information about the version of Node.js being used is logged.
The action selects the Node.js major version through the setting for [runs.using](https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#runsusing-for-javascript-actions):
`cypress-io/github-action@v6` selects:
https://github.com/cypress-io/github-action/blob/4b97333793ccb3c4885f89f55db569765b48f18c/action.yml#L102-L104
Based on the  [runs.using](https://docs.github.com/en/actions/sharing-automations/creating-act …
=> chore: add debug output of node.js version

examples/component-tests/package-lock.json, examples/component-tests/package.json, examples/wait-on-vite/package-lock.json, examples/wait-on-vite/package.json
Dependabot reports the vulnerability [CVE-2025-31125](https://github.com/advisories/GHSA-4r4m-qw57-chr8) with Moderate severity in [vite@6.2.3](https://github.com/vitejs/vite/releases/tag/v6.2.3) used in:
Update `vite` from [vite@6.2.3](https://github.com/vitejs/vite/releases/tag/v6.2.3) to [vite@6.2.4](https://github.com/vitejs/vite/releases/tag/v6.2.4) in the above examples.
=> test(deps): update vite to 6.2.4 in examples

.github/workflows/example-yarn-modern-pnp.yml, .github/workflows/example-yarn-modern.yml, docs/MAINTENANCE.md, examples/yarn-modern-pnp/README.md, examples/yarn-modern/README.md
The current [Yarn Modern Installation](https://yarnpkg.com/getting-started/install) instructions recommend managing Yarn through Corepack and they now instruct to install Corepack through npm instead of using the version currently still distributed with Node.js. The background is that the Node.js Technical Steering Committee [voted](https://github.com/nodejs/TSC/pull/1697#issuecomment-2737093616) to stop distributing the experimental Corepack with Node.js in the long term.
This affects examples, tests and scripts in the repo related to Yarn Modern.
In the appropriate places add `npm install -g corepack`.
In both the examples:
- [examples/yarn-modern](https://github.com/cypress-io/github-action/tree/master/examples/yarn-modern)
- [examples/yarn-modern-pnp](https://github.com/cypress-io/gith …
=> chore: migrate yarn modern to npm registry corepack

examples/component-tests/package-lock.json, examples/component-tests/package.json, examples/wait-on-vite/package-lock.json, examples/wait-on-vite/package.json
Dependabot reports a moderate severity vulnerability [CVE-2025-31486](https://github.com/advisories/GHSA-xcj6-pq6g-qj4x) in [vite@6.2.4](https://github.com/vitejs/vite/releases/tag/v6.2.4) used in:
Update `vite` from [vite@6.2.4](https://github.com/vitejs/vite/releases/tag/v6.2.4) to [vite@6.2.5](https://github.com/vitejs/vite/releases/tag/v6.2.5) in the above examples.
=> test(deps): update vite to 6.2.5 in examples

examples/basic-pnpm/package.json, examples/basic-pnpm/pnpm-workspace.yaml, examples/start-and-pnpm-workspaces/package.json
The pnpm example projects:
- [examples/start-and-pnpm-workspaces](https://github.com/cypress-io/github-action/tree/master/examples/start-and-pnpm-workspaces)
are configured with `onlyBuiltDependencies` for `cypress` in their respective `package.json` files.
[pnpm@10.5.0](https://github.com/pnpm/pnpm/releases/tag/v10.5.0) moved the default location for this configuration to the `pnpm-workspace.yaml` file.
To align with the pnpm default location for `onlyBuiltDependencies` in the current version of the `pnpm` package manager move `onlyBuiltDependencies` to a corresponding example `pnpm-workspace.yaml` file.
- [examples/basic-pnpm](https://github.com/cypress-io/github-action/tree/master/exampl …
=> test: move pnpm onlyBuiltDependencies to pnpm-workspace.yaml

.github/workflows/example-basic-pnpm.yml, .github/workflows/example-basic.yml
The following workflows use the GitHub Actions runner [windows-2022](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md)
- [.github/workflows/example-basic.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic.yml)
The latest GitHub Actions runner for the Windows operating system is [windows-2025](https://github.com/actions/runner-images/blob/main/images/windows/Windows2025-Readme.md).
Update the workflows
- [.github/workflows/example-basic.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic.yml)
- …
=> ci: use windows-2025 in basic example workflows

.github/workflows/example-basic-pnpm.yml, .github/workflows/example-basic.yml, README.md
The following workflows use the GitHub Actions runner image [macos-14](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md):
- [.github/workflows/example-basic.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic.yml)
GitHub announced the transition of [Windows 2025 and macOS 15 images to GA status](https://github.blog/changelog/2025-04-10-github-actions-macos-15-and-windows-2025-images-are-now-generally-available/) on Apr 10, 2025.
The GitHub Actions runner image [macos-15](https://github.com/actions/runner-images/blob/main/images/macos/macos-15-arm64-Readme.md) is an …
=> test: update to macos-15

examples/basic-pnpm/.npmrc, examples/start-and-pnpm-workspaces/.npmrc
The `.npmrc` file in the following projects that implements the pnpm configuration [side-effects-cache=false](https://pnpm.io/9.x/npmrc#side-effects-cache) includes a link `https://pnpm.io/npmrc#side-effects-cache` which should be a comment.
Additionally, this link has moved to https://pnpm.io/settings#sideeffectscache.
- [examples/start-and-pnpm-workspaces](https://github.com/cypress-io/github-action/tree/master/examples/start-and-pnpm-workspaces)
Change the pnpm sideEffectsCache documentation link to https://pnpm.io/settings#sideeffectscache in the following projects and ensure that the link is a comment:
- [examples/basic-pnpm](https://github.com/cypress-io/github-action/tree/master/exam …
=> test: fix pnpm .npmrc

examples/component-tests/package-lock.json, examples/component-tests/package.json, examples/wait-on-vite/package-lock.json, examples/wait-on-vite/package.json
Dependabot reports a moderate severity vulnerability [CVE-2025-32395](https://github.com/advisories/GHSA-356w-63v5-8wf4) in [vite@6.2.5](https://github.com/vitejs/vite/releases/tag/v6.2.5) used in:
Update `vite` from [vite@6.2.5](https://github.com/vitejs/vite/releases/tag/v6.2.5) to [vite@6.2.6](https://github.com/vitejs/vite/releases/tag/v6.2.6) in the above examples.
=> test(deps): update vite to 6.2.6 in examples

action.yml
The action options, defined in [action.yml](https://github.com/cypress-io/github-action/blob/master/action.yml), are listed in an apparent arbitrary order. This is a barrier to maintenance, referral and documentation.
List the action options in [action.yml](https://github.com/cypress-io/github-action/blob/master/action.yml) in alphabetical order, separated into options used in the action and those passed to the [Cypress Module API](https://on.cypress.io/module-api).
Cross-reference in comments to the following sets of options:
- [Cypress Module API > Options](https://on.cypress.io/module-api#Options)
- [`cypress run` > Options](https://docs.cypress.io/app/references/command-line#Options)
=> refactor: sort and comment action.yml options

README.md, examples/basic-pnpm/.npmrc, examples/basic-pnpm/pnpm-workspace.yaml, examples/start-and-pnpm-workspaces/.npmrc, examples/start-and-pnpm-workspaces/pnpm-workspace.yaml
1. In order to disable the pnpm side effects cache, to prevent pnpm from skipping Cypress binary installation if the Cypress npm module is already cached, the [Cypress documentation > pnpm Configuration](https://docs.cypress.io/app/get-started/install-cypress#pnpm-Configuration) now recommends using:
```shell
pnpm config set side-effects-cache false --location project
```
This uses ini-syntax and is compatible with pnpm 9.x and earlier 10.x versions. Later versions, such as `pnpm@10.9.0` also accept this syntax and convert it into json-syntax using [sideEffectsCache](https://pnpm.io/settings#sideeffectscache).
2. When the above command is executed on a empty `pnpm@10.9.0` project it writes now to the file `pnpm-workspace.yaml` instead of to `.npmrc`.
3. The pnpm bookmark …
=> test: move side-effects-cache=false for pnpm

README.md
The heading [Specify auto cancel after failures](https://github.com/cypress-io/github-action/blob/master/README.md#specify-auto-cancel-after-failures) includes the verb "specify" unlike other headings describing action parameters in the [README](https://github.com/cypress-io/github-action/blob/master/README.md) document.
For consistency with other action parameter headings, change the title of the section describing the `auto-cancel-after-failures` action parameter to the matching "Auto cancel after failures" text, removing "Specify".
- supports https://github.com/cypress-io/github-action/issues/1440 so that a migration section can better refer to the `auto-cancel-after-failures` action parameter
=> docs: remove "Specify" from auto-cancel-after-failures section heading

eslint.config.mjs
ESlint reports warnings from an externally sourced Yarn Plug'n'Play module:
```text
github-action/examples/yarn-modern-pnp/.pnp.cjs
8519:4   warning  Unused eslint-disable directive (no problems were reported from 'operator-linebreak')
8570:10  warning  Unused eslint-disable directive (no problems were reported from 'no-undef')
```
Add externally sourced Yarn Plug'n'Play modules to global ignore list of [eslint.config.mjs](https://github.com/cypress-io/github-action/blob/master/eslint.config.mjs)
```json
examples/**/.pnp.*
```
Ubuntu `22.04.2` LTS, Node.js `22.14.0` LTS
```shell
git clean -xfd
npm ci
corepack enable yarn
cd examples/yarn-modern-pnp
yarn
cd ../..
npx eslint
```
and confirm no ESLint warnings or errors are shown.
=> ci: exclude yarn pnp sources from eslint checks

README.md
- partially resolves issue https://github.com/cypress-io/github-action/issues/1440
The action parameter [command](https://github.com/cypress-io/github-action/blob/master/README.md#custom-test-command) allows executing a CLI command like `npm run e2e:ci`.
This example invokes a script defined in the project's `package.json` and runs it through a CLI call, bypassing the Cypress Module API call.
Users read the documentation section [command](https://github.com/cypress-io/github-action/blob/master/README.md#custom-test-command) and understand that this is a good way to use the action, even though the caution node attempts to explain the drawbacks.
Add a "Migrating from CLI command" section
=> docs: add migrate from CLI to README

.github/workflows/example-node-versions.yml, README.md
Node.js 18.x transitioned into [End-of-life](https://github.com/nodejs/release#release-schedule) status on Apr 30, 2025.
This PR removes Node.js `18`:
- from the matrix of tested nodes under [.github/workflows/example-node-versions.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-node-versions.yml)
- from the [README > Examples](https://github.com/cypress-io/github-action/blob/master/README.md#examples) section
- from the [README > Node.js > Support](https://github.com/cypress-io/github-action/blob/master/README.md#examples) section
The section [README > `wait-on` with Node.js 18+](https://github.com/cypress-io/github-action/blob/master/README.md#wait-on-with-nodejs-18) is removed. This section describes workarounds which some environments needed to …
=> feat(deps): remove node.js 18

README.md
The [command-prefix](https://github.com/cypress-io/github-action/blob/master/README.md#command-prefix) parameter
- refers to the `default test command` without explaining what the term means
- does not explain that when used it will convert action parameters into CLI parameters and not invoke the Cypress Module API
- does not mention that it cannot be used with the custom test [command](https://github.com/cypress-io/github-action/blob/master/README.md#custom-test-command) parameter
The example refers to `npm` whereas the action uses `npx`.
- `npx` restricts the use of this parameter to package manager setups using `node_modules`
Explain how the action builds the cli command
```shell
npx <command-prefix> cypress run <options>
```
Say how this is compatible with package managers using a …
=> docs: rework command-prefix readme section

examples/component-tests/package-lock.json, examples/component-tests/package.json, examples/wait-on-vite/package-lock.json, examples/wait-on-vite/package.json
Dependabot reports a moderate severity vulnerability [CVE-2025-46565](https://github.com/advisories/GHSA-859w-5945-r5v3) in [vite@6.2.6](https://github.com/vitejs/vite/releases/tag/v6.2.5) used in:
Update `vite` from [vite@6.2.6](https://github.com/vitejs/vite/releases/tag/v6.2.6) to [vite@6.3.4](https://github.com/vitejs/vite/releases/tag/v6.3.4) (current `latest`) in the above examples.
=> test(deps): update vite to 6.3.4 in examples

dist/index.js, index.js
- closes https://github.com/cypress-io/github-action/issues/1439
- contributes to resolution of issue #1440 
When the input parameter `command` is used (see [README > Custom test command](https://github.com/cypress-io/github-action/blob/master/README.md#custom-test-command)) then multiple other command parameters are ignored without error or warning.
If related string parameters are set then they will be ignored.
Boolean input parameters are ignored if they are set different from their default settings.
Validate input parameters used together with the `command` parameter and emit a GitHub Actions annotations warning if any ignored parameters are being used.
This example contains all possible ignored parameters:
=> feat: validate other parameters against command parameter when used

.github/workflows/example-custom-command.yml, README.md
- contributes to resolution of issue #1440 
The action parameter [README > command](https://github.com/cypress-io/github-action/blob/master/README.md#custom-test-command) allows executing a CLI command like `npm run e2e:ci`.
This example invokes a script defined in the project's `package.json` and runs it through a CLI call, bypassing the Cypress Module API call.
Users reading the documentation section [command](https://github.com/cypress-io/github-action/blob/master/README.md#custom-test-command) may come to the conclusion that the `command` parameter is a good way to use the action, even though the caution note attempts to explain the drawbacks that other related action parameters are ignored.
- Make it clear when the action parameter …
=> test: rework custom test command and example

CHANGELOG.md
The [CHANGELOG](https://github.com/cypress-io/github-action/blob/master/CHANGELOG.md) is manually maintained and typically lists major and minor version updates. Individual patches are listed under [Releases](https://github.com/cypress-io/github-action/releases).
Add
| Version | Changes                                                                                                      |
| ------- | ------------------------------------------------------------------------------------------------------------ |
| v6.9.0  | Add parameter validation for `command`                                                                       |
| v6.8.0  | Examples remove Node.js 18. End of support for Node.js 18.                                                   |
| v6.7.10 | Examples updated to Cypress …
=> docs: update changelog to v6.9.0 and below

.github/workflows/example-custom-ci-build-id.yml
The workflow [.github/workflows/example-custom-ci-build-id.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-custom-ci-build-id.yml) contains hybrid use of the action, with both Module API and CLI commands beings used.
The job `smoke-tests` uses regular action parameters
```yml
record: true
parallel: true
group: '1 - smoke tests'
ci-build-id: ${{ needs.prepare.outputs.uuid }}
spec: 'cypress/e2e/spec-a.cy.js'
working-directory: examples/recording
```
The follow-on job `all-tests` uses the action with a CLI command
```yml
command: |
npx cypress run --record --parallel \
--ci-build-id ${{ needs.prepare.outputs.uuid }} \
--group "2 - all tests"
working-directory: examples/recording
```
The `command` parameter uses a CLI command to run the action, which …
=> test: harmonize example custom-ci-build-id to use module API only

.github/workflows/example-build-artifacts.yml, README.md, examples/nextjs/next.config.mjs
- contributes to closure of issue https://github.com/cypress-io/github-action/issues/1455
The repo contains no example of splitting jobs between install and test, using stored build artifacts between the jobs.
- The existing [examples/nextjs](https://github.com/cypress-io/github-action/tree/master/examples/nextjs) example project, which is currently only used in the [.github/workflows/example-wait-on.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-wait-on.yml) workflow, is used in a new workflow `.github/workflows/example-build-artifacts.yml` to show how an install job can pass on build artifacts to a test job.
- The app is tested in 3 different E2E jobs, using Ubuntu, Windows and macOS.
=> test: add example-build-artifacts workflow

README.md
- closes https://github.com/cypress-io/github-action/issues/1455
- PR https://github.com/cypress-io/github-action/pull/1456 added the example workflow [.github/workflows/example-build-artifacts.yml](https://github.com/cypress-io/github-action/blob/example-build-artifacts/.github/workflows/example-build-artifacts.yml) removing the need for similar external examples.
- The README table [More examples](https://github.com/cypress-io/github-action/blob/master/README.md#more-examples) currently contains two related external example links that are now redundant:
- https://github.com/bahmutov/cypress-examples
- https://github.com/bahmutov/cypress-gh-action-split-jobs
Remove the links
- https://github.com/bahmutov/cypress-examples
- https://github.com/bahmutov/cypress-gh-action-split-jobs
from the …
=> docs: remove external artifact examples

.github/workflows/example-node-versions.yml, README.md
[Node.js 24.0.0](https://nodejs.org/en/blog/release/v24.0.0) was released on May 6, 2025.
This PR adds Node.js `24`:
- to the matrix of tested nodes under [.github/workflows/example-node-versions.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-node-versions.yml)
- to the [README > Example](https://github.com/cypress-io/github-action/blob/master/README.md#examples) section
- to the [README > Node.js > Support](https://github.com/cypress-io/github-action/blob/master/README.md#examples) section
- Since there is no change to the action itself, and the additional support of Node.js `24.x` is an extension, there is no version change of the action
- According to [Node.js release schedule](https://github.com/nodejs/release#release-schedule) plans, Node.js …
=> tests(deps): add node.js 24 (current) support

dist/index.js, package-lock.json
npm audit and dependabot report a low severity vulnerability [CVE-2025-47279](https://github.com/advisories/GHSA-cxrh-j4jr-qwg3) in [undici](https://github.com/nodejs/undici):
- [@actions/cache@4.0.2](https://github.com/actions/toolkit/blob/main/packages/cache/RELEASES.md#402) uses `undici@5.28.5`
- [markdown-link-check@3.13.7](https://github.com/tcort/markdown-link-check/releases/tag/v3.13.7) uses `undici@6.21.1`
`npm audit fix` is used to update the `undici` dependencies as follows:
- [@actions/cache@4.0.2](https://github.com/actions/toolkit/blob/main/packages/cache/RELEASES.md#402) updated to [undici@5.29.0](https://github.com/nodejs/undici/releases/tag/v5.29.0)
- [markdown-link-check@3.13.7](https://github.com/tcort/markdown-link-check/releases/tag/v3.13.7) updated to …
=> fix(deps): update undici transitive dependency

.github/workflows/main.yml
- this may allow issue https://github.com/cypress-io/github-action/issues/1464 to be closed
Publication of release `6.9.1` was only partially successful.
The logs show
> An error occurred while running semantic-release: Error: Could not resolve to an Issue with the number of 1416.
There was a related issue resolved in [@semantic-release/github@11.0.1](https://github.com/semantic-release/github/releases/tag/v11.0.1).
Update the [main](https://github.com/cypress-io/github-action/blob/master/.github/workflows/main.yml) workflow to use `semantic_version: 24.2.3` (`latest`)
=> fix(ci): update semantic-version to 24.2.3

README.md
The example repo
- https://github.com/bahmutov/cypress-gh-action-monorepo
listed in the README table [More examples](https://github.com/cypress-io/github-action/blob/master/README.md#more-examples) is running `cypress-io/github-action@v5`, which is an outdated and unsupported action version that fails caching.
The latest `v5` version was [v5.8.4](https://github.com/cypress-io/github-action/releases/tag/v5.8.4) released in Aug 2023. This is the version that the example repo is running.
> Download action repository 'cypress-io/github-action@v5' (SHA:248bde77443c376edc45906ede03a1aba9da0462)
Errors are:
> Run cypress-io/github-action@v5
> Warning: Failed to restore: Cache service responded with 422
> Warning: Failed to restore: Cache service responded with 422
> /usr/local/bin/yarn …
=> docs: remove outdated external monorepo example from README

.github/workflows/example-custom-ci-build-id.yml, .github/workflows/example-recording.yml, CONTRIBUTING.md, docs/MAINTENANCE.md
- [Cypress 10.0.0](https://docs.cypress.io/app/references/changelog#10-0-0) was released on June 1, 2022, 3 years ago
- The [Cypress documentation website](https://docs.cypress.io/) no longer contains any configuration information for legacy Cypress version < 10
- Several documents / comments in this repo still refer to Cypress v9, although it is no longer supported.
Remove references to Cypress v9
=> docs: remove legacy v9 references

package-lock.json, package.json
Release [@stylistic/eslint-plugin@5.0.0](https://github.com/eslint-stylistic/eslint-stylistic/releases/tag/v5.0.0) is now the latest available release.
Update from [@stylistic/eslint-plugin@4.4.1](https://github.com/eslint-stylistic/eslint-stylistic/releases/tag/v4.4.1) to [@stylistic/eslint-plugin@5.0.0](https://github.com/eslint-stylistic/eslint-stylistic/releases/tag/v5.0.0)
On Ubuntu `24.04.2` LTS, Node.js `22.16.0` LTS
```shell
git clean -xfd
npm ci
npm run lint
```
and confirm that no linting errors are reported.
=> chore(deps): update @stylistic/eslint-plugin to 5.0.0

eslint.config.mjs, package-lock.json, package.json
- supersedes Renovate PR https://github.com/cypress-io/github-action/pull/1478
Release [eslint-plugin-cypress@5.1.0](https://github.com/cypress-io/eslint-plugin-cypress/releases/tag/v5.1.0) is now the latest available release.
- Update from [eslint-plugin-cypress@4.3.0](https://github.com/cypress-io/eslint-plugin-cypress/releases/tag/v4.3.0) to [eslint-plugin-cypress@5.1.0](https://github.com/cypress-io/eslint-plugin-cypress/releases/tag/v5.1.0)
- Update [eslint.config.mjs](https://github.com/cypress-io/github-action/blob/master/eslint.config.mjs) from using the deprecated configuration `eslint-plugin-cypress/flat` to using the non-deprecated default configuration `eslint-plugin-cypress`.
On Ubuntu `24.04.2` LTS, Node.js `22.16.0` LTS
```shell
git clean -xfd
npm ci
npm run lint
```
and …
=> chore(deps): update eslint-plugin-cypress to 5.1.0

examples/wait-on-vite/package-lock.json, examples/wait-on-vite/package.json
- The E2E example directory [examples/wait-on-vite](https://github.com/cypress-io/github-action/tree/master/examples/wait-on-vite) currently uses [vite@6.3.4](https://github.com/vitejs/vite/releases/tag/v6.3.4)
- [vite@7.0.0](https://github.com/vitejs/vite/releases/tag/v7.0.0) was released on June 24, 2025
- Update [examples/wait-on-vite](https://github.com/cypress-io/github-action/tree/master/examples/wait-on-vite) from [vite@6.3.4](https://github.com/vitejs/vite/releases/tag/v6.3.4) to [vite@7.0.0](https://github.com/vitejs/vite/releases/tag/v7.0.0)
- Refresh transitive dependencies in example with `npm update --save`
=> test(deps): update to vite 7 in wait-on-vite example

README.md
- The description for the [project](https://github.com/cypress-io/github-action/blob/master/README.md#project) parameter is open to misinterpretation, particularly in relation to whether it points to a complete project or just a set of Cypress tests
- The CLI description for [cypress run --project <project-path>](https://docs.cypress.io/app/references/command-line#cypress-run-project-lt-project-path-gt) lacks explanation and the linked repo https://github.com/cypress-io/cypress-test-nested-projects is outdated (legacy v9 Cypress), fails to run and is archived. Issue https://github.com/cypress-io/cypress-documentation/issues/5322 remains unaddressed
- Add an description of usage and constraints for the successful use of the `project` parameter into the [README > …
=> docs: extend project parameter description

package-lock.json, package.json
`npm audit` reports a high severity vulnerability https://github.com/advisories/GHSA-xffm-g5w8-qvg7 in [@eslint/plugin-kit](https://www.npmjs.com/package/@eslint/plugin-kit)
Take the opportunity to update related `devDependencies` to latest versions, which then supersede several individual pending Renovate PRs:
| Dependency               | Before     | After                                                                             |
| ------------------------ | ---------- | --------------------------------------------------------------------------------- |
| @eslint/js               | `9.29.0`   | [9.31.0](https://github.com/eslint/eslint/releases/tag/v9.31.0)                   |
| @stylistic/eslint-plugin | `5.0.0`    | [5.2.0](https://github.com/eslint-stylistic/eslint-stylistic/releas …
=> chore(deps): update ESLint devDependencies

package-lock.json
- resolves reporting of CVE-2025-7783 in action
`npm audit` reports https://github.com/advisories/GHSA-fjxv-7rqg-78g4 critical vulnerability CVE-2025-7783 for transient dependency [form-data@2.5.3](https://github.com/form-data/form-data/releases/tag/v2.5.3)
```
git clone https://github.com/cypress-io/github-action
cd github-action
npm ci
npm audit
```
```
$ npm audit
form-data  <2.5.4
Severity: critical
form-data uses unsafe random function in form-data for choosing boundary - https://github.com/advisories/GHSA-fjxv-7rqg-78g4
fix available via `npm audit fix`
node_modules/form-data
1 critical severity vulnerability
To address all issues, run:
npm audit fix
$ npm ls form-data
@cypress/github-action@0.0.0-development
└─┬ @actions/cache@4.0.2
└─┬ @azure/ms-rest-js@2.7.0
└── form-data@2.5.3 …
```
=> fix(deps): update form-data to 2.5.5 (CVE-2025-7783)

.github/workflows/example-basic-pnpm.yml, .github/workflows/example-basic.yml, .github/workflows/example-build-artifacts.yml, .github/workflows/example-chrome-for-testing.yml, .github/workflows/example-chrome.yml, .github/workflows/example-component-test.yml, .github/workflows/example-config.yml, .github/workflows/example-cron.yml, .github/workflows/example-custom-ci-build-id.yml, .github/workflows/example-custom-command.yml, .github/workflows/example-debug.yml, .github/workflows/example-docker.yml, .github/workflows/example-edge.yml, .github/workflows/example-env.yml, .github/workflows/example-firefox.yml, .github/workflows/example-install-command.yml, .github/workflows/example-install-only.yml, .github/workflows/example-node-versions.yml, .github/workflows/example-quiet.yml, .github/workflows/example-recording.yml, .github/workflows/example-start-and-pnpm-workspaces.yml, .github/workflows/example-start-and-yarn-workspaces.yml, .github/workflows/example-start.yml, .github/workflows/example-wait-on.yml, .github/workflows/example-webpack.yml, .github/workflows/example-yarn-classic.yml, .github/workflows/example-yarn-modern-pnp.yml, .github/workflows/example-yarn-modern.yml, README.md
Example workflows, such as [.github/workflows/example-basic.yml](https://github.com/cypress-io/github-action/blob/master/.github/workflows/example-basic.yml) include the syntax `uses: ./` to run the action from the root of the repo's current branch. This is not explained in the [README](https://github.com/cypress-io/github-action/blob/master/README.md) and the comments in the different example workflows in the [.github/workflows](https://github.com/cypress-io/github-action/blob/master/.github/workflows) are inconsistently worded. Some workflows don't contain any related remark.
- Add an explanation to the [README](https://github.com/cypress-io/github-action/blob/master/README.md) about `uses: ./`
- Add a comment to the workflows:
```yml
uses: ./ # if copying, replace with …
```
=> docs: harmonize examples 'use: ./' syntax explanation

examples/config/package-lock.json, examples/config/package.json, examples/start-and-pnpm-workspaces/package.json, examples/start-and-pnpm-workspaces/packages/workspace-1/package.json, examples/start-and-pnpm-workspaces/packages/workspace-2/package.json, examples/start-and-pnpm-workspaces/pnpm-lock.yaml, examples/start-and-yarn-workspaces/package.json, examples/start-and-yarn-workspaces/workspace-1/package.json, examples/start-and-yarn-workspaces/workspace-2/package.json, examples/start-and-yarn-workspaces/yarn.lock, examples/start/package-lock.json, examples/start/package.json
- PR https://github.com/cypress-io/github-action/pull/1524 implemented a workaround for low severity vulnerabilities CVE-2025-7339 using [on-headers](https://www.npmjs.com/package/on-headers) `< 1.1.0` as a transitive dependency of [serve@14.2.4](https://github.com/vercel/serve/releases/tag/14.2.4).
- [serve@14.2.5](https://github.com/vercel/serve/releases/tag/v14.2.5) has now been published and which mitigates the vulnerability directly by updating its dependencies.
Update from [serve@14.2.4](https://github.com/vercel/serve/releases/tag/14.2.4) to [serve@14.2.5](https://github.com/vercel/serve/releases/tag/v14.2.5) in the example directories using `serve`:
- [examples/config](https://github.com/cypress-io/github-action/tree/master/examples/config)
- …
=> test(deps): update serve to 14.2.5

examples/component-tests/cypress/support/component.js, examples/component-tests/package-lock.json, examples/component-tests/package.json, examples/component-tests/src/App.jsx, examples/component-tests/src/index.css, examples/component-tests/src/main.jsx, examples/component-tests/vite.config.js, examples/wait-on-vite/package-lock.json, examples/wait-on-vite/package.json
`npm audit` reports low severity vulnerabilities in examples using `vite` versions `6.0.0` - `6.3.5` and `7.0.0` - `7.0.6`
| Example                                                                                                      | Version                                                          |
| ------------------------------------------------------------------------------------------------------------ | ---------------------------------------------------------------- |
| [examples/component-tests](https://github.com/cypress-io/github-action/tree/master/examples/component-tests) | [vite@6.3.4](https://github.com/vitejs/vite/releases/tag/v6.3.4) |
| [examples/wait-on-vite](https://github.com/cypress-io/github-action/tree/master/examples/wait-on-vite)       | …
=> test(deps): update vite in examples to 7.1.5
